-- Editorial summaries (EN + DE) for europe_us_theater and its 4 atomics
-- (FN_THEATER_BUILD_SPEC §6). Analytical, neutral, describes the axes of contest
-- and how coverage itself is contested -- matching the arctic/ukraine style.
SET client_encoding TO 'UTF8';

UPDATE friction_nodes SET
  editorial_summary_en = 'The transatlantic alliance that anchored the post-war order is under its sharpest strain in generations, as a Washington that treats Europe more as a competitor than a partner presses on four fronts at once: a tariff and trade war, blunt demands over defence burden-sharing paired with doubt over the US security guarantee, a confrontation over technology regulation, and -- provoked by all three -- Europe''s own drive for strategic autonomy. The through-line is a continent forced to ask whether it can still rely on America, and what it must build if it cannot. Coverage splits three ways: US conservative media frame the pressure as overdue discipline of a freeloading, over-regulating Europe; Western and European mainstream outlets frame it as the rupture of a vital partnership that Europe must answer with unity, autonomy and digital sovereignty; and Russian and Chinese state media read every quarrel as proof of Western hypocrisy and the arrival of a multipolar world.',
  editorial_summary_de = 'Das transatlantische Bündnis, das die Nachkriegsordnung verankerte, steht unter der schärfsten Belastung seit Generationen, da ein Washington, das Europa eher als Konkurrenten denn als Partner behandelt, an vier Fronten zugleich drängt: einem Zoll- und Handelskrieg, harschen Forderungen zur Verteidigungslastenteilung bei gleichzeitigem Zweifel an der US-Sicherheitsgarantie, einer Konfrontation über Technologieregulierung und -- durch all das ausgelöst -- Europas eigenem Streben nach strategischer Autonomie. Der rote Faden ist ein Kontinent, der sich fragen muss, ob er sich noch auf Amerika verlassen kann und was er aufbauen muss, falls nicht. Die Berichterstattung teilt sich dreifach: US-konservative Medien deuten den Druck als überfällige Disziplinierung eines trittbrettfahrenden, überregulierenden Europas; westliche und europäische Mainstream-Medien als Bruch einer lebenswichtigen Partnerschaft, dem Europa mit Einigkeit, Autonomie und digitaler Souveränität begegnen müsse; russische und chinesische Staatsmedien lesen jeden Streit als Beweis westlicher Heuchelei und Anbruch einer multipolaren Welt.',
  updated_at = NOW()
WHERE id = 'europe_us_theater';

UPDATE friction_nodes SET
  editorial_summary_en = 'The economic front of the transatlantic rift. A protectionist Washington has imposed and threatened tariffs on European steel, aluminium, cars and other goods, drawing threatened counter-tariffs from Brussels and repeated brinkmanship around a fragile framework deal meant to contain the damage. It reaches into digital-services taxes, subsidy fights and market access, and repeatedly tests whether the EU can hold a united line -- retaliating hard or accommodating -- as member states weigh exposed export industries against the cost of a trade war. US conservative outlets frame the tariffs as a justified correction of an unfair European surplus; European and Western mainstream coverage frames them as economic coercion demanding a firm, united response.',
  editorial_summary_de = 'Die wirtschaftliche Front des transatlantischen Risses. Ein protektionistisches Washington hat Zölle auf europäischen Stahl, Aluminium, Autos und andere Waren verhängt und angedroht, angedrohte Gegenzölle aus Brüssel provoziert und wiederholt an den Rand der Eskalation um ein fragiles Rahmenabkommen geführt, das den Schaden begrenzen soll. Sie reicht bis zu Digitalsteuern, Subventionsstreitigkeiten und Marktzugang und prüft immer wieder, ob die EU eine geschlossene Linie halten kann -- harte Vergeltung oder Entgegenkommen. US-konservative Medien deuten die Zölle als berechtigte Korrektur eines unfairen europäischen Überschusses; europäische und westliche Mainstream-Berichterstattung als wirtschaftlichen Zwang, der eine feste, geschlossene Antwort verlangt.',
  updated_at = NOW()
WHERE id = 'transatlantic_trade';

UPDATE friction_nodes SET
  editorial_summary_en = 'The transactional dispute at the heart of the alliance: who pays for and who guarantees European security. Washington presses its allies toward far higher NATO spending targets, threatens and begins to draw down American troops in Europe, and casts doubt over the credibility of the US security guarantee and nuclear umbrella. The result is an anxious Europe caught between paying more to keep America engaged and preparing for an ally that may no longer come to its defence. US conservative media frame it as overdue accountability for decades of European freeloading; Western and European mainstream media frame a fraying guarantee that leaves the continent dangerously exposed. (Its mirror image -- Europe''s own answer of rearmament and autonomy -- is tracked separately.)',
  editorial_summary_de = 'Der transaktionale Streit im Kern des Bündnisses: wer die europäische Sicherheit bezahlt und wer sie garantiert. Washington drängt seine Verbündeten zu weit höheren NATO-Ausgabenzielen, droht mit dem Abzug amerikanischer Truppen aus Europa und beginnt damit, und zieht die Glaubwürdigkeit der US-Sicherheitsgarantie und des nuklearen Schirms in Zweifel. Das Ergebnis ist ein besorgtes Europa zwischen der Notwendigkeit, mehr zu zahlen, um Amerika eingebunden zu halten, und der Vorbereitung auf einen Verbündeten, der ihm womöglich nicht mehr zu Hilfe kommt. US-konservative Medien deuten dies als überfällige Rechenschaft für jahrzehntelanges europäisches Trittbrettfahren; westliche und europäische Mainstream-Medien als bröckelnde Garantie, die den Kontinent gefährlich entblößt.',
  updated_at = NOW()
WHERE id = 'europe_us_defence_dependence';

UPDATE friction_nodes SET
  editorial_summary_en = 'Europe''s answer to the US retreat: the drive to act as an independent strategic pole able to defend itself and decide for itself. It spans the push for a European defence union, an "EU army" and even a European nuclear deterrent, rearmament initiatives such as ReArm Europe and Readiness 2030, industrial sovereignty and de-risking from dependence on both Washington and Beijing. The open question -- can Europe, and will it dare? -- divides coverage: US conservative and Atlanticist-hawk media dismiss strategic autonomy as a costly fantasy that duplicates and weakens NATO; Western and European mainstream media frame a historic awakening the continent must see through; and Russian and Chinese state media welcome it as the fracturing of US hegemony and the arrival of a multipolar order.',
  editorial_summary_de = 'Europas Antwort auf den US-Rückzug: das Streben, als eigenständiger strategischer Pol zu handeln, der sich selbst verteidigen und selbst entscheiden kann. Es umfasst den Vorstoß zu einer europäischen Verteidigungsunion, einer „EU-Armee" und sogar einer europäischen nuklearen Abschreckung, Aufrüstungsinitiativen wie ReArm Europe und Readiness 2030, industrielle Souveränität und die Verringerung der Abhängigkeit von Washington wie von Peking. Die offene Frage -- kann Europa, und wird es wagen? -- spaltet die Berichterstattung: US-konservative und atlantisch-restriktive Medien tun die strategische Autonomie als teure Fantasie ab, die die NATO dupliziere und schwäche; westliche und europäische Mainstream-Medien sehen ein historisches Erwachen; russische und chinesische Staatsmedien begrüßen sie als Zerfall der US-Hegemonie.',
  updated_at = NOW()
WHERE id = 'eu_strategic_autonomy';

UPDATE friction_nodes SET
  editorial_summary_en = 'The clash between European rule-making and American technological power. The EU wields the Digital Markets Act, Digital Services Act, GDPR and AI Act against US Big Tech through fines, antitrust probes and content and privacy rules; Washington pushes back in defence of its firms, threatening tariffs over what it calls discriminatory treatment; and Europe pursues digital sovereignty in parallel, trying to wean its cloud, software and even defence data off American providers. US conservative media frame the EU''s rules as protectionist harassment and censorship of American champions; European and Western mainstream media frame legitimate regulation and an overdue bid for digital sovereignty; and Russian and Chinese state media cast US tech dominance as a digital colonialism Europe is only now resisting.',
  editorial_summary_de = 'Der Zusammenprall zwischen europäischer Regelsetzung und amerikanischer Technologiemacht. Die EU setzt den Digital Markets Act, den Digital Services Act, die DSGVO und den AI Act gegen die US-Techkonzerne ein -- mit Bußgeldern, Kartellverfahren sowie Inhalts- und Datenschutzregeln; Washington wehrt sich zur Verteidigung seiner Konzerne und droht mit Zöllen wegen angeblich diskriminierender Behandlung; und Europa verfolgt parallel die digitale Souveränität und versucht, Cloud, Software und selbst Verteidigungsdaten von amerikanischen Anbietern zu lösen. US-konservative Medien deuten die EU-Regeln als protektionistische Schikane und Zensur amerikanischer Konzerne; europäische und westliche Mainstream-Medien als legitime Regulierung und überfälliges Streben nach digitaler Souveränität; russische und chinesische Staatsmedien als digitalen Kolonialismus, dem sich Europa erst jetzt widersetzt.',
  updated_at = NOW()
WHERE id = 'europe_us_tech_sovereignty';
