-- South Asia theater: completeness fields (§6) -- bilingual name/description/
-- editorial_summary for the theater AND every atomic.
--
-- Prose rule (feedback_fn_descriptions_neutral): description_en/de and
-- editorial_summary_en/de are neutral, fact-based and evergreen -- no framing,
-- no motive attribution, no temporality. All framing lives in narratives_v2.
-- Both sides' claims are attributed to the claimant ("India says", "Kabul
-- accuses"), never asserted.

BEGIN;

-- ---------------------------------------------------------------- THEATER
UPDATE friction_nodes SET
  description_en = 'The contested borders of South Asia, where two nuclear-armed states and their neighbours dispute territory, water and responsibility for cross-border violence. Five fault lines run through it: the air campaign and border clashes between Pakistan and Afghanistan along the Durand Line; the Kashmir territorial dispute between India and Pakistan; the separatist insurgency in Balochistan; the Indus Waters Treaty, suspended by India and contested by Pakistan; and the militant attacks that each state attributes to the other. Pakistan is a party to four of the five.',
  description_de = 'Die umstrittenen Grenzen Südasiens, wo zwei Atommächte und ihre Nachbarn über Territorium, Wasser und die Verantwortung für grenzüberschreitende Gewalt streiten. Fünf Bruchlinien durchziehen die Region: die Luftangriffe und Grenzgefechte zwischen Pakistan und Afghanistan entlang der Durand-Linie; der Territorialstreit um Kaschmir zwischen Indien und Pakistan; der separatistische Aufstand in Belutschistan; der von Indien ausgesetzte und von Pakistan angefochtene Indus-Wasservertrag; sowie die militanten Anschläge, die jeder Staat dem anderen zuschreibt. Pakistan ist an vier der fünf Konflikte beteiligt.',
  editorial_summary_en = 'South Asia''s frictions are organised around Pakistan, which is a party to four of the theater''s five fault lines. The largest by volume is the conflict with Afghanistan: cross-border air strikes, clashes along the Durand Line, and short ceasefires that have repeatedly lapsed, with both governments describing the relationship in terms of open war. The India-Pakistan relationship is in a post-conflict phase a year after a ceasefire ended open hostilities; its live threads are the suspended Indus Waters Treaty, a recurring airspace ban, disputed responsibility for the Pahalgam attack, and sovereignty claims exchanged at the United Nations. Inside Pakistan, the Balochistan insurgency continues, with Islamabad attributing the attacks to Indian backing and India rejecting the charge. The India-China border, by contrast, has been quiet: talks on delimitation have resumed and Ladakh coverage has largely moved to domestic Indian politics.',
  editorial_summary_de = 'Die Reibungspunkte Südasiens ordnen sich um Pakistan, das an vier der fünf Bruchlinien des Schauplatzes beteiligt ist. Am umfangreichsten ist der Konflikt mit Afghanistan: grenzüberschreitende Luftangriffe, Gefechte entlang der Durand-Linie und kurze Waffenruhen, die wiederholt scheiterten, wobei beide Regierungen das Verhältnis als offenen Krieg bezeichnen. Das indisch-pakistanische Verhältnis befindet sich ein Jahr nach einer Waffenruhe, die offene Feindseligkeiten beendete, in einer Nachkriegsphase; aktuelle Themen sind der ausgesetzte Indus-Wasservertrag, ein wiederholt verlängertes Überflugverbot, die umstrittene Verantwortung für den Anschlag von Pahalgam und vor den Vereinten Nationen ausgetauschte Souveränitätsansprüche. Innerhalb Pakistans dauert der Aufstand in Belutschistan an, wobei Islamabad die Anschläge indischer Unterstützung zuschreibt und Indien dies zurückweist. Die indisch-chinesische Grenze ist dagegen ruhig: Gespräche über den Grenzverlauf wurden wieder aufgenommen, und die Berichterstattung über Ladakh betrifft überwiegend die indische Innenpolitik.',
  updated_at = now()
WHERE id = 'south_asia_theater';

-- ------------------------------------------- pakistan_afghanistan_border
UPDATE friction_nodes SET
  description_en = 'Armed conflict along and across the Durand Line, the frontier between Pakistan and Afghanistan that Kabul has never formally recognised. Pakistan conducts air strikes on targets in Kabul, Kandahar, Nangarhar and the eastern provinces, stating that they hit Tehreek-e-Taliban sanctuaries; the Taliban government reports civilian casualties, including a strike on a Kabul hospital, and claims retaliatory strikes inside Pakistan. Ground clashes recur around border crossings and checkposts, and successive short ceasefires have lapsed.',
  description_de = 'Bewaffneter Konflikt entlang und über die Durand-Linie hinweg, die Grenze zwischen Pakistan und Afghanistan, die Kabul nie förmlich anerkannt hat. Pakistan fliegt Luftangriffe auf Ziele in Kabul, Kandahar, Nangarhar und den östlichen Provinzen und erklärt, diese träfen Rückzugsgebiete der Tehreek-e-Taliban; die Taliban-Regierung meldet zivile Opfer, darunter einen Angriff auf ein Krankenhaus in Kabul, und gibt Vergeltungsangriffe in Pakistan an. An Grenzübergängen und Kontrollposten kommt es wiederholt zu Bodengefechten, und aufeinanderfolgende kurze Waffenruhen sind gescheitert.',
  editorial_summary_en = 'The Pakistan-Afghanistan border is the most active conflict in this theater by coverage volume. Pakistan states that its strikes target Tehreek-e-Taliban fighters who cross from Afghan territory to attack Pakistani forces and civilians, and that it acted after demands for verifiable measures went unanswered. The Taliban government accuses Pakistan of war crimes and of killing civilians, reports several hundred dead in a strike on a Kabul hospital, and says Afghan forces have struck military positions inside Pakistan. Both defence ministries have used the language of open war. Third states including China and Türkiye have offered to broker a ceasefire, and India has condemned the strikes as an assault on Afghan sovereignty. Coverage peaks with each round of strikes and subsides between them.',
  editorial_summary_de = 'Die pakistanisch-afghanische Grenze ist gemessen am Berichterstattungsvolumen der aktivste Konflikt dieses Schauplatzes. Pakistan erklärt, seine Angriffe zielten auf Kämpfer der Tehreek-e-Taliban, die von afghanischem Gebiet aus pakistanische Sicherheitskräfte und Zivilisten angreifen, und es habe gehandelt, nachdem Forderungen nach überprüfbaren Maßnahmen unbeantwortet blieben. Die Taliban-Regierung wirft Pakistan Kriegsverbrechen und die Tötung von Zivilisten vor, meldet mehrere Hundert Tote bei einem Angriff auf ein Krankenhaus in Kabul und gibt an, afghanische Kräfte hätten Militärstellungen in Pakistan getroffen. Beide Verteidigungsministerien haben von offenem Krieg gesprochen. Drittstaaten wie China und die Türkei boten Vermittlung an, und Indien verurteilte die Angriffe als Verletzung der afghanischen Souveränität. Die Berichterstattung erreicht mit jeder Angriffswelle Spitzenwerte und geht dazwischen zurück.',
  updated_at = now()
WHERE id = 'pakistan_afghanistan_border';

-- ------------------------------------------------------- kashmir_dispute
UPDATE friction_nodes SET
  description_en = 'The territorial dispute over Kashmir, divided since 1947 between areas administered by India and by Pakistan and claimed in full by both. It covers the constitutional status of Jammu and Kashmir following the 2019 changes and the unrestored statehood that followed, the status of Gilgit-Baltistan and the areas Pakistan administers, exchanges over the territory at the United Nations and other international bodies, and unrest and security operations on both sides of the line of control.',
  description_de = 'Der Territorialstreit um Kaschmir, das seit 1947 zwischen indisch und pakistanisch verwalteten Gebieten geteilt ist und von beiden Seiten vollständig beansprucht wird. Er umfasst den Verfassungsstatus von Jammu und Kaschmir nach den Änderungen von 2019 und die seither nicht wiederhergestellte Eigenstaatlichkeit, den Status von Gilgit-Baltistan und der von Pakistan verwalteten Gebiete, den Austausch über das Gebiet vor den Vereinten Nationen und anderen internationalen Gremien sowie Unruhen und Sicherheitsoperationen auf beiden Seiten der Waffenstillstandslinie.',
  editorial_summary_en = 'Kashmir remains the formal territorial dispute between India and Pakistan, though it now generates more diplomatic and constitutional coverage than military coverage. India treats the territory as an internal matter and rejects references to it by other states as unwarranted; Pakistan raises it at the UN Human Rights Council and other bodies as an unresolved dispute, and marks Kashmir Solidarity Day. Within Indian-administered Jammu and Kashmir, the restoration of statehood is contested in domestic politics. Within Pakistan-administered Kashmir, protests over refugee seats and other grievances have turned deadly. Coverage is heavily concentrated in Indian and Pakistani outlets, each reporting the other''s administration critically.',
  editorial_summary_de = 'Kaschmir bleibt der formelle Territorialstreit zwischen Indien und Pakistan, erzeugt inzwischen aber mehr diplomatische und verfassungsrechtliche als militärische Berichterstattung. Indien behandelt das Gebiet als innere Angelegenheit und weist Äußerungen anderer Staaten dazu als unzulässig zurück; Pakistan bringt es vor dem UN-Menschenrechtsrat und anderen Gremien als ungelösten Streitfall vor und begeht den Kaschmir-Solidaritätstag. Im indisch verwalteten Jammu und Kaschmir ist die Wiederherstellung der Eigenstaatlichkeit innenpolitisch umstritten. Im pakistanisch verwalteten Kaschmir sind Proteste um Flüchtlingssitze und andere Beschwerden tödlich verlaufen. Die Berichterstattung konzentriert sich stark auf indische und pakistanische Medien, die jeweils die Verwaltung der Gegenseite kritisch darstellen.',
  updated_at = now()
WHERE id = 'kashmir_dispute';

-- ------------------------------------------------ india_pakistan_militancy
UPDATE friction_nodes SET
  description_en = 'Militant attacks on Indian soil and the dispute over responsibility for them. It covers the groups India names -- Lashkar-e-Taiba, Jaish-e-Mohammed and associated figures such as Hafiz Saeed and Masood Azhar -- Indian investigations and designations, the 2025 Pahalgam attack and the Indian military operation conducted in response, and Pakistan''s rejection of the allegations. India states that the groups operate from Pakistani territory with official tolerance; Pakistan states that the allegations are unsubstantiated.',
  description_de = 'Militante Anschläge auf indischem Boden und der Streit über die Verantwortung dafür. Erfasst werden die von Indien benannten Gruppen -- Lashkar-e-Taiba, Jaish-e-Mohammed und Personen wie Hafiz Saeed und Masood Azhar --, indische Ermittlungen und Listungen, der Anschlag von Pahalgam 2025 und die daraufhin durchgeführte indische Militäroperation sowie Pakistans Zurückweisung der Vorwürfe. Indien erklärt, die Gruppen operierten mit offizieller Duldung von pakistanischem Gebiet aus; Pakistan erklärt, die Vorwürfe seien unbelegt.',
  editorial_summary_en = 'This is the accusation layer of the India-Pakistan relationship, and it is asymmetric in coverage: Indian outlets report it heavily, Pakistani outlets rarely. Indian investigators have charge-sheeted figures including Hafiz Saeed over the Pahalgam attack and traced equipment and handlers across the border; New Delhi presses for international designations and for Pakistan''s return to the FATF list. Operation Sindoor, the military response to Pahalgam, is marked in Indian coverage as a precedent for striking back, and its anniversary generates recurring commentary. Pakistan''s foreign ministry says India has never presented evidence and describes the allegations as a narrative built for political use.',
  editorial_summary_de = 'Dies ist die Vorwurfsebene des indisch-pakistanischen Verhältnisses, und die Berichterstattung ist asymmetrisch: Indische Medien behandeln sie ausführlich, pakistanische selten. Indische Ermittler haben unter anderem gegen Hafiz Saeed wegen des Anschlags von Pahalgam Anklage erhoben und Ausrüstung sowie Hintermänner jenseits der Grenze nachverfolgt; Neu-Delhi drängt auf internationale Listungen und auf Pakistans Rückkehr auf die FATF-Liste. Die Operation Sindoor, die militärische Antwort auf Pahalgam, gilt in der indischen Berichterstattung als Präzedenzfall für Gegenschläge, und ihr Jahrestag erzeugt wiederkehrende Kommentare. Pakistans Außenministerium erklärt, Indien habe nie Beweise vorgelegt, und bezeichnet die Vorwürfe als politisch nutzbares Narrativ.',
  updated_at = now()
WHERE id = 'india_pakistan_militancy';

-- --------------------------------------------------- balochistan_insurgency
UPDATE friction_nodes SET
  description_en = 'The separatist insurgency in Balochistan, Pakistan''s largest and least populous province. It covers attacks by the Baloch Liberation Army and allied groups on security forces, railways and infrastructure, Pakistani military operations in response, the detention and prosecution of Baloch political activists including Mahrang Baloch, and the province''s mineral and port development, including Gwadar. Pakistan attributes the attacks to Indian backing; India rejects the attribution.',
  description_de = 'Der separatistische Aufstand in Belutschistan, Pakistans größter und am dünnsten besiedelter Provinz. Erfasst werden Anschläge der Belutschischen Befreiungsarmee und verbündeter Gruppen auf Sicherheitskräfte, Eisenbahnen und Infrastruktur, pakistanische Militäroperationen als Reaktion darauf, die Inhaftierung und strafrechtliche Verfolgung belutschischer Aktivisten wie Mahrang Baloch sowie die Erschließung der Bodenschätze und Häfen der Provinz, einschließlich Gwadar. Pakistan schreibt die Anschläge indischer Unterstützung zu; Indien weist dies zurück.',
  editorial_summary_en = 'Balochistan produces the highest-casualty incidents inside Pakistan: coordinated attacks that killed well over a hundred people, a train bombing claimed by Baloch separatists, and military operations reported to have killed scores of fighters. Pakistani officials link the Baloch Liberation Army to Indian backing and have pressed the UN Security Council to designate it; Indian officials call the charge a deflection from internal failings, and Pakistani lawmakers have themselves described the province as approaching civil war. Alongside the violence runs a civil-rights dispute: the life sentence handed to activist Mahrang Baloch, and reported enforced disappearances. Foreign investment in the province''s minerals and in Gwadar port proceeds against this backdrop.',
  editorial_summary_de = 'Belutschistan verzeichnet die opferreichsten Vorfälle innerhalb Pakistans: koordinierte Anschläge mit weit über hundert Toten, ein von belutschischen Separatisten reklamierter Anschlag auf einen Zug und Militäroperationen, bei denen Dutzende Kämpfer getötet worden sein sollen. Pakistanische Behörden bringen die Belutschische Befreiungsarmee mit indischer Unterstützung in Verbindung und drängten den UN-Sicherheitsrat, sie zu listen; indische Stellen nennen den Vorwurf eine Ablenkung von inneren Defiziten, und pakistanische Abgeordnete haben die Lage in der Provinz selbst als bürgerkriegsnah beschrieben. Neben der Gewalt verläuft ein bürgerrechtlicher Streit: die lebenslange Haftstrafe für die Aktivistin Mahrang Baloch und Berichte über Fälle des Verschwindenlassens. Ausländische Investitionen in die Bodenschätze der Provinz und in den Hafen von Gwadar laufen vor diesem Hintergrund weiter.',
  updated_at = now()
WHERE id = 'balochistan_insurgency';

-- ----------------------------------------------------- indus_water_sharing
UPDATE friction_nodes SET
  description_en = 'The dispute over the Indus Waters Treaty, the 1960 World Bank-brokered agreement allocating the Indus basin rivers between India and Pakistan. It covers India''s suspension of the treaty and Pakistan''s demands for its restoration, Indian projects on the Chenab and the other western rivers, proceedings before the Court of Arbitration and the Permanent Indus Commission, and Pakistan''s representations to the UN Security Council. India describes the treaty as outdated; Pakistan describes it as valid, binding and operative.',
  description_de = 'Der Streit um den Indus-Wasservertrag, das 1960 von der Weltbank vermittelte Abkommen zur Aufteilung der Flüsse des Indus-Beckens zwischen Indien und Pakistan. Erfasst werden Indiens Aussetzung des Vertrags und Pakistans Forderungen nach seiner Wiederherstellung, indische Projekte am Chenab und den übrigen westlichen Flüssen, Verfahren vor dem Schiedsgerichtshof und der Ständigen Induskommission sowie Pakistans Eingaben an den UN-Sicherheitsrat. Indien bezeichnet den Vertrag als überholt; Pakistan bezeichnet ihn als gültig, bindend und in Kraft.',
  editorial_summary_en = 'Water is the live lever in the India-Pakistan relationship. India suspended participation in the Indus Waters Treaty and has fast-tracked projects on the western rivers; its foreign ministry describes its position as consistent and the treaty as belonging to another era. Pakistan, wholly downstream, treats the suspension as unlawful: its president and ministers have called for restoration on World Water Day and at the UN, its deputy prime minister has written to the Security Council, and a defence minister has framed the issue in terms of war. A Court of Arbitration has issued findings, including a pondage award that India rejects. The dispute is a small share of overall coverage but recurs steadily and rises whenever a project or ruling advances.',
  editorial_summary_de = 'Wasser ist der aktive Hebel im indisch-pakistanischen Verhältnis. Indien hat seine Teilnahme am Indus-Wasservertrag ausgesetzt und Projekte an den westlichen Flüssen beschleunigt; sein Außenministerium bezeichnet die eigene Position als konsistent und den Vertrag als einer anderen Zeit zugehörig. Pakistan, vollständig flussabwärts gelegen, hält die Aussetzung für rechtswidrig: Präsident und Minister forderten am Weltwassertag und vor den UN die Wiederherstellung, der stellvertretende Ministerpräsident wandte sich schriftlich an den Sicherheitsrat, und ein Verteidigungsminister formulierte die Frage in Kriegsbegriffen. Ein Schiedsgerichtshof hat Entscheidungen getroffen, darunter einen Schiedsspruch zur Speicherhaltung, den Indien zurückweist. Der Streit macht einen kleinen Teil der Gesamtberichterstattung aus, kehrt aber stetig wieder und nimmt zu, sobald ein Projekt oder eine Entscheidung voranschreitet.',
  updated_at = now()
WHERE id = 'indus_water_sharing';

COMMIT;
