-- Editorial summaries (EN + DE) for arctic_theater and its 4 atomics.
-- Analytical, neutral, describes the axes of contest and how coverage itself is
-- contested -- matching the ukraine_war_theater / ukraine_infrastructure_war style.
SET client_encoding TO 'UTF8';

UPDATE friction_nodes SET
  editorial_summary_en = 'The Arctic is emerging as a distinct arena of great-power competition as retreating sea ice opens once-inaccessible waters, seabed and sea lanes. It draws in the eight Arctic states plus China as a self-declared "near-Arctic" power, along four axes: the militarization of the High North and NATO''s northern expansion; the race for Arctic hydrocarbons and critical minerals; control of the emerging shipping routes; and — dominating current coverage — the confrontation over Greenland, where a US push for control has ruptured transatlantic relations. Warming is both the enabler that opens access and a planetary alarm running beneath all four. Coverage is sharply contested: Western outlets frame Russian and Chinese activity as encroachment requiring deterrence, Moscow and Beijing frame NATO''s build-up as the destabilizing provocation, and the same US move on Greenland is read as strategic necessity, unacceptable coercion, or imperial hypocrisy depending on the outlet.',
  editorial_summary_de = 'Die Arktis entwickelt sich zu einer eigenständigen Arena des Großmächte-Wettbewerbs, da das zurückweichende Meereis einst unzugängliche Gewässer, Meeresböden und Seewege öffnet. Sie zieht die acht Arktis-Staaten sowie China als selbsternannte "arktisnahe" Macht an — entlang vier Achsen: die Militarisierung des hohen Nordens und die Nordausdehnung der NATO; das Rennen um arktische Kohlenwasserstoffe und kritische Rohstoffe; die Kontrolle über die entstehenden Schifffahrtsrouten; und — die aktuelle Berichterstattung dominierend — die Konfrontation um Grönland, wo ein US-Vorstoß zur Kontrolle die transatlantischen Beziehungen zerrüttet hat. Die Erwärmung ist zugleich Wegbereiter des Zugangs und planetarer Alarm unter allen vier Achsen. Die Berichterstattung ist stark umkämpft: westliche Medien deuten russische und chinesische Aktivitäten als Vordringen, das Abschreckung erfordert, Moskau und Peking deuten den NATO-Aufbau als destabilisierende Provokation, und derselbe US-Vorstoß in Grönland gilt je nach Medium als strategische Notwendigkeit, inakzeptabler Zwang oder imperiale Heuchelei.',
  updated_at = NOW()
WHERE id = 'arctic_theater';

UPDATE friction_nodes SET
  editorial_summary_en = 'Greenland has become the sharpest flashpoint of Arctic geopolitics after Washington escalated a long-standing interest into an open push for control, backed by tariff threats against European allies who object. The island''s value is triple — Arctic military basing at Pituffik, rare-earth minerals, and the sea lanes opening off its coast — but the confrontation runs along a transatlantic axis: the United States against Denmark, the EU and NATO partners, with Greenlanders'' own voice for self-determination cutting across both. Four readings compete: a US strategic, manifest-destiny claim that is thinly held; a European defense of Danish sovereignty and international law; a Greenlandic insistence that only Greenlanders decide; and a pro-Kremlin and Chinese framing that treats the episode not as support for a US takeover but as proof of Western imperialism and hypocrisy, amplifying the rift it opens.',
  editorial_summary_de = 'Grönland ist zum schärfsten Brennpunkt der arktischen Geopolitik geworden, nachdem Washington ein langjähriges Interesse zu einem offenen Vorstoß zur Kontrolle eskaliert hat, untermauert durch Zolldrohungen gegen widersprechende europäische Verbündete. Der Wert der Insel ist dreifach — arktische Militärstützpunkte in Pituffik, Seltene Erden und die vor ihrer Küste entstehenden Seewege — doch die Konfrontation verläuft transatlantisch: die USA gegen Dänemark, die EU und NATO-Partner, mit der grönländischen Stimme für Selbstbestimmung quer dazu. Vier Lesarten konkurrieren: ein dünn vertretener strategischer US-Machtanspruch; eine europäische Verteidigung dänischer Souveränität und des Völkerrechts; ein grönländisches Beharren darauf, dass nur Grönländer entscheiden; und eine pro-Kreml- und chinesische Rahmung, die die Episode nicht als Zustimmung zu einer US-Übernahme deutet, sondern als Beweis westlicher Heuchelei und Imperialismus.',
  updated_at = NOW()
WHERE id = 'greenland_control';

UPDATE friction_nodes SET
  editorial_summary_en = 'The High North is re-militarizing. Russia has rebuilt Cold-War-era bases and its Northern Fleet along the Kola Peninsula and Barents Sea; NATO, enlarged by Finnish and Swedish accession, has answered with exercises such as Arctic Sentry, Cold Response and Nordic Response, reinforcement of its northern flank and new basing, increasingly shadowed by Sino-Russian cooperation. The contest is over who is the provocateur: Western and Nordic coverage frames the build-up as necessary deterrence against a growing Russian and Chinese threat, while Russian and Chinese state media reverse the causality, casting NATO expansion as the destabilizing militarization of a once-low-tension zone and an encirclement of Russia.',
  editorial_summary_de = 'Der hohe Norden militarisiert sich erneut. Russland hat Stützpunkte aus dem Kalten Krieg und seine Nordflotte entlang der Kola-Halbinsel und der Barentssee wiederaufgebaut; die durch den finnischen und schwedischen Beitritt vergrößerte NATO hat mit Übungen wie Arctic Sentry, Cold Response und Nordic Response, der Verstärkung ihrer Nordflanke und neuen Stützpunkten geantwortet, zunehmend begleitet von russisch-chinesischer Kooperation. Umstritten ist, wer der Provokateur ist: westliche und nordische Berichterstattung sieht den Aufbau als notwendige Abschreckung gegen eine wachsende russische und chinesische Bedrohung, während russische und chinesische Staatsmedien die Kausalität umkehren und die NATO-Erweiterung als destabilisierende Militarisierung einer einst spannungsarmen Zone und Einkreisung Russlands darstellen.',
  updated_at = NOW()
WHERE id = 'arctic_military_presence';

UPDATE friction_nodes SET
  editorial_summary_en = 'As the ice retreats it exposes an estimated fortune in Arctic hydrocarbons and critical minerals — Russia''s Yamal gas and Vostok oil, Norway''s Barents fields, Alaska''s Willow project, Greenland''s rare earths — turning the region into a resource frontier contested by Arctic states and China alike. Two stances frame it: a development camp of Russian state and Western energy press that treats extraction as a legitimate, economically vital sovereign right, and its own critics, who warn that the same warming that opens access — record-low sea ice, thawing permafrost, black carbon — is a climate emergency that drilling, mining and shipping only compound. Because the outlets reporting the resource boom often sound the environmental alarm too, the split is one of framing rather than of camp.',
  editorial_summary_de = 'Mit dem Rückzug des Eises tritt ein geschätztes Vermögen an arktischen Kohlenwasserstoffen und kritischen Rohstoffen zutage — Russlands Jamal-Gas und Wostok-Öl, Norwegens Barents-Felder, Alaskas Willow-Projekt, Grönlands Seltene Erden — und macht die Region zu einer Rohstoff-Grenze, um die Arktis-Staaten und China gleichermaßen konkurrieren. Zwei Haltungen rahmen dies: ein Entwicklungslager aus russischer Staats- und westlicher Energiepresse, das die Förderung als legitimes, wirtschaftlich wichtiges souveränes Recht betrachtet, und dessen eigene Kritiker, die warnen, dass dieselbe Erwärmung, die den Zugang öffnet — Rekordtief beim Meereis, tauender Permafrost, Ruß — ein Klimanotstand ist, den Bohrungen, Bergbau und Schifffahrt nur verschärfen. Da dieselben Medien Boom und Umweltalarm berichten, ist die Trennung eine der Rahmung, nicht des Lagers.',
  updated_at = NOW()
WHERE id = 'arctic_resources_competition';

UPDATE friction_nodes SET
  editorial_summary_en = 'Warming is opening sea routes that could reshape global trade — the Northern Sea Route along Russia''s coast, the Northwest Passage through Canada''s archipelago, and a future transpolar route — cutting weeks off Asia-Europe voyages. Russia is developing the Northern Sea Route with a nuclear-icebreaker fleet and the port of Sabetta, and China has folded the corridor into a "Polar Silk Road". Coverage divides between an opportunity framing from Russian, Chinese and commercial press that presents the routes as a shared economic prospect to be developed, and a strategic-threat framing from Western security press that sees Russian control of the passage, Chinese encroachment and a sanctions-evading "shadow fleet" as risks requiring monitoring and freedom-of-navigation assertion.',
  editorial_summary_de = 'Die Erwärmung öffnet Seewege, die den globalen Handel umgestalten könnten — die Nordostpassage entlang der russischen Küste, die Nordwestpassage durch den kanadischen Archipel und eine künftige transpolare Route — und verkürzt Asien-Europa-Fahrten um Wochen. Russland entwickelt die Nordostpassage mit einer Flotte nuklearer Eisbrecher und dem Hafen Sabetta, und China hat den Korridor in eine "polare Seidenstraße" eingebettet. Die Berichterstattung teilt sich zwischen einer Chancen-Rahmung aus russischer, chinesischer und kommerzieller Presse, welche die Routen als gemeinsame wirtschaftliche Perspektive zur Entwicklung präsentiert, und einer Bedrohungs-Rahmung aus westlicher Sicherheitspresse, welche die russische Kontrolle der Passage, chinesisches Vordringen und eine sanktionsumgehende "Schattenflotte" als überwachungsbedürftige Risiken sieht.',
  updated_at = NOW()
WHERE id = 'arctic_shipping_routes';
