-- Outlet editorial descriptions generated by DeepSeek.
-- Populated by scripts/generate_outlet_descriptions.py (one-shot + re-runnable).
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS description     TEXT;
ALTER TABLE feeds ADD COLUMN IF NOT EXISTS description_de  TEXT;
