-- fn_anchor bundles for EUROPE theater atomic FNs
-- Approach: Real corpus keywords + semantic grouping (same as Australia)
-- 10 languages: EN, AR, DE, ES, FR, HI, IT, JA, RU, ZH
-- 2026-06-23

INSERT INTO taxonomy_v3 (
  taxonomy_function,
  linked_id,
  item_raw,
  aliases,
  is_active
) VALUES

-- UKRAINE_WAR_THEATER ATOMICS
(
  'fn_anchor',
  'ukraine_battlefield',
  'ukraine_battlefield',
  '{"en": ["ukraine battlefield", "frontline", "military operations", "ceasefire", "war crimes", "territorial control", "kharkiv", "donetsk", "luhansk", "zaporizhzhia", "crimea", "snake island", "mariupol", "bakhmut", "severodonetsk", "battlefield losses"], "ar": ["ساحة المعركة الأوكرانية", "خط المواجهة", "العمليات العسكرية", "وقف إطلاق النار", "جرائم الحرب", "السيطرة الإقليمية", "خاركيف", "دونيتسك", "لوهانسك", "زابوريجيا", "القرم", "جزيرة الثعبان", "ماريوبول", "باخموت"], "de": ["ukrainisches Schlachtfeld", "Frontlinie", "Militäreinsätze", "Waffenstillstand", "Kriegsverbrechen", "Territoriale Kontrolle", "Charkiw", "Donezk", "Luhansk", "Saporischschja", "Krim", "Schlangeninsel", "Mariupol", "Bachmut"], "es": ["campo de batalla ucraniano", "línea del frente", "operaciones militares", "alto el fuego", "crímenes de guerra", "control territorial", "járkiv", "donetsk", "lugansk", "zapo rizhzhia", "crimea", "isla serpiente", "mariúpol", "bajmut"], "fr": ["champ de bataille ukrainien", "ligne de front", "opérations militaires", "cessez-le-feu", "crimes de guerre", "contrôle territorial", "Kharkiv", "Donetsk", "Louhansk", "Zaporijia", "Crimée", "île du Serpent", "Marioupol", "Bakhmout"], "hi": ["यूक्रेन युद्धक्षेत्र", "मोर्चा", "सैन्य अभियान", "संघर्ष विराम", "युद्ध अपराध", "क्षेत्रीय नियंत्रण", "खार्कीव", "दोनेत्स्क", "लुहान्स्क", "ज़ापोरिज़्ज़िया", "क्रीमिया", "सांप द्वीप", "मारियुपोल", "बाख़मुत"], "it": ["campo di battaglia ucraino", "linea del fronte", "operazioni militari", "cessate il fuoco", "crimini di guerra", "controllo territoriale", "Kharkiv", "Donetsk", "Luhansk", "Zaporizhzhia", "Crimea", "isola del Serpente", "Mariupol", "Bakhmut"], "ja": ["ウクライナ戦場", "前線", "軍事作戦", "停戦", "戦争犯罪", "領土支配", "ハルキウ", "ドネツク", "ルハンシク", "ザポリージャ", "クリミア", "ヘビ島", "マリウポリ", "バフムト"], "ru": ["украинское поле боя", "линия фронта", "военные операции", "прекращение огня", "военные преступления", "территориальный контроль", "Харьков", "Донецк", "Луганск", "Запорожье", "Крым", "остров Змеиный", "Мариуполь", "Бахмут"], "zh": ["乌克兰战场", "前线", "军事行动", "停火", "战争罪行", "领土控制", "哈尔科夫", "顿涅茨克", "卢甘斯克", "扎波罗热", "克里米亚", "蛇岛", "玛丽乌波尔", "巴赫穆特"]}'::jsonb,
  true
),
(
  'fn_anchor',
  'western_aid_to_ukraine',
  'western_aid_to_ukraine',
  '{"en": ["military aid", "weapons supply", "aid package", "defense assistance", "patriot missile", "leopard tank", "abrams tank", "artillery ammunition", "air defense", "training mission", "lend lease", "financial support", "humanitarian aid", "reconstruction"], "ar": ["المساعدات العسكرية", "توريد الأسلحة", "حزمة مساعدات", "المساعدة الدفاعية", "صاروخ باتريوت", "دبابة ليوبارد", "دبابة أبرامس", "ذخيرة المدفعية", "الدفاع الجوي", "مهمة تدريب", "قرض عقار", "الدعم المالي", "المساعدات الإنسانية"], "de": ["Militärhilfe", "Waffenversorgung", "Hilfspaket", "Verteidigungshilfe", "Patriot-Rakete", "Leopard-Panzer", "Abrams-Panzer", "Artilleriemunition", "Luftverteidigung", "Schulungsmission", "Leasing-Leihe", "finanzielle Unterstützung", "humanitäre Hilfe"], "es": ["ayuda militar", "suministro de armas", "paquete de ayuda", "asistencia defensiva", "misil patriota", "tanque leopardo", "tanque abrams", "munición de artillería", "defensa aérea", "misión de entrenamiento", "préstamo arrendamiento", "apoyo financiero", "ayuda humanitaria"], "fr": ["aide militaire", "fourniture d''armes", "paquet d''aide", "assistance défensive", "missile Patriot", "char Léopard", "char Abrams", "munitions d''artillerie", "défense aérienne", "mission d''entraînement", "prêt-bail", "soutien financier", "aide humanitaire"], "hi": ["सैन्य सहायता", "हथियार आपूर्ति", "सहायता पैकेज", "रक्षा सहायता", "देशभक्त मिसाइल", "तेंदुए टैंक", "एब्राम्स टैंक", "तोपखाना गोला-बारूद", "वायु रक्षा", "प्रशिक्षण मिशन", "पट्टे-पट्टे", "वित्तीय समर्थन", "मानवीय सहायता"], "it": ["aiuto militare", "fornitura di armi", "pacchetto di aiuti", "assistenza difensiva", "missile Patriot", "carro Leopard", "carro Abrams", "munizioni di artiglieria", "difesa aerea", "missione di addestramento", "prestito leasing", "sostegno finanziario", "aiuti umanitari"], "ja": ["軍事援助", "武器供給", "援助パッケージ", "防御支援", "パトリオットミサイル", "レオパルド戦車", "エイブラムス戦車", "砲兵弾薬", "防空", "訓練任務", "リースバック", "財政支援", "人道支援"], "ru": ["военная помощь", "поставки вооружения", "пакет помощи", "оборонная помощь", "ракета Patriot", "танк Leopard", "танк Abrams", "артиллерийские боеприпасы", "противовоздушная оборона", "учебная миссия", "лизинг", "финансовая поддержка", "гуманитарная помощь"], "zh": ["军事援助", "武器供应", "援助方案", "防务援助", "爱国者导弹", "豹式坦克", "艾布拉姆斯坦克", "火炮弹药", "防空", "培训任务", "租赁贷款", "财政支持", "人道援助"]}'::jsonb,
  true
),
(
  'fn_anchor',
  'ukraine_peace_negotiations',
  'ukraine_peace_negotiations',
  '{"en": ["peace negotiation", "ceasefire deal", "peace summit", "territorial integrity", "nato accession", "reparations", "war crimes tribunal", "frozen conflict", "ankara talks", "istanbul framework", "settlement terms", "diplomatic channel", "neutral status"], "ar": ["مفاوضات السلام", "صفقة وقف إطلاق النار", "قمة السلام", "التكامل الإقليمي", "الانضمام إلى الناتو", "التعويضات", "محكمة جرائم الحرب", "النزاع المتجمد", "محادثات أنقرة", "إطار إسطنبول", "شروط التسوية", "القناة الدبلوماسية", "وضع محايد"], "de": ["Friedensverhandlungen", "Waffenstillstandsabkommen", "Friedensgipfel", "Territoriale Integrität", "NATO-Beitritt", "Reparationen", "Kriegsverbrechertribunal", "eingefrorener Konflikt", "Ankara-Gespräche", "Istanbul-Rahmen", "Regelungsbedingungen", "diplomatischer Kanal", "neutraler Status"], "es": ["negociaciones de paz", "acuerdo de alto el fuego", "cumbre de paz", "integridad territorial", "adhesión a la OTAN", "reparaciones", "tribunal de crímenes de guerra", "conflicto congelado", "conversaciones de Ankara", "marco de Estambul", "términos de liquidación", "canal diplomático", "estatus neutral"], "fr": ["négociations de paix", "accord de cessez-le-feu", "sommet de la paix", "intégrité territoriale", "adhésion à l''OTAN", "réparations", "tribunal des crimes de guerre", "conflit gelé", "pourparlers d''Ankara", "cadre d''Istanbul", "conditions de règlement", "canal diplomatique", "statut neutre"], "hi": ["शांति वार्ता", "संघर्ष विराम समझौता", "शांति शिखर सम्मेलन", "क्षेत्रीय अखंडता", "नाटो सदस्यता", "मुआवजा", "युद्ध अपराध अदालत", "जमी हुई संघर्ष", "अंकारा बातचीत", "इस्तांबुल ढांचा", "निपटान शर्तें", "कूटनीतिक चैनल", "तटस्थ स्थिति"], "it": ["negoziati di pace", "accordo di cessate il fuoco", "vertice della pace", "integrità territoriale", "adesione alla NATO", "risarcimenti", "tribunale per i crimini di guerra", "conflitto congelato", "colloqui di Ankara", "quadro di Istanbul", "termini di regolamento", "canale diplomatico", "status neutrale"], "ja": ["平和交渉", "停戦協定", "平和サミット", "領土保全", "NATO加盟", "賠償金", "戦争犯罪法廷", "凍結紛争", "アンカラ交渉", "イスタンブール枠組み", "和解条件", "外交チャネル", "中立地位"], "ru": ["мирные переговоры", "соглашение о прекращении огня", "миротворческий саммит", "территориальная целостность", "вступление в НАТО", "репарации", "трибунал по военным преступлениям", "замороженный конфликт", "переговоры в Анкаре", "стамбульская база", "условия урегулирования", "дипломатический канал", "нейтральный статус"], "zh": ["和平谈判", "停火协议", "和平峰会", "领土完整", "北约入选", "赔偿金", "战争罪行法庭", "冻结冲突", "安卡拉会谈", "伊斯坦布尔框架", "解决条件", "外交渠道", "中立地位"]}'::jsonb,
  true
),

-- RUSSIA_EUROPE_THEATER ATOMICS
(
  'fn_anchor',
  'nato_deterrence',
  'nato_deterrence',
  '{"en": ["NATO deterrence", "NATO deployment", "eastern flank", "air defense", "missile defense", "military exercise", "nato expansion", "estonia", "latvia", "lithuania", "baltic defense", "nuclear deterrent", "strategic message"], "ar": ["ردع الناتو", "نشر الناتو", "الجناح الشرقي", "الدفاع الجوي", "دفاع صاروخي", "تمرين عسكري", "توسع الناتو", "إستونيا", "لاتفيا", "ليتوانيا", "الدفاع البلطيقي", "الردع النووي", "الرسالة الاستراتيجية"], "de": ["NATO-Abschreckung", "NATO-Einsatz", "östliche Flanke", "Luftverteidigung", "Raketenabwehr", "Militärübung", "NATO-Erweiterung", "Estland", "Lettland", "Litauen", "baltische Verteidigung", "nukleares Abschreckungsmittel", "strategische Botschaft"], "es": ["disuasión de la OTAN", "despliegue de la OTAN", "flanco oriental", "defensa aérea", "defensa de misiles", "ejercicio militar", "expansión de la OTAN", "estonia", "letonia", "lituania", "defensa báltica", "disuasión nuclear", "mensaje estratégico"], "fr": ["dissuasion de l''OTAN", "déploiement de l''OTAN", "flanc oriental", "défense aérienne", "défense antimissile", "exercice militaire", "expansion de l''OTAN", "Estonie", "Lettonie", "Lituanie", "défense balte", "dissuasion nucléaire", "message stratégique"], "hi": ["नाटो निरोध", "नाटो तैनाती", "पूर्वी फ्लैंक", "वायु रक्षा", "मिसाइल रक्षा", "सैन्य व्यायाम", "नाटो विस्तार", "एस्टोनिया", "लातविया", "लिथुआनिया", "बाल्टिक रक्षा", "परमाणु निरोध", "रणनीतिक संदेश"], "it": ["deterrenza NATO", "dispiegamento NATO", "fianco orientale", "difesa aerea", "difesa antimissile", "esercizio militare", "espansione NATO", "Estonia", "Lettonia", "Lituania", "difesa baltica", "deterrente nucleare", "messaggio strategico"], "ja": ["NATO抑止力", "NATO展開", "東側側面", "防空", "ミサイル防衛", "軍事演習", "NATO拡大", "エストニア", "ラトビア", "リトアニア", "バルト防衛", "核抑止力", "戦略的メッセージ"], "ru": ["отвод НАТО", "развёртывание НАТО", "восточный фланг", "противовоздушная оборона", "противоракетная оборона", "военные учения", "расширение НАТО", "Эстония", "Латвия", "Литва", "балтийская оборона", "ядерный отвод", "стратегическое сообщение"], "zh": ["北约威慑", "北约部署", "东侧翼", "防空", "导弹防御", "军事演习", "北约扩展", "爱沙尼亚", "拉脱维亚", "立陶宛", "波罗的防御", "核威慑", "战略信息"]}'::jsonb,
  true
),
(
  'fn_anchor',
  'sanctions_and_economy',
  'sanctions_and_economy',
  '{"en": ["sanctions regime", "economic sanctions", "oil embargo", "energy embargo", "gas supply", "price cap", "shadow fleet", "secondary sanctions", "financial freeze", "swift sanctions", "ruble collapse", "inflation russia", "economic pressure"], "ar": ["نظام العقوبات", "العقوبات الاقتصادية", "حظر النفط", "حظر الطاقة", "إمدادات الغاز", "سقف السعر", "الأسطول الظل", "العقوبات الثانوية", "التجميد المالي", "عقوبات سويفت", "انهيار الروبل", "التضخم الروسي", "الضغط الاقتصادي"], "de": ["Sanktionsregime", "Wirtschaftssanktionen", "Ölembargo", "Energieembargo", "Gasversorgung", "Preisdeckel", "Schattenflotte", "Sekundärsanktionen", "finanzielle Gefrierung", "SWIFT-Sanktionen", "Rubel-Zusammenbruch", "russische Inflation", "wirtschaftlicher Druck"], "es": ["régimen de sanciones", "sanciones económicas", "embargo de petróleo", "embargo de energía", "suministro de gas", "tope de precios", "flota fantasma", "sanciones secundarias", "congelación financiera", "sanciones SWIFT", "colapso del rublo", "inflación rusa", "presión económica"], "fr": ["régime de sanctions", "sanctions économiques", "embargo pétrolier", "embargo énergétique", "fourniture de gaz", "plafond des prix", "flotte fantôme", "sanctions secondaires", "gel financier", "sanctions SWIFT", "effondrement du rouble", "inflation russe", "pression économique"], "hi": ["प्रतिबंध व्यवस्था", "आर्थिक प्रतिबंध", "तेल प्रतिबंध", "ऊर्जा प्रतिबंध", "गैस आपूर्ति", "मूल्य सीमा", "छाया बेड़ा", "माध्यमिक प्रतिबंध", "वित्तीय जमीकरण", "स्विफ्ट प्रतिबंध", "रूबल पतन", "रूसी मुद्रास्फीति", "आर्थिक दबाव"], "it": ["regime di sanzioni", "sanzioni economiche", "embargo petrolifero", "embargo energetico", "fornitura di gas", "tetto dei prezzi", "flotta fantasma", "sanzioni secondarie", "congelamento finanziario", "sanzioni SWIFT", "crollo del rublo", "inflazione russa", "pressione economica"], "ja": ["制裁体制", "経済制裁", "石油禁輸", "エネルギー禁輸", "ガス供給", "価格上限", "シャドー艦隊", "二次制裁", "金融凍結", "SWIFT制裁", "ルーブル崩壊", "ロシアインフレ", "経済的圧力"], "ru": ["режим санкций", "экономические санкции", "нефтяное эмбарго", "энергетическое эмбарго", "поставки газа", "ценовой потолок", "теневой флот", "вторичные санкции", "финансовое замораживание", "санкции SWIFT", "крах рубля", "российская инфляция", "экономическое давление"], "zh": ["制裁制度", "经济制裁", "石油禁运", "能源禁运", "天然气供应", "价格上限", "影子舰队", "二级制裁", "金融冻结", "SWIFT制裁", "卢布崩溃", "俄罗斯通胀", "经济压力"]}'::jsonb,
  true
)

ON CONFLICT DO NOTHING;
