-- Mexico theater: completeness fields (neutral/evergreen descriptions,
-- bilingual editorial summaries, German-orthography fixes). LOCAL 2026-07-18.
-- Idempotent UPDATEs only.

BEGIN;

-- Theater: broaden + neutralize description (was military-only framed);
-- add bilingual editorial summary.
UPDATE friction_nodes SET
  description_en = 'Confrontation between the United States and Mexico across three fronts: the cartel war and Mexico''s security response, US intervention pressure against Mexico''s sovereignty, and tariff, border and migration leverage.',
  description_de = 'Konfrontation zwischen den USA und Mexiko an drei Fronten: der Kartellkrieg und Mexikos Sicherheitsantwort, US-Interventionsdruck gegenüber Mexikos Souveränität sowie Zoll-, Grenz- und Migrationsdruckmittel.',
  editorial_summary_en = 'The US-Mexico relationship has hardened into a confrontation across three fronts, driven by Washington''s use of security and economic pressure on its southern neighbour. On the ground, Mexico''s own war against the Sinaloa and Jalisco New Generation cartels — leader captures, army operations, and the corruption and collusion that shadow them — is the substrate. Over it the United States has layered coercive security pressure: covert CIA operations (including the deaths of officers in Chihuahua), indictments of Mexican officials, and threats of unilateral military action against cartels on Mexican soil. In parallel runs economic and border leverage — tariff threats, USMCA renegotiation, and demands on migration, deportation and border enforcement. President Sheinbaum''s government answers with a sovereignty red line of cooperation without subordination. Coverage splits sharply: US conservative outlets frame the pressure as justified leverage against a failed partner; Mexican and Hispanic-American media as a violation of sovereignty and dignity; Western mainstream and business press through scandal, diplomacy and market disruption; and Russian and Chinese state media as proof of American imperialism in its own backyard.',
  editorial_summary_de = 'Die Beziehung zwischen den USA und Mexiko hat sich zu einer Konfrontation an drei Fronten verhärtet, getrieben von Washingtons Einsatz sicherheitspolitischen und wirtschaftlichen Drucks auf seinen südlichen Nachbarn. Am Boden bildet Mexikos eigener Krieg gegen die Kartelle von Sinaloa und Jalisco Nueva Generación — Festnahmen von Anführern, Armeeoperationen sowie die begleitende Korruption und Kollusion — das Substrat. Darüber haben die USA sicherheitspolitischen Zwang gelegt: verdeckte CIA-Operationen (darunter der Tod von Beamten in Chihuahua), Anklagen gegen mexikanische Amtsträger und Drohungen mit einseitigen Militäraktionen gegen Kartelle auf mexikanischem Boden. Parallel verläuft wirtschaftlicher und grenzpolitischer Druck — Zolldrohungen, USMCA-Neuverhandlung und Forderungen zu Migration, Abschiebung und Grenzsicherung. Die Regierung von Präsidentin Sheinbaum antwortet mit einer roten Souveränitätslinie: Kooperation ohne Unterordnung. Die Berichterstattung ist stark gespalten: US-konservative Medien deuten den Druck als gerechtfertigtes Druckmittel gegen einen gescheiterten Partner; mexikanische und hispanoamerikanische Medien als Verletzung von Souveränität und Würde; westliche Mainstream- und Wirtschaftspresse über Skandal, Diplomatie und Marktstörungen; und russische und chinesische Staatsmedien als Beweis amerikanischen Imperialismus im eigenen Hinterhof.'
WHERE id = 'mexico_theater';

-- Cartel war: fix German orthography; add editorial summary.
UPDATE friction_nodes SET
  description_de = 'Großoperationen gegen CJNG und Sinaloa, Festnahmen und Tötungen von Kartellführern und die Militarisierung der inneren Sicherheit Mexikos.',
  editorial_summary_en = 'Mexico''s confrontation with its drug cartels centres on the Sinaloa Cartel and the Jalisco New Generation Cartel (CJNG), fought through militarised operations, high-profile leader captures and extraditions to the United States, and running violence that has not been durably reduced. The story carries a persistent own-goal dimension: indictments and arrests reaching into the state itself — a Sinaloa governor accused of cartel ties, a former state security chief in US custody — feed a narco-state critique of collusion, corruption and impunity that even sympathetic outlets advance. Coverage divides between a security-offensive reading that treats captures as progress, a friendly-critic reading that treats militarisation as a failing strategy compromised from within, and a Russian/Chinese framing that blames US drug demand and the southward flow of American guns.',
  editorial_summary_de = 'Mexikos Auseinandersetzung mit seinen Drogenkartellen konzentriert sich auf das Sinaloa-Kartell und das Kartell Jalisco Nueva Generación (CJNG), ausgetragen durch militarisierte Operationen, aufsehenerregende Festnahmen von Anführern und Auslieferungen an die USA sowie anhaltende Gewalt, die nicht dauerhaft zurückgegangen ist. Die Geschichte trägt eine beständige Eigentor-Dimension: Anklagen und Festnahmen, die bis in den Staat selbst reichen — ein Sinaloa-Gouverneur, dem Kartellverbindungen vorgeworfen werden, ein früherer Sicherheitschef in US-Gewahrsam — nähren eine Narco-Staat-Kritik an Kollusion, Korruption und Straflosigkeit, die selbst wohlgesonnene Medien vertreten. Die Berichterstattung teilt sich zwischen einer Sicherheitsoffensiv-Lesart, die Festnahmen als Fortschritt wertet, einer wohlwollend-kritischen Lesart, die Militarisierung als von innen kompromittierte, scheiternde Strategie sieht, und einem russisch/chinesischen Framing, das die US-Drogennachfrage und den Zustrom amerikanischer Waffen nach Süden verantwortlich macht.'
WHERE id = 'mexico_cartel_war';

-- Military/intervention pressure: add editorial summary (description set earlier).
UPDATE friction_nodes SET
  editorial_summary_en = 'This axis covers US pressure on Mexico that reaches beyond trade into security and politics. Its dominant strands in current coverage are covert and paramilitary — the deaths of CIA officers during a counter-narcotics operation in Chihuahua, US indictments of sitting Mexican officials, and repeated threats of unilateral military strikes against cartels on Mexican soil — alongside a political-interference dispute, with Mexico City accusing Washington of meddling in its internal affairs and elections. Against all of it, President Sheinbaum invokes a sovereignty red line of cooperation without subordination and constitutional non-intervention. Readings compete: US conservative voices call intervention necessary against a partner that cannot deliver; Mexican and Hispanic-American media call it a sovereignty violation; Western mainstream press covers it as scandal and diplomatic strain; and Russian and Chinese state media cast it as Monroe-Doctrine imperialism in Washington''s backyard.',
  editorial_summary_de = 'Diese Achse umfasst US-Druck auf Mexiko, der über den Handel hinaus in Sicherheit und Politik reicht. Ihre dominierenden Stränge in der aktuellen Berichterstattung sind verdeckt und paramilitärisch — der Tod von CIA-Beamten während einer Anti-Drogen-Operation in Chihuahua, US-Anklagen gegen amtierende mexikanische Amtsträger und wiederholte Drohungen mit einseitigen Militärschlägen gegen Kartelle auf mexikanischem Boden — neben einem Streit über politische Einmischung, bei dem Mexiko-Stadt Washington Einmischung in innere Angelegenheiten und Wahlen vorwirft. Dem allen setzt Präsidentin Sheinbaum eine rote Souveränitätslinie entgegen: Kooperation ohne Unterordnung und verfassungsmäßige Nichtintervention. Die Lesarten konkurrieren: US-konservative Stimmen halten die Intervention gegen einen Partner, der nicht liefern kann, für notwendig; mexikanische und hispanoamerikanische Medien nennen sie eine Souveränitätsverletzung; westliche Mainstream-Presse berichtet über Skandal und diplomatische Spannungen; und russische und chinesische Staatsmedien deuten sie als Monroe-Doktrin-Imperialismus in Washingtons Hinterhof.'
WHERE id = 'us_mexico_military_pressure';

-- Trade/border: fix German orthography in name; add editorial summary.
UPDATE friction_nodes SET
  name_de = 'Zölle, Grenze und Migration als Druckmittel',
  editorial_summary_en = 'The economic and border front of the US-Mexico relationship treats tariffs, the USMCA/T-MEC trade pact, and migration and border enforcement as interlocking instruments of leverage. Washington has wielded tariff threats — on autos, steel and aluminium — and the renegotiation or non-renewal of USMCA to extract Mexican cooperation on migration, deportation, fentanyl and border security, including National Guard deployments and a screwworm-driven livestock-trade dispute. Mexico, its economy deeply integrated with that of the United States, answers with counter-measures and diversification toward the EU and other partners. Coverage divides between a US conservative reading of legitimate, results-producing leverage; a business and wire reading centred on supply-chain and market disruption; and a Mexican reading of economic coercion that breaches the trade pact and national dignity.',
  editorial_summary_de = 'Die wirtschaftliche und grenzpolitische Front der Beziehung zwischen den USA und Mexiko behandelt Zölle, das Handelsabkommen USMCA/T-MEC sowie Migration und Grenzsicherung als ineinandergreifende Druckmittel. Washington hat Zolldrohungen — auf Autos, Stahl und Aluminium — sowie die Neuverhandlung oder Nichtverlängerung des USMCA eingesetzt, um Mexikos Kooperation bei Migration, Abschiebung, Fentanyl und Grenzsicherung zu erzwingen, einschließlich Entsendungen der Nationalgarde und eines durch den Schraubenwurm ausgelösten Streits um den Viehhandel. Mexiko, dessen Wirtschaft eng mit der der USA verflochten ist, antwortet mit Gegenmaßnahmen und Diversifizierung hin zur EU und anderen Partnern. Die Berichterstattung teilt sich zwischen einer US-konservativen Lesart legitimer, ergebnisorientierter Druckmittel; einer wirtschafts- und agenturgeprägten Lesart mit Fokus auf Lieferketten- und Marktstörungen; und einer mexikanischen Lesart wirtschaftlichen Zwangs, der das Handelsabkommen und die nationale Würde verletzt.'
WHERE id = 'us_mexico_trade_border';

COMMIT;
