-- (A) Theater-level narrative cards for australia_theater (spec 5.5), so the
--     theater page renders cards. These carry no bundle: THEATER_ROLLUP_SQL
--     (apps/frontend/lib/friction-nodes.ts) sources each card from the member
--     atomics' title_narratives where sign(atomic.stance) = sign(theater.stance)
--     AND the publisher is in the card's publishers[].
--
--     Publisher-disjointness within each sign bucket (the one hard rule -- counts
--     are uncapped over (sign, publisher), so same-sign overlap double-counts):
--       + bucket: only australia_western_consensus            -> no collision
--       - bucket: australia_china_counter (Chinese/Russian state)
--                 vs australia_alliance_scepticism (Western)   -> DISJOINT
--     The +2 and -1 cards share Western publishers, which is safe: opposite signs
--     pull different-signed atomic titles, so no title is counted twice.
--
--     The -1 Western card is not optional. aukus_capability_doubt (-1, 28 titles)
--     is the single largest narrative in the theater and is carried by Australian
--     mainstream outlets; without a negative Western-publisher card it would be
--     homeless in the roll-up.
--
-- (B) Completeness fields (spec 6): name_de, description_en/_de,
--     editorial_summary_en/_de for the theater AND all 4 atomics. All were null.
--     descriptions stay neutral and factual (no framing words, no motive
--     attribution); interpretation lives in narratives_v2 and the editorial
--     summaries describe how coverage itself divides.
SET client_encoding TO 'UTF8';

-- ========================= (A) theater narratives =========================
INSERT INTO narratives_v2
  (id, name_en, name_de, claim_en, claim_de, actor_centroids, framing_keywords,
   is_active, publishers, fn_id, display_order, stance_label_en, stance_label_de,
   stance, framing_required)
VALUES
(
  'australia_western_consensus',
  'Australia must reduce its exposure to China and deepen its alliances',
  'Australien muss seine Abhängigkeit von China verringern und seine Bündnisse vertiefen',
  'The Australian and Western mainstream reading treats Australia''s position as one requiring active management: Chinese commercial leverage over iron ore, beef and critical minerals is a vulnerability to be diversified away from; espionage and interference findings and China''s growing strike reach justify the assessments its agencies make; and the answer across the Pacific is more partnership — defence treaties with Fiji and Vanuatu, alongside AUKUS. Vocabulary: de-risk, diversify, counter, deterrence, partner of choice, screening, resilience.',
  'Die australische und westliche Mainstream-Lesart sieht Australiens Lage als aktiv zu steuern: Chinas kommerzieller Hebel über Eisenerz, Rindfleisch und kritische Rohstoffe gilt als Verwundbarkeit, von der zu diversifizieren ist; Erkenntnisse über Spionage und Einflussnahme sowie Chinas wachsende Angriffsreichweite rechtfertigen die Einschätzungen der Sicherheitsbehörden; und die Antwort im Pazifik lautet mehr Partnerschaft — Verteidigungsverträge mit Fidschi und Vanuatu sowie AUKUS.',
  ARRAY['OCEANIA-AUSTRALIA','AMERICAS-USA','ASIA-CHINA'],
  ARRAY['de-risk','diversify','counter','deterrence','partner of choice','screening','resilience','vulnerability','security pact','defence pact','assessment'],
  true,
  ARRAY['ABC News','Australian Broadcasting Corporation','ABC Pacific','Sydney Morning Herald','The Sydney Morning Herald','SMH.com.au','The Australian','The Guardian','Sky News','News24','Reuters','Associated Press','BBC World','Bloomberg','Financial Times','Nikkei Asia','Straits Times','The Straits Times','Deutsche Welle','Euronews','France 24','France 24 (EN)','Wall Street Journal','New York Times','Channel NewsAsia','The Hindu','Times of India','Janes','Defense News','Mining.com','S&P Global','OilPrice','CNBC','War on the Rocks','Chatham House','Anadolu Agency','Express Tribune','Bangkok Post','The Star','Jerusalem Post','Philippine Daily Inquirer','CSIS','Lowy Institute'],
  'australia_theater', 1,
  'Australian and Western consensus',
  'Australischer und westlicher Konsens',
  2, false
),
(
  'australia_china_counter',
  'Australia is manufacturing a threat and importing a bloc confrontation it does not need',
  'Australien konstruiert eine Bedrohung und importiert eine Blockkonfrontation, die es nicht braucht',
  'Chinese state media — with Russian outlets on AUKUS — reject the premise across every axis: the trade relationship is complementary and growing, and quota-triggered tariffs are routine administration rather than pressure; the espionage and military-threat assessments are hype, a "crafted rhetorical trap" and a grave strategic miscalculation; Pacific cooperation is requested by sovereign governments and should not be constrained by any third party; and AUKUS is Cold War bloc-building that spreads naval nuclear technology. Vocabulary: hype, fabricated, mutual benefit, Cold War mentality, third party, bloc confrontation.',
  'Chinesische Staatsmedien — bei AUKUS ergänzt durch russische — weisen die Prämisse auf allen Achsen zurück: die Handelsbeziehung sei komplementär und wachsend, quotenbedingte Zölle seien Routine statt Druck; die Einschätzungen zu Spionage und Militärbedrohung seien Panikmache, eine "rhetorische Falle" und ein schwerer strategischer Fehlschluss; die Kooperation im Pazifik erfolge auf Wunsch souveräner Regierungen und dürfe von keinem Dritten beschränkt werden; und AUKUS sei Blockbildung des Kalten Krieges, die nukleare Marinetechnik verbreite.',
  ARRAY['ASIA-CHINA','EUROPE-RUSSIA','OCEANIA-AUSTRALIA'],
  ARRAY['hype','fabricated','mutual benefit','Cold War','mentality','third party','bloc confrontation','rhetorical trap','miscalculation','win-win','complementary'],
  true,
  ARRAY['Global Times','CGTN','news.cgtn.com','China Daily','People''s Daily','Xinhua','TASS','TASS (EN)','tass.com','RT'],
  'australia_theater', 2,
  'Chinese and Russian state counter-framing',
  'Chinesische und russische staatliche Gegenrahmung',
  -2, false
),
(
  'australia_alliance_scepticism',
  'The alliance is delivering less than Australia was promised',
  'Das Bündnis liefert weniger, als Australien versprochen wurde',
  'A distinct critical reading inside the Australian and Western press questions not China policy but the alliance itself: AUKUS has been revised down to three second-hand US submarines, a capability gap opens as the Collins-class fleet is downsized, a UK inquiry found the investment had "already faltered", and senior Australian figures — including a former foreign minister — describe the pact as among the country''s worst foreign-policy decisions. The concern is reliability and cost rather than the existence of a China problem. Vocabulary: second-hand, downgrade, gap, inquiry, faltered, mess, division, explaining.',
  'Eine eigenständige kritische Lesart in der australischen und westlichen Presse stellt nicht die China-Politik infrage, sondern das Bündnis selbst: AUKUS wurde auf drei gebrauchte US-U-Boote heruntergestuft, eine Fähigkeitslücke entsteht durch die Verkleinerung der Collins-Klasse, eine britische Untersuchung sah die Investition als "bereits ins Stocken geraten", und führende australische Persönlichkeiten — darunter ein früherer Außenminister — bezeichnen den Pakt als eine der schlechtesten außenpolitischen Entscheidungen des Landes. Es geht um Zuverlässigkeit und Kosten, nicht um die Existenz eines China-Problems.',
  ARRAY['OCEANIA-AUSTRALIA','AMERICAS-USA','EUROPE-UK'],
  ARRAY['second-hand','downgrade','gap','inquiry','faltered','mess','division','explaining','worst','risk','scraps','stopgap'],
  true,
  ARRAY['ABC News','Australian Broadcasting Corporation','ABC Pacific','Sydney Morning Herald','The Sydney Morning Herald','SMH.com.au','The Australian','The Guardian','Sky News','News24','Reuters','Associated Press','BBC World','Bloomberg','Financial Times','Nikkei Asia','Straits Times','The Straits Times','Deutsche Welle','Euronews','France 24','France 24 (EN)','Wall Street Journal','New York Times','Channel NewsAsia','The Hindu','Times of India','Janes','Defense News','War on the Rocks','Chatham House','Anadolu Agency','Express Tribune','Bangkok Post','The Star','CSIS','Lowy Institute'],
  'australia_theater', 3,
  'Australian alliance scepticism',
  'Australische Bündnisskepsis',
  -1, false
)
ON CONFLICT (id) DO NOTHING;

-- ========================= (B) completeness fields =========================
UPDATE friction_nodes SET
  name_de = 'Australien als umkämpfte Mittelmacht',
  description_en = 'Australia''s strategic position between its largest trading partner and its principal security ally. Four axes run through it: the contest with China over the security and diplomatic alignment of the Pacific island states; a trade relationship in which iron ore, beef and critical minerals carry both dependence and leverage; the contested assessment of Chinese espionage and military reach; and the AUKUS submarine programme, whose revision has made alliance reliability a domestic Australian question. Coverage divides between Australian and Western outlets, Chinese state media, and — on AUKUS — Australian critics of the pact itself.',
  description_de = 'Australiens strategische Lage zwischen seinem größten Handelspartner und seinem wichtigsten Sicherheitsverbündeten. Vier Achsen durchziehen sie: der Wettstreit mit China um die sicherheitspolitische und diplomatische Ausrichtung der pazifischen Inselstaaten; eine Handelsbeziehung, in der Eisenerz, Rindfleisch und kritische Rohstoffe zugleich Abhängigkeit und Hebel bedeuten; die umstrittene Einschätzung chinesischer Spionage und militärischer Reichweite; und das AUKUS-U-Boot-Programm, dessen Überarbeitung die Zuverlässigkeit des Bündnisses zu einer innenpolitischen Frage Australiens gemacht hat. Die Berichterstattung teilt sich zwischen australischen und westlichen Medien, chinesischen Staatsmedien und — bei AUKUS — australischen Kritikern des Pakts selbst.',
  editorial_summary_en = 'Australia is the test case of a middle power that buys from one great power and shelters under another. Its coverage is not a single dyad but four distinct contests. The Pacific is the live front: within hours of Canberra signing a mutual defence treaty with Fiji, Beijing test-fired a nuclear-capable ballistic missile into the South Pacific, and Vanuatu and Solomon Islands are openly weighing which partner to take. Trade is the quiet one: the 2020-21 barley-and-wine coercion episode has largely unwound, and the live story is quota mechanics and iron-ore pricing power, running in both directions. Threat assessment is the loudest rhetorically, where ASIO, Five Eyes and the Lowy Institute meet a Chinese rebuttal machine that calls the whole thing hype. And AUKUS is the outlier: 96% of its coverage never mentions China at all, because the argument is with Washington and within Australia — over second-hand submarines, a capability gap and whether the pact was ever a good bargain. The result is a theater where the sharpest criticism of Australian policy comes not from Beijing but from Australian outlets.',
  editorial_summary_de = 'Australien ist der Prüfstein einer Mittelmacht, die von einer Großmacht kauft und sich bei einer anderen unterstellt. Seine Berichterstattung ist keine einzelne Dyade, sondern vier getrennte Auseinandersetzungen. Der Pazifik ist die aktive Front: Stunden nachdem Canberra einen Verteidigungsvertrag mit Fidschi unterzeichnet hatte, testete Peking eine atomwaffenfähige ballistische Rakete im Südpazifik, und Vanuatu und die Salomonen wägen offen ab, welchen Partner sie wählen. Der Handel ist die leise Achse: die Zwangsmaßnahmen gegen Gerste und Wein von 2020-21 sind weitgehend zurückgenommen, und die aktuelle Geschichte sind Quotenmechanik und Preismacht beim Eisenerz — in beide Richtungen. Die Bedrohungsanalyse ist rhetorisch am lautesten, wo ASIO, Five Eyes und das Lowy Institute auf einen chinesischen Widerlegungsapparat treffen, der das Ganze als Panikmache bezeichnet. Und AUKUS ist der Ausreißer: 96 Prozent dieser Berichterstattung erwähnen China überhaupt nicht, denn der Streit wird mit Washington und innerhalb Australiens geführt — über gebrauchte U-Boote, eine Fähigkeitslücke und die Frage, ob der Pakt je ein guter Handel war. So entsteht ein Schauplatz, an dem die schärfste Kritik an australischer Politik nicht aus Peking kommt, sondern aus australischen Medien.',
  updated_at = NOW()
WHERE id = 'australia_theater';

UPDATE friction_nodes SET
  name_de = 'Wettstreit um die Ausrichtung pazifischer Inselstaaten',
  description_en = 'The competition between Australia and China over the security and diplomatic alignment of the Pacific island states. Australia has signed a mutual defence treaty with Fiji and a pact with Vanuatu barring foreign military bases; Solomon Islands, under a new prime minister, is reviewing the security pact it signed with Beijing; Nauru, which switched recognition to Beijing, has directed officials to observe the one-China principle. China supplies medical teams, infrastructure and policing assistance across the region. Recognition of Taiwan and access to seabed minerals run through the same contest.',
  description_de = 'Der Wettbewerb zwischen Australien und China um die sicherheitspolitische und diplomatische Ausrichtung der pazifischen Inselstaaten. Australien hat einen Verteidigungsvertrag mit Fidschi und einen Pakt mit Vanuatu zum Verbot ausländischer Militärbasen unterzeichnet; die Salomonen überprüfen unter einem neuen Premierminister den mit Peking geschlossenen Sicherheitspakt; Nauru, das seine Anerkennung nach Peking verlagert hat, wies Bedienstete an, das Ein-China-Prinzip zu beachten. China stellt medizinische Teams, Infrastruktur und Polizeihilfe in der Region bereit. Die Anerkennung Taiwans und der Zugang zu Meeresbodenmineralien durchziehen denselben Wettstreit.',
  editorial_summary_en = 'This is the theater''s live front and its fastest-moving one. The sequence in July 2026 is the whole story compressed: Canberra signs a mutual defence treaty with Fiji, and within hours Beijing test-fires a nuclear-capable ballistic missile into the South Pacific that lands near Nauru and Tuvalu, prompting Pacific leaders to answer "don''t threaten us". Around it, Vanuatu signs a pact barring foreign military bases while warning Australia it will not be "dictated to", and a new Solomon Islands prime minister moves to review the secret pact his predecessor signed with Beijing. Coverage splits cleanly by publisher: Australian and Western outlets read the pacts as island states freely choosing transparency over Chinese basing, while Chinese state media present the same engagement as ordinary cooperation that "should not target any third party" and cast Australian reporting as hype from an exclusionary mindset. A third voice — the islands'' own insistence that they are neither camp''s to win — is audible but still thin in the corpus.',
  editorial_summary_de = 'Dies ist die aktive und am schnellsten bewegte Front des Schauplatzes. Die Abfolge im Juli 2026 verdichtet die ganze Geschichte: Canberra unterzeichnet einen Verteidigungsvertrag mit Fidschi, und binnen Stunden testet Peking eine atomwaffenfähige ballistische Rakete im Südpazifik, die nahe Nauru und Tuvalu niedergeht — worauf pazifische Staatschefs mit "Droht uns nicht" antworten. Daneben unterzeichnet Vanuatu einen Pakt zum Verbot ausländischer Militärbasen und warnt Australien zugleich, es lasse sich nichts "diktieren", und ein neuer Premierminister der Salomonen leitet die Überprüfung des von seinem Vorgänger mit Peking geschlossenen Geheimpakts ein. Die Berichterstattung trennt sich klar nach Medium: australische und westliche Medien deuten die Pakte als freie Entscheidung der Inselstaaten für Transparenz statt chinesischer Stützpunkte, während chinesische Staatsmedien dasselbe Engagement als gewöhnliche Kooperation darstellen, die "kein Drittland ins Visier nehmen" solle, und australische Berichte als Panikmache eines ausgrenzenden Denkens abtun. Eine dritte Stimme — das Beharren der Inseln, keinem Lager zu gehören — ist hörbar, im Korpus aber noch dünn.',
  updated_at = NOW()
WHERE id = 'pacific_island_contest';

UPDATE friction_nodes SET
  name_de = 'Handelsabhängigkeit und Rohstoffhebel',
  description_en = 'The commercial relationship between Australia and China, in which market access and commodity supply function as mutual leverage. China''s state-owned iron ore buyer restricted Fortescue and BHP cargoes during pricing negotiations before a settlement adopting a Chinese price index; a 55% tariff on Australian beef took effect when an agreed quota threshold was reached; Australia ordered Chinese investors to divest stakes in rare-earth projects under its foreign investment rules, and the Darwin Port lease remains disputed. The 2020-21 restrictions on barley, wine, coal and lobster have largely been unwound.',
  description_de = 'Die Handelsbeziehung zwischen Australien und China, in der Marktzugang und Rohstoffversorgung als wechselseitiger Hebel wirken. Chinas staatlicher Eisenerzkäufer beschränkte während der Preisverhandlungen Ladungen von Fortescue und BHP, bevor eine Einigung einen chinesischen Preisindex übernahm; ein Zoll von 55 Prozent auf australisches Rindfleisch trat in Kraft, als eine vereinbarte Quotenschwelle erreicht war; Australien ordnete nach seinen Regeln zur Auslandsinvestitionsprüfung den Verkauf chinesischer Anteile an Seltene-Erden-Projekten an, und die Verpachtung des Hafens von Darwin bleibt strittig. Die Beschränkungen von 2020-21 für Gerste, Wein, Kohle und Hummer sind weitgehend aufgehoben.',
  editorial_summary_en = 'The quiet axis, and the one most often described with a stale frame. The 2020-21 coercion campaign — barley, wine, coal, lobster — is essentially over: Treasury Wine posts its strongest China result in over a decade and Beijing has been issuing new beef licences. What replaced it is subtler and genuinely two-way. China''s state buyer can restrict Fortescue and BHP cargoes mid-negotiation, and a 55% beef tariff snaps in at a quota threshold; but Australia can force Chinese investors out of rare-earth projects, and its foreign minister can be found telling Beijing "we need your fuel to send you iron ore". Coverage divides on interpretation rather than fact: Australian and Western business press reads each lever as proof that concentration is a strategic vulnerability requiring diversification and screening, while Chinese state media report the same tariff as the routine operation of an agreed quota and point to record vehicle sales, solar cooperation and rising Australian opinion of China as the real trend.',
  editorial_summary_de = 'Die leise Achse — und die, die am häufigsten mit einem veralteten Deutungsrahmen beschrieben wird. Die Zwangskampagne von 2020-21 gegen Gerste, Wein, Kohle und Hummer ist im Wesentlichen beendet: Treasury Wine meldet sein stärkstes China-Ergebnis seit über einem Jahrzehnt, und Peking erteilt neue Rindfleischlizenzen. An ihre Stelle ist etwas Feineres und tatsächlich Wechselseitiges getreten. Chinas staatlicher Käufer kann mitten in Verhandlungen Ladungen von Fortescue und BHP beschränken, und ein 55-Prozent-Rindfleischzoll greift bei Erreichen einer Quotenschwelle; doch Australien kann chinesische Investoren aus Seltene-Erden-Projekten drängen, und seine Außenministerin sagt Peking, man brauche dessen Treibstoff, um Eisenerz zu liefern. Die Berichterstattung unterscheidet sich in der Deutung, nicht im Faktum: die australische und westliche Wirtschaftspresse liest jeden Hebel als Beleg dafür, dass Konzentration eine strategische Verwundbarkeit ist, die Diversifizierung und Prüfung erfordert, während chinesische Staatsmedien denselben Zoll als routinemäßige Anwendung einer vereinbarten Quote darstellen und Rekordabsätze bei Fahrzeugen, Solarkooperation und eine steigende Meinung über China als den eigentlichen Trend anführen.',
  updated_at = NOW()
WHERE id = 'australia_china_trade_leverage';

UPDATE friction_nodes SET
  name_de = 'AUKUS-U-Boot-Programm und Bündniszuverlässigkeit',
  description_en = 'The AUKUS submarine programme and the Australian debate over what it delivers. Under a revised arrangement Australia is to receive three second-hand US Virginia-class submarines rather than newly built boats; the Collins-class fleet is being downsized and has entered a life-of-type extension; a UK inquiry reported shortcomings in the programme, and an Australian former minister crowd-funded a separate inquiry. The US Navy has established Naval Support Activity Stirling in Western Australia for rotational US and UK submarines, and Australia has pledged $2.7bn towards its own shipyard. The dispute runs between Australia and its partners and within Australian politics rather than with China.',
  description_de = 'Das AUKUS-U-Boot-Programm und die australische Debatte über seinen Ertrag. Nach einer überarbeiteten Vereinbarung soll Australien drei gebrauchte US-U-Boote der Virginia-Klasse statt neu gebauter Boote erhalten; die Collins-Klasse wird verkleinert und hat eine Laufzeitverlängerung begonnen; eine britische Untersuchung stellte Mängel des Programms fest, und ein früherer australischer Minister finanzierte per Crowdfunding eine eigene Untersuchung. Die US-Marine hat in Westaustralien die Naval Support Activity Stirling für rotierende US- und britische U-Boote eingerichtet, und Australien hat 2,7 Milliarden für eine eigene Werft zugesagt. Der Streit verläuft zwischen Australien und seinen Partnern sowie innerhalb der australischen Politik, nicht mit China.',
  editorial_summary_en = 'AUKUS is the theater''s outlier, and the reason this theater is not a simple Australia-China dyad: only 3 of 70 AUKUS headlines mention China at all. The pact was built to answer Beijing, but the argument in the coverage is with Washington and within Australia. The revision to three second-hand Virginia-class boats reframed the entire debate — "the impact of Australia only buying second-hand submarines", "Australia scraps new Virginia-class submarines in AUKUS shake-up" — while the Collins-class fleet shrinks into a "high-risk" life extension and the Coalition floats stealth bombers as a stopgap. This is an own-goal topic in the strict sense: the harshest critics are the Australian mainstream itself, from a former foreign minister calling it among the country''s worst foreign-policy decisions to an ex-minister crowd-funding his own inquiry. Publisher alignment cannot separate stance here, because the same outlets carry both the defence of the pact and its demolition; only the framing does. Chinese and Russian state media denounce it as bloc confrontation and proliferation, but they are barely present in the coverage.',
  editorial_summary_de = 'AUKUS ist der Ausreißer des Schauplatzes und der Grund, warum dieser keine einfache Australien-China-Dyade ist: nur 3 von 70 AUKUS-Schlagzeilen erwähnen China überhaupt. Der Pakt wurde als Antwort auf Peking geschlossen, doch der Streit in der Berichterstattung wird mit Washington und innerhalb Australiens geführt. Die Umstellung auf drei gebrauchte Boote der Virginia-Klasse hat die ganze Debatte neu gerahmt — "die Folgen davon, dass Australien nur gebrauchte U-Boote kauft", "Australien streicht neue Virginia-Boote in AUKUS-Umbau" — während die Collins-Klasse in eine "hochriskante" Laufzeitverlängerung schrumpft und die Opposition Tarnkappenbomber als Übergangslösung ins Spiel bringt. Dies ist ein Eigentor-Thema im strengen Sinne: die schärfsten Kritiker sind die australischen Leitmedien selbst — von einem früheren Außenminister, der den Pakt zu den schlechtesten außenpolitischen Entscheidungen des Landes zählt, bis zu einem Ex-Minister, der seine eigene Untersuchung per Crowdfunding finanziert. Die Medienzugehörigkeit kann die Haltung hier nicht trennen, weil dieselben Medien Verteidigung und Demontage des Pakts tragen; nur die Rahmung tut es. Chinesische und russische Staatsmedien verurteilen ihn als Blockkonfrontation und Proliferation, sind in der Berichterstattung aber kaum präsent.',
  updated_at = NOW()
WHERE id = 'aukus_alliance_reliability';

UPDATE friction_nodes SET
  name_de = 'Spionagevorwürfe und Einschätzung der chinesischen Bedrohung',
  description_en = 'The contested assessment of Chinese espionage and military reach in relation to Australia. Australian authorities have charged Chinese nationals with foreign interference in Canberra, a jury found an Australian expatriate had acted as a Chinese intelligence asset, and the Five Eyes alliance warned that Chinese services recruit targets through fake job advertisements on professional networks. The Lowy Institute assessed China''s capacity to strike targets in Australia as growing, and China conducted a nuclear-capable ballistic missile test into the South Pacific. Chinese officials and state media reject these assessments.',
  description_de = 'Die umstrittene Einschätzung chinesischer Spionage und militärischer Reichweite in Bezug auf Australien. Australische Behörden haben chinesische Staatsbürger wegen ausländischer Einflussnahme in Canberra angeklagt, ein Geschworenengericht befand, ein australischer Auswanderer habe als chinesischer Nachrichtendienstzuträger gehandelt, und das Five-Eyes-Bündnis warnte, chinesische Dienste würben Zielpersonen über gefälschte Stellenanzeigen in beruflichen Netzwerken an. Das Lowy Institute schätzte Chinas Fähigkeit zu Angriffen auf Ziele in Australien als wachsend ein, und China führte einen atomwaffenfähigen ballistischen Raketentest im Südpazifik durch. Chinesische Amtsträger und Staatsmedien weisen diese Einschätzungen zurück.',
  editorial_summary_en = 'This axis is a contest over whether the threat is real, and it is unusually symmetrical: nearly every Australian claim has a same-week Chinese rebuttal. ASIO spars publicly with Beijing over foreign interference; two more Chinese nationals are charged over information-gathering in Canberra; a jury finds an Australian expatriate acted as a Chinese spy asset; Five Eyes warns that Chinese officers pose as recruiters on job platforms; the Lowy Institute concludes China''s ability to strike targets in Australia is "real and growing"; and a nuclear-capable missile lands in the South Pacific. Against each, Chinese state media return a mirror line — the espionage warning is a "crafted rhetorical trap" and "highly ironic" from an alliance built on surveillance, and the think-tank threat assessment is a grave strategic miscalculation. The two coalitions are fully disjoint, so publisher alone tells the stances apart; what the corpus cannot settle is which reading a reader should believe.',
  editorial_summary_de = 'Diese Achse ist ein Streit darüber, ob die Bedrohung real ist, und sie verläuft ungewöhnlich symmetrisch: fast jede australische Behauptung findet in derselben Woche eine chinesische Erwiderung. Der Inlandsgeheimdienst ASIO streitet öffentlich mit Peking über ausländische Einflussnahme; zwei weitere chinesische Staatsbürger werden wegen Informationsbeschaffung in Canberra angeklagt; ein Geschworenengericht befindet, ein australischer Auswanderer habe als chinesischer Spionagehelfer gehandelt; Five Eyes warnt, chinesische Offiziere gäben sich auf Jobplattformen als Personalvermittler aus; das Lowy Institute schließt, Chinas Fähigkeit zu Angriffen auf Ziele in Australien sei "real und wachsend"; und eine atomwaffenfähige Rakete geht im Südpazifik nieder. Dagegen setzen chinesische Staatsmedien jeweils eine Spiegelaussage — die Spionagewarnung sei eine "rhetorische Falle" und "höchst ironisch" von einem auf Überwachung gebauten Bündnis, und die Bedrohungsanalyse der Denkfabrik ein schwerer strategischer Fehlschluss. Die beiden Lager sind vollständig getrennt, sodass allein das Medium die Haltungen unterscheidet; was der Korpus nicht klären kann, ist, welcher Lesart zu glauben ist.',
  updated_at = NOW()
WHERE id = 'china_threat_assessment';
