-- Korea theater: bilingual completeness fields (spec section 6) + display order.
--
-- Prose rules: factual, neutral, evergreen. No motive attribution, no
-- temporality, no framing words in our own voice. Where coverage is contested,
-- that contest is stated as an observable fact about the coverage -- the
-- framings themselves live in narratives_v2, not here.

BEGIN;

-- Normalise display order: the two new atomics landed on 3/4 while the
-- inherited ones sat at 57/58/61.
UPDATE friction_nodes SET display_order = 1 WHERE id = 'north_korea_missile_program';
UPDATE friction_nodes SET display_order = 2 WHERE id = 'korea_peninsula_deterrence';
UPDATE friction_nodes SET display_order = 3 WHERE id = 'north_korea_russia_alignment';
UPDATE friction_nodes SET display_order = 4 WHERE id = 'north_korea_china_patronage';
UPDATE friction_nodes SET display_order = 5 WHERE id = 'inter_korean_relations';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'Konfrontation auf der koreanischen Halbinsel',
description_en = 'The unresolved confrontation on the Korean Peninsula, where the Korean War was halted by an armistice rather than concluded by a peace treaty. Five axes run through it: North Korea''s nuclear and ballistic missile programme and the sanctions architecture built around it; the United States-South Korea alliance, with its exercises, command arrangements and extended-deterrence commitments; North Korea''s military alignment with Russia, including troop deployments to the war in Ukraine; China''s economic and diplomatic patronage of Pyongyang; and the inter-Korean relationship itself, which North Korea has redefined constitutionally as a relationship between separate states. Coverage divides by bloc: Western, South Korean and Japanese outlets report the Northern programme as a threat requiring containment, while Russian and Chinese state media present Pyongyang''s arrangements with Moscow and Beijing as lawful cooperation between sovereign states.',
description_de = 'Die ungelöste Konfrontation auf der koreanischen Halbinsel, wo der Koreakrieg durch einen Waffenstillstand unterbrochen und nicht durch einen Friedensvertrag beendet wurde. Fünf Achsen durchziehen sie: Nordkoreas Nuklear- und Raketenprogramm und die darum errichtete Sanktionsarchitektur; das Bündnis zwischen den Vereinigten Staaten und Südkorea mit seinen Übungen, Kommandostrukturen und Zusagen zur erweiterten Abschreckung; Nordkoreas militärische Ausrichtung auf Russland einschließlich Truppenentsendungen in den Krieg in der Ukraine; Chinas wirtschaftliche und diplomatische Patronage über Pjöngjang; und die innerkoreanische Beziehung selbst, die Nordkorea verfassungsrechtlich als Verhältnis getrennter Staaten neu definiert hat. Die Berichterstattung teilt sich nach Blöcken: Westliche, südkoreanische und japanische Medien berichten über das nordkoreanische Programm als Bedrohung, die Eindämmung erfordert, während russische und chinesische Staatsmedien Pjöngjangs Arrangements mit Moskau und Peking als rechtmäßige Zusammenarbeit souveräner Staaten darstellen.',
editorial_summary_en = 'The Korean Peninsula remains divided along an armistice line that has held without a peace treaty since 1953. The dominant axis is North Korea''s nuclear and ballistic missile programme: Pyongyang has declared itself a nuclear state, describes that status as irreversible, and continues launch testing and enrichment expansion against a United Nations sanctions regime that has not reversed it. Two external relationships now shape what pressure can achieve. Russia and North Korea have built a treaty-based military partnership under which North Korean troops have fought in Kursk and North Korean munitions have supplied the war in Ukraine, with the return flow -- cash, and possibly military and space technology -- the central question for observers. China has restored its own links to Pyongyang through a state visit, resumed flights and rail, and trade that sustains the North Korean economy. Facing them, the United States-South Korea alliance is simultaneously reaffirming extended deterrence and renegotiating its own terms: the transfer of wartime operational control, defence cost-sharing, and Seoul''s push for a more self-reliant defence including nuclear-powered submarines. The inter-Korean track itself has narrowed, with Seoul offering engagement while North Korea has removed reunification from its constitution and defined the South as a separate state.',
editorial_summary_de = 'Die koreanische Halbinsel bleibt entlang einer Waffenstillstandslinie geteilt, die seit 1953 ohne Friedensvertrag hält. Die dominierende Achse ist Nordkoreas Nuklear- und Raketenprogramm: Pjöngjang hat sich zum Atomstaat erklärt, bezeichnet diesen Status als unumkehrbar und setzt Starttests und den Ausbau der Anreicherung gegen ein Sanktionsregime der Vereinten Nationen fort, das dies nicht rückgängig gemacht hat. Zwei äußere Beziehungen bestimmen inzwischen, was Druck bewirken kann. Russland und Nordkorea haben eine vertraglich geregelte Militärpartnerschaft aufgebaut, in deren Rahmen nordkoreanische Truppen bei Kursk gekämpft und nordkoreanische Munition den Krieg in der Ukraine beliefert haben; der Rückfluss -- Geld und möglicherweise Militär- und Raumfahrttechnologie -- ist die zentrale Frage für Beobachter. China hat seine eigenen Verbindungen nach Pjöngjang durch einen Staatsbesuch, wieder aufgenommene Flüge und Bahnverbindungen sowie Handel wiederhergestellt, der die nordkoreanische Wirtschaft trägt. Ihnen gegenüber bekräftigt das Bündnis zwischen den Vereinigten Staaten und Südkorea die erweiterte Abschreckung und verhandelt zugleich seine eigenen Bedingungen neu: die Übertragung der Operationskontrolle im Kriegsfall, die Teilung der Verteidigungskosten und Seouls Streben nach eigenständigerer Verteidigung einschließlich atomgetriebener U-Boote. Der innerkoreanische Kanal selbst hat sich verengt: Seoul bietet Annäherung an, während Nordkorea die Wiedervereinigung aus seiner Verfassung entfernt und den Süden als eigenen Staat definiert hat.',
updated_at = NOW()
WHERE id = 'korea_theater';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'Nordkoreas ballistisches und nukleares Raketenprogramm',
description_en = 'North Korea''s nuclear weapons and ballistic missile programme, and the international pressure regime built against it. It covers warhead and fissile-material production at sites such as Yongbyon and Kangson, the test infrastructure at Punggye-ri and Sohae, the Hwasong and Pukguksong families of ballistic and submarine-launched missiles, hypersonic and guided systems, and the launch testing that punctuates the calendar. It also covers the response: United Nations Security Council sanctions and their enforcement, denuclearisation diplomacy, and allied detection and interception. Pyongyang has written its nuclear status into law and rejects denuclearisation as a premise for talks.',
description_de = 'Nordkoreas Nuklearwaffen- und Raketenprogramm sowie das dagegen errichtete internationale Druckregime. Erfasst werden die Produktion von Sprengköpfen und Spaltmaterial an Standorten wie Yongbyon und Kangson, die Testinfrastruktur in Punggye-ri und Sohae, die Raketenfamilien Hwasong und Pukguksong einschließlich U-Boot-gestützter Systeme, Hyperschall- und gelenkte Systeme sowie die Starttests, die den Kalender prägen. Erfasst wird ebenso die Reaktion: Sanktionen des Sicherheitsrats der Vereinten Nationen und ihre Durchsetzung, Denuklearisierungsdiplomatie sowie Aufklärung und Abfangfähigkeit der Verbündeten. Pjöngjang hat seinen Atomstatus gesetzlich verankert und lehnt Denuklearisierung als Voraussetzung für Gespräche ab.',
editorial_summary_en = 'This is the axis that sets the terms for everything else on the peninsula. North Korea has declared itself a nuclear state, written that status into its constitution and law, and says it is irreversible; assessments track expanding uranium-enrichment capacity, growing warhead estimates, and progress on intercontinental and submarine-launched delivery. Launch testing is frequent and often timed against allied exercises or regional events. The pressure architecture built to reverse the programme -- Security Council resolutions, sanctions enforcement, interdiction and denuclearisation diplomacy -- has not achieved that reversal, and its enforcement has weakened as Russia and China have moved closer to Pyongyang. Reporting divides sharply: Western, South Korean and Japanese outlets treat the programme as an expanding danger to be contained, while Russian and Chinese state press, when it takes a position at all, relays Pyongyang''s claim that the arsenal is a lawful sovereign deterrent and that containment has failed. Most of that bloc''s coverage is neutral reporting of launches rather than advocacy.',
editorial_summary_de = 'Dies ist die Achse, die die Bedingungen für alles Übrige auf der Halbinsel setzt. Nordkorea hat sich zum Atomstaat erklärt, diesen Status in Verfassung und Gesetz verankert und bezeichnet ihn als unumkehrbar; Einschätzungen verfolgen wachsende Urananreicherungskapazitäten, steigende Sprengkopfschätzungen und Fortschritte bei interkontinentalen und U-Boot-gestützten Trägersystemen. Starttests erfolgen häufig und oft mit zeitlichem Bezug zu Übungen der Verbündeten oder regionalen Ereignissen. Die Druckarchitektur, die das Programm umkehren sollte -- Resolutionen des Sicherheitsrats, Sanktionsdurchsetzung, Unterbindung und Denuklearisierungsdiplomatie -- hat diese Umkehr nicht erreicht, und ihre Durchsetzung ist schwächer geworden, seit Russland und China Pjöngjang näher gerückt sind. Die Berichterstattung teilt sich deutlich: Westliche, südkoreanische und japanische Medien behandeln das Programm als wachsende Gefahr, die eingedämmt werden muss, während die russische und chinesische Staatspresse, sofern sie überhaupt Position bezieht, Pjöngjangs Anspruch wiedergibt, das Arsenal sei ein rechtmäßiges souveränes Abschreckungsmittel und die Eindämmung gescheitert. Der Großteil dieser Berichterstattung besteht aus neutralen Meldungen über Raketenstarts, nicht aus Fürsprache.',
updated_at = NOW()
WHERE id = 'north_korea_missile_program';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'US-südkoreanisches Bündnis und Abschreckung auf der Halbinsel',
description_en = 'The United States-South Korea alliance as a military instrument and as a relationship under renegotiation. It covers the combined force posture -- United States Forces Korea, the Combined Forces Command, basing at Camp Humphreys, Osan and Kunsan, and the THAAD battery at Seongju -- and the exercise cycle, including Freedom Shield and Ulchi. It also covers the terms of the alliance itself: the conditions-based transfer of wartime operational control, defence cost-sharing, extended deterrence and the Nuclear Consultative Group, and South Korea''s programme for nuclear-powered submarines and a more self-reliant defence.',
description_de = 'Das Bündnis zwischen den Vereinigten Staaten und Südkorea als militärisches Instrument und als Beziehung, deren Bedingungen neu verhandelt werden. Erfasst werden die gemeinsame Streitkräfteaufstellung -- die US-Streitkräfte in Korea, das kombinierte Oberkommando, die Stationierung in Camp Humphreys, Osan und Kunsan sowie die THAAD-Batterie in Seongju -- und der Übungszyklus einschließlich Freedom Shield und Ulchi. Erfasst werden ebenso die Bündnisbedingungen selbst: die bedingungsgebundene Übertragung der Operationskontrolle im Kriegsfall, die Teilung der Verteidigungskosten, die erweiterte Abschreckung und die Nukleare Konsultativgruppe sowie Südkoreas Programm für atomgetriebene U-Boote und eine eigenständigere Verteidigung.',
editorial_summary_en = 'The alliance is doing two things at once. As a military instrument it sustains the deterrence posture against the North: a standing US troop presence, a combined command, an annual exercise cycle that Pyongyang answers with launches, and extended-deterrence commitments reaffirmed through the Nuclear Consultative Group. As a relationship it is being renegotiated. Seoul is working toward the conditions-based transfer of wartime operational control, pressing for indigenous nuclear-powered submarines, and framing a more self-reliant defence as complementary to rather than a substitute for the alliance; defence cost-sharing and episodes of friction between the two capitals recur. Coverage of the first strand is broadly supportive across Western, South Korean and Japanese outlets. Coverage of the second is critical from inside the same coalition, which is why the two are separated here rather than read off publisher alignment. Chinese state media run a third line: that Washington treats South Korea as an instrument for containing China. Russian and Chinese reporting of the exercises themselves is otherwise neutral.',
editorial_summary_de = 'Das Bündnis leistet zweierlei zugleich. Als militärisches Instrument trägt es das Abschreckungsdispositiv gegenüber dem Norden: eine dauerhafte US-Truppenpräsenz, ein kombiniertes Oberkommando, einen jährlichen Übungszyklus, den Pjöngjang mit Raketenstarts beantwortet, und Zusagen zur erweiterten Abschreckung, die über die Nukleare Konsultativgruppe bekräftigt werden. Als Beziehung wird es neu verhandelt. Seoul arbeitet auf die bedingungsgebundene Übertragung der Operationskontrolle im Kriegsfall hin, drängt auf eigene atomgetriebene U-Boote und stellt eine eigenständigere Verteidigung als Ergänzung und nicht als Ersatz für das Bündnis dar; die Teilung der Verteidigungskosten und Reibungen zwischen beiden Hauptstädten kehren wieder. Die Berichterstattung über den ersten Strang ist in westlichen, südkoreanischen und japanischen Medien weitgehend zustimmend. Die über den zweiten ist kritisch aus derselben Koalition heraus, weshalb beide hier getrennt und nicht über die Medienzugehörigkeit erschlossen werden. Chinesische Staatsmedien fahren eine dritte Linie: Washington behandle Südkorea als Instrument zur Eindämmung Chinas. Die russische und chinesische Berichterstattung über die Übungen selbst ist ansonsten neutral.',
updated_at = NOW()
WHERE id = 'korea_peninsula_deterrence';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'Nordkoreas Ausrichtung auf Russland',
description_en = 'The military and political alignment between North Korea and Russia, extended through Belarus. It covers the treaty-based partnership and its implementation: North Korean troop deployments to Russian territory including Kursk, munitions and missile transfers supporting the war in Ukraine, ministerial, parliamentary and head-of-state visits in both directions, cross-border infrastructure such as the Khasan-Tumangang crossing and a road bridge, and the compensation flowing back to Pyongyang. Estimates of that return flow include payments and the transfer of military and space technology. North Korean casualties and prisoners of war taken in Ukraine are part of the same axis.',
description_de = 'Die militärische und politische Ausrichtung zwischen Nordkorea und Russland, erweitert um Belarus. Erfasst werden die vertraglich geregelte Partnerschaft und ihre Umsetzung: Entsendungen nordkoreanischer Truppen auf russisches Gebiet einschließlich Kursk, Lieferungen von Munition und Raketen zur Unterstützung des Krieges in der Ukraine, Besuche von Ministern, Parlamentariern und Staatsoberhäuptern in beide Richtungen, grenzüberschreitende Infrastruktur wie der Übergang Chasan-Tumangang und eine Straßenbrücke sowie die Gegenleistungen an Pjöngjang. Schätzungen dieses Rückflusses umfassen Zahlungen sowie den Transfer von Militär- und Raumfahrttechnologie. Nordkoreanische Gefallene und in der Ukraine gemachte Kriegsgefangene gehören zur selben Achse.',
editorial_summary_en = 'North Korea has become a participant in a European war, and the relationship that made it one is the newest structural change on the peninsula. Under a treaty-based partnership, North Korean soldiers have fought on Russian territory in Kursk and North Korean munitions and missiles have supplied the war in Ukraine; Pyongyang has publicly honoured the dead with memorials and housing for their families, and its leadership has described ties with Moscow as a top priority. Belarus has joined the axis at the level of state visits. What Russia pays in return is the question that connects this node to the weapons programme: estimates cover cash running to billions, and suspicion centres on military and space technology that would accelerate North Korean capabilities. Russian and Belarusian state press present the arrangement as lawful cooperation between sovereign states under the same sanctions, with North Korean soldiers as heroes of a liberation. Western, South Korean, Japanese and Ukrainian outlets read it as a transaction -- troops and shells for cash and technology -- and foreground its costs, including casualty figures, prisoners of war, and a policy of self-destruction to avoid capture that Kim has praised publicly.',
editorial_summary_de = 'Nordkorea ist zur Kriegspartei in einem europäischen Krieg geworden, und die Beziehung, die dazu geführt hat, ist die jüngste strukturelle Veränderung auf der Halbinsel. Im Rahmen einer vertraglich geregelten Partnerschaft haben nordkoreanische Soldaten auf russischem Gebiet bei Kursk gekämpft, und nordkoreanische Munition und Raketen haben den Krieg in der Ukraine beliefert; Pjöngjang hat die Gefallenen öffentlich mit Denkmälern und Wohnungen für ihre Familien geehrt, und seine Führung bezeichnet die Beziehungen zu Moskau als oberste Priorität. Belarus ist der Achse auf der Ebene von Staatsbesuchen beigetreten. Was Russland im Gegenzug zahlt, ist die Frage, die diesen Knoten mit dem Waffenprogramm verbindet: Schätzungen reichen bis in den Milliardenbereich, und der Verdacht richtet sich auf Militär- und Raumfahrttechnologie, die nordkoreanische Fähigkeiten beschleunigen würde. Die russische und belarussische Staatspresse stellt das Arrangement als rechtmäßige Zusammenarbeit souveräner Staaten unter denselben Sanktionen dar, mit nordkoreanischen Soldaten als Helden einer Befreiung. Westliche, südkoreanische, japanische und ukrainische Medien lesen es als Geschäft -- Truppen und Granaten gegen Geld und Technologie -- und stellen die Kosten in den Vordergrund, darunter Verlustzahlen, Kriegsgefangene und eine von Kim öffentlich gelobte Praxis der Selbstsprengung zur Vermeidung der Gefangennahme.',
updated_at = NOW()
WHERE id = 'north_korea_russia_alignment';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'Chinas Patronage über Nordkorea',
description_en = 'China''s economic and diplomatic relationship with North Korea, and its effect on the sanctions regime. It covers head-of-state and foreign-ministry visits, the cross-border economy through Dandong, Sinuiju and the Yalu and Tumen crossings, restored transport links including Beijing-Pyongyang flights and rail service, the treaty of friendship and its commemorative infrastructure, and the trade that supplies the North Korean economy. China is a permanent member of the United Nations Security Council and a party to the sanctions resolutions on North Korea; enforcement of those resolutions at the Chinese border is a recurring subject.',
description_de = 'Chinas wirtschaftliche und diplomatische Beziehung zu Nordkorea und deren Wirkung auf das Sanktionsregime. Erfasst werden Besuche auf Ebene der Staatsoberhäupter und Außenministerien, die grenzüberschreitende Wirtschaft über Dandong, Sinuiju und die Übergänge am Yalu und Tumen, wiederhergestellte Verkehrsverbindungen einschließlich Flügen und Bahnverkehr zwischen Peking und Pjöngjang, der Freundschaftsvertrag und seine Gedenkinfrastruktur sowie der Handel, der die nordkoreanische Wirtschaft versorgt. China ist ständiges Mitglied des Sicherheitsrats der Vereinten Nationen und Vertragspartei der Sanktionsresolutionen zu Nordkorea; die Durchsetzung dieser Resolutionen an der chinesischen Grenze ist ein wiederkehrendes Thema.',
editorial_summary_en = 'China is the variable that determines how much the pressure regime can actually deliver. It is a permanent member of the Security Council and a signatory to the sanctions resolutions on North Korea, and it is simultaneously the North Korean economy''s principal external support: trade across the Yalu, restored Beijing-Pyongyang flights and rail service after years of suspension, and a re-engagement at the highest level through a state visit and a foreign-ministry mission. The nuclear question was not visibly advanced by that re-engagement. Chinese state media present it as a traditional friendship entering a new era and as a contribution to regional stability. Western, South Korean and Japanese outlets that take a position read the same links as the decisive gap in enforcement -- a lifeline that keeps the economy alive and rebuilds Chinese leverage over Pyongyang as a card in Beijing''s own competition with Washington. Much of the non-Chinese coverage, however, simply reports the visits and the reopened links without arguing either case.',
editorial_summary_de = 'China ist die Variable, die bestimmt, wie viel das Druckregime tatsächlich bewirken kann. Es ist ständiges Mitglied des Sicherheitsrats und Unterzeichner der Sanktionsresolutionen zu Nordkorea und zugleich die wichtigste äußere Stütze der nordkoreanischen Wirtschaft: Handel über den Yalu, wieder aufgenommene Flüge und Bahnverbindungen zwischen Peking und Pjöngjang nach Jahren der Aussetzung und eine Wiederannäherung auf höchster Ebene durch einen Staatsbesuch und eine Mission des Außenministeriums. Die Nuklearfrage wurde durch diese Wiederannäherung sichtbar nicht vorangebracht. Chinesische Staatsmedien stellen sie als traditionelle Freundschaft dar, die in eine neue Ära eintritt, und als Beitrag zur regionalen Stabilität. Westliche, südkoreanische und japanische Medien, die Position beziehen, lesen dieselben Verbindungen als entscheidende Lücke in der Durchsetzung -- eine Lebensader, die die Wirtschaft am Leben hält und Pekings Einfluss auf Pjöngjang als Karte im eigenen Wettbewerb mit Washington wiederaufbaut. Ein großer Teil der nicht-chinesischen Berichterstattung meldet die Besuche und die wiedereröffneten Verbindungen jedoch schlicht, ohne für eine der beiden Lesarten zu argumentieren.',
updated_at = NOW()
WHERE id = 'north_korea_china_patronage';

-- ---------------------------------------------------------------------------
UPDATE friction_nodes SET
name_de = 'Innerkoreanische Beziehungen',
description_en = 'The relationship between the two Korean states, conducted across the Demilitarized Zone and the Northern Limit Line. It covers the engagement instruments -- the 2018 inter-Korean military agreement and its no-fly zone, liaison and hotline channels, family reunions, the Kaesong industrial zone and Kumgang tourism -- and the incidents that interrupt them, including drone incursions, loudspeaker and leaflet campaigns, and disputes over jurisdiction along the armistice line. It also covers the constitutional question: North Korea has removed references to reunification from its constitution and defines South Korea as a separate state, while Seoul''s unification policy has moved toward a two-state framing of peaceful coexistence.',
description_de = 'Das Verhältnis zwischen den beiden koreanischen Staaten, geführt über die entmilitarisierte Zone und die nördliche Grenzlinie. Erfasst werden die Instrumente der Annäherung -- das innerkoreanische Militärabkommen von 2018 samt Flugverbotszone, Verbindungsbüros und Direktleitungen, Familienzusammenführungen, die Industriezone Kaesong und der Tourismus am Kumgang -- sowie die Zwischenfälle, die sie unterbrechen, darunter Drohneneinflüge, Lautsprecher- und Flugblattaktionen und Streit über die Zuständigkeit entlang der Waffenstillstandslinie. Erfasst wird ebenso die Verfassungsfrage: Nordkorea hat Verweise auf die Wiedervereinigung aus seiner Verfassung entfernt und definiert Südkorea als eigenen Staat, während Seouls Wiedervereinigungspolitik sich einer Zwei-Staaten-Rahmung friedlicher Koexistenz zugewandt hat.',
editorial_summary_en = 'The inter-Korean relationship is being redefined rather than negotiated. North Korea has removed reunification from its constitution, defined its territory against a South it describes as a separate and hostile state, and publicly dismissed Seoul''s diplomatic overtures. Seoul has moved in a parallel direction on paper -- its unification white paper now frames the goal as peaceful two-state coexistence -- while pursuing engagement in practice: restoring the 2018 military agreement and its no-fly zone, easing civilian access along the border, expressing regret over drone incursions into the North, and reading signals such as statements from Kim Yo-jong or a less hostile constitutional revision as possible openings. The result is an asymmetry in which one side maintains an engagement track that the other has formally closed. Both readings of that asymmetry -- that engagement can still reopen the track, and that Pyongyang has ended it structurally -- appear in the same South Korean and Western outlets, which is why they are distinguished here by their framing rather than by publisher.',
editorial_summary_de = 'Das innerkoreanische Verhältnis wird eher neu definiert als verhandelt. Nordkorea hat die Wiedervereinigung aus seiner Verfassung entfernt, sein Staatsgebiet gegen einen Süden abgegrenzt, den es als eigenen und feindlichen Staat bezeichnet, und Gesprächsangebote aus Seoul öffentlich zurückgewiesen. Seoul hat sich auf dem Papier in eine parallele Richtung bewegt -- sein Weißbuch zur Wiedervereinigung fasst das Ziel nun als friedliche Koexistenz zweier Staaten -- verfolgt in der Praxis jedoch Annäherung: Wiederherstellung des Militärabkommens von 2018 samt Flugverbotszone, Erleichterung des zivilen Zugangs entlang der Grenze, Bedauern über Drohneneinflüge in den Norden und die Deutung von Signalen wie Äußerungen von Kim Yo-jong oder einer weniger feindseligen Verfassungsrevision als mögliche Öffnungen. Das Ergebnis ist eine Asymmetrie, in der eine Seite einen Annäherungskurs aufrechterhält, den die andere förmlich geschlossen hat. Beide Lesarten dieser Asymmetrie -- dass Annäherung den Kanal wieder öffnen kann und dass Pjöngjang ihn strukturell beendet hat -- erscheinen in denselben südkoreanischen und westlichen Medien, weshalb sie hier über ihre Rahmung und nicht über das Medium unterschieden werden.',
updated_at = NOW()
WHERE id = 'inter_korean_relations';

COMMIT;
