-- Venezuela theater: completeness fields (§6, 2026-07-18).
--
-- name_de / description_en|_de / editorial_summary_en|_de on the theater AND all
-- four atomics. Text is NEUTRAL, fact-based and evergreen per the
-- feedback_fn_descriptions_neutral rule -- no motive attribution, no stance
-- framing (that lives only in narratives_v2), no dated specifics.
--
-- Two fixes to pre-existing text:
--   * German rewritten in native orthography (was ASCII: Uebergang -> Übergang,
--     Oel -> Öl, Legitimitaet -> Legitimität).
--   * "Operation Absolute Resolve" REMOVED from us_venezuela_relations -- it
--     returns 0 hits in 365d of corpus. Stale training-data invention.

BEGIN;

-- ------------------------------- THEATER -------------------------------
UPDATE friction_nodes SET
  description_en = 'Venezuela''s contested trajectory after the US operation that removed Nicolás Maduro: the mandate of the interim administration, the reopening of the oil sector, the legality of the intervention, and the unresolved Essequibo claim against Guyana.',
  description_de = 'Venezuelas umstrittener Weg nach der US-Operation, die Nicolás Maduro absetzte: das Mandat der Übergangsverwaltung, die Wiederöffnung des Ölsektors, die Rechtmäßigkeit der Intervention und der ungelöste Essequibo-Anspruch gegenüber Guyana.',
  editorial_summary_en = 'Venezuela concentrates several distinct disputes in a single country. A US military operation detained the sitting president and a negotiated interim administration took office, leaving open questions of mandate, election timing and the opposition''s role. In parallel, sanctions relief reopened the world''s largest proven crude reserves to international operators, drawing the majors back and lifting exports to multi-year highs. The intervention itself remains legally contested, including over war-powers authority and strikes on vessels at sea. Separately, Venezuela''s long-standing claim to the Essequibo region continues before the International Court of Justice. Coverage divides sharply between Western and Latin American outlets on one side and Russian, Chinese and Iranian state media on the other.',
  editorial_summary_de = 'Venezuela bündelt mehrere unterschiedliche Konflikte in einem Land. Eine US-Militäroperation nahm den amtierenden Präsidenten fest, und eine ausgehandelte Übergangsverwaltung trat an -- offen bleiben Fragen des Mandats, des Wahltermins und der Rolle der Opposition. Parallel öffnete die Lockerung der Sanktionen die größten nachgewiesenen Rohölreserven der Welt wieder für internationale Betreiber, die Konzerne kehrten zurück und die Exporte erreichten Mehrjahreshöchststände. Die Intervention selbst bleibt rechtlich umstritten, auch hinsichtlich der Kriegsvollmachten und der Angriffe auf Schiffe. Davon getrennt liegt Venezuelas langjähriger Anspruch auf die Region Essequibo weiterhin beim Internationalen Gerichtshof. Die Berichterstattung teilt sich deutlich zwischen westlichen und lateinamerikanischen Medien einerseits und russischen, chinesischen und iranischen Staatsmedien andererseits.'
WHERE id = 'venezuela_theater';

-- --------------------------- A. OIL RESTART ----------------------------
UPDATE friction_nodes SET
  description_en = 'The reopening of Venezuela''s oil sector: sanctions relief and licensing, the return of international operators, recovery in production and exports, hydrocarbon-law and contract reform, and sovereign debt restructuring.',
  description_de = 'Die Wiederöffnung des venezolanischen Ölsektors: Sanktionslockerungen und Lizenzvergabe, die Rückkehr internationaler Betreiber, die Erholung von Förderung und Exporten, die Reform des Kohlenwasserstoffrechts und der Verträge sowie die Umstrukturierung der Staatsschulden.',
  editorial_summary_en = 'Venezuela holds the world''s largest proven crude reserves, most of it heavy oil in the Orinoco belt, and years of sanctions had left the sector largely closed to Western operators. Sanctions relief reversed that: licences were issued, majors and independents negotiated returns, exports climbed to their highest level in years, and buyers in the United States, India and Europe re-entered the market. A revised hydrocarbon law, contract terms, arbitration exposure and unresolved debt claims determine how far the recovery can run. The economics are inseparable from the political settlement that produced them, and reporting divides over who ultimately benefits.',
  editorial_summary_de = 'Venezuela verfügt über die größten nachgewiesenen Rohölreserven der Welt, überwiegend Schweröl im Orinoco-Gürtel; jahrelange Sanktionen hatten den Sektor für westliche Betreiber weitgehend verschlossen. Die Sanktionslockerung kehrte das um: Lizenzen wurden erteilt, Konzerne und unabhängige Förderer verhandelten über eine Rückkehr, die Exporte stiegen auf den höchsten Stand seit Jahren, und Abnehmer in den USA, Indien und Europa kehrten an den Markt zurück. Ein überarbeitetes Kohlenwasserstoffgesetz, Vertragsbedingungen, Schiedsverfahren und ungeklärte Schuldenansprüche bestimmen, wie weit die Erholung tragen kann. Die Wirtschaft ist untrennbar mit der politischen Einigung verbunden, aus der sie hervorging; die Berichterstattung ist uneins darüber, wer letztlich profitiert.'
WHERE id = 'venezuela_sanctions_oil';

-- ------------------------ B. POLITICAL TRANSITION ----------------------
UPDATE friction_nodes SET
  description_en = 'The political settlement after Maduro''s removal: the interim administration''s mandate and legitimacy, the timing and conduct of elections, the opposition''s position, and governance, wage and security measures.',
  description_de = 'Die politische Einigung nach Maduros Absetzung: Mandat und Legitimität der Übergangsverwaltung, Zeitpunkt und Durchführung von Wahlen, die Position der Opposition sowie Regierungs-, Lohn- und Sicherheitsmaßnahmen.',
  editorial_summary_en = 'Maduro''s vice-president took office as acting head of state under a negotiated arrangement reached with Washington, and remained in place after the initial appointment period lapsed. The administration has replaced military commanders, raised wages and pensions, and advanced economic reform, while the opposition led by María Corina Machado was left outside the settlement and continues to press for early elections and a return from exile. Detentions and releases of opposition figures, street protests and the absence of a fixed electoral timetable are the recurring flashpoints. Whether this represents a genuine transition or a continuation of the previous governing bloc under new management is the central contested question.',
  editorial_summary_de = 'Maduros Vizepräsidentin übernahm im Rahmen einer mit Washington ausgehandelten Vereinbarung das Amt der geschäftsführenden Staatschefin und blieb auch nach Ablauf der ursprünglichen Amtszeit im Amt. Die Regierung tauschte Militärkommandeure aus, erhöhte Löhne und Renten und trieb Wirtschaftsreformen voran, während die Opposition unter María Corina Machado von der Einigung ausgeschlossen blieb und weiterhin auf vorgezogene Wahlen und eine Rückkehr aus dem Exil drängt. Festnahmen und Freilassungen von Oppositionellen, Straßenproteste und das Fehlen eines festen Wahlkalenders sind die wiederkehrenden Konfliktpunkte. Ob dies ein echter Übergang oder die Fortsetzung des bisherigen Regierungslagers unter neuer Führung ist, bleibt die zentrale strittige Frage.'
WHERE id = 'venezuela_political_transition';

-- --------------------- C. US COERCION & MILITARY ACTION -----------------
UPDATE friction_nodes SET
  description_en = 'US coercive and military action toward Venezuela: the operation that detained Maduro, continued military presence and maritime interdiction, counter-narcotics strikes on vessels and on the Tren de Aragua network, and statements proposing US annexation.',
  description_de = 'Militärisches und erzwingendes Vorgehen der USA gegenüber Venezuela: die Operation zur Festnahme Maduros, fortgesetzte Militärpräsenz und Seeblockaden, Anti-Drogen-Angriffe auf Schiffe und das Netzwerk Tren de Aragua sowie Äußerungen über eine Annexion durch die USA.',
  editorial_summary_en = 'A US military operation detained the sitting Venezuelan president, who now faces narcoterrorism proceedings in a New York court. Since then the United States has maintained a military presence in and around the country, seized tankers linked to Venezuelan crude, and carried out strikes on vessels alleged to carry narcotics as well as on the leadership of the Tren de Aragua network, in at least one case jointly with Venezuelan forces. Congressional war-powers resolutions seeking to limit the deployment were introduced and narrowly defeated. Statements from the US president proposing that Venezuela become part of the United States were publicly rejected by the interim administration. The lawfulness of the operation and of the maritime strikes remains disputed.',
  editorial_summary_de = 'Eine US-Militäroperation nahm den amtierenden venezolanischen Präsidenten fest, der sich nun in New York wegen Narkoterrorismus vor Gericht verantworten muss. Seither halten die USA eine Militärpräsenz im und um das Land aufrecht, beschlagnahmten Tanker mit venezolanischem Rohöl und führten Angriffe auf mutmaßliche Drogenschiffe sowie auf die Führung des Netzwerks Tren de Aragua durch -- in mindestens einem Fall gemeinsam mit venezolanischen Kräften. Im Kongress eingebrachte Resolutionen zu den Kriegsvollmachten, die den Einsatz begrenzen sollten, scheiterten knapp. Äußerungen des US-Präsidenten, Venezuela solle Teil der USA werden, wies die Übergangsverwaltung öffentlich zurück. Die Rechtmäßigkeit der Operation und der Angriffe auf See bleibt umstritten.'
WHERE id = 'us_venezuela_relations';

-- ------------------------- D. ESSEQUIBO DISPUTE -------------------------
UPDATE friction_nodes SET
  name_de = 'Territorialstreit um Essequibo mit Guyana',
  description_en = 'The territorial dispute between Venezuela and Guyana over the Essequibo region (Guayana Esequiba), including proceedings before the International Court of Justice and the offshore Stabroek oil block.',
  description_de = 'Der Territorialstreit zwischen Venezuela und Guyana um die Region Essequibo (Guayana Esequiba), einschließlich der Verfahren vor dem Internationalen Gerichtshof und des Offshore-Ölblocks Stabroek.',
  editorial_summary_en = 'Venezuela claims the Essequibo region, roughly two-thirds of Guyana''s territory, on the basis of a boundary settlement it regards as invalid. The dispute gained weight after major offshore oil discoveries in the adjacent Stabroek block turned Guyana into a significant producer. Guyana has brought the matter before the International Court of Justice; Venezuela contests the court''s jurisdiction and argues for direct negotiation. Coverage volume is low and episodic, spiking around hearings, but the combination of contested territory and offshore reserves keeps the escalation potential high.',
  editorial_summary_de = 'Venezuela beansprucht die Region Essequibo -- etwa zwei Drittel des Staatsgebiets von Guyana -- unter Berufung auf eine Grenzregelung, die es als ungültig ansieht. Der Streit gewann an Gewicht, nachdem große Offshore-Ölfunde im angrenzenden Stabroek-Block Guyana zu einem bedeutenden Förderland gemacht hatten. Guyana rief den Internationalen Gerichtshof an; Venezuela bestreitet dessen Zuständigkeit und fordert direkte Verhandlungen. Das Berichterstattungsvolumen ist gering und episodisch mit Spitzen um Anhörungen, doch die Kombination aus umstrittenem Gebiet und Offshore-Reserven hält das Eskalationspotenzial hoch.'
WHERE id = 'essequibo_dispute';

COMMIT;
