-- Rewrite Caucasus FN description/editorial texts to be neutral, fact-based and
-- evergreen: state what exists and what is contested, drop motive-attribution,
-- drop "coverage splits between narratives", drop temporality ("recently"/"now").
-- Also: remove the caucasus_iran_regional theater card (not worth a placeholder),
-- and neutralize the Georgia node's interpretive name ("Russia's shadow").

BEGIN;

DELETE FROM narratives_v2 WHERE id='caucasus_iran_regional';

-- ---------------- THEATER ----------------
UPDATE friction_nodes SET
 description_en = 'The South Caucasus -- Armenia, Azerbaijan and Georgia -- at the intersection of Russian, Turkish, Iranian and Euro-Atlantic interests. The region carries several unresolved disputes: the Armenia-Azerbaijan conflict centred on Nagorno-Karabakh, the question of Armenia''s alignment between the Russian-led blocs and the European Union, the status of Georgia''s breakaway regions of Abkhazia and South Ossetia, transit corridors across the region, and competition among external powers over influence, energy routes and security ties. It has seen repeated wars, including the Nagorno-Karabakh wars and the 2008 Russia-Georgia war.',
 description_de = 'Der Südkaukasus -- Armenien, Aserbaidschan und Georgien -- an der Schnittstelle russischer, türkischer, iranischer und euro-atlantischer Interessen. Die Region trägt mehrere ungelöste Streitfragen: den auf Bergkarabach zentrierten Konflikt zwischen Armenien und Aserbaidschan, die Frage von Armeniens Ausrichtung zwischen den russisch geführten Bündnissen und der Europäischen Union, den Status der abtrünnigen georgischen Regionen Abchasien und Südossetien, Transitkorridore durch die Region sowie den Wettbewerb externer Mächte um Einfluss, Energierouten und Sicherheitsbeziehungen. Sie hat wiederholt Kriege erlebt, darunter die Kriege um Bergkarabach und den russisch-georgischen Krieg von 2008.',
 editorial_summary_en = 'The South Caucasus is a small region bordered by Russia, Turkey and Iran and reached by the interests of the European Union and the United States. Its principal fault lines are long-standing. Armenia and Azerbaijan have fought over Nagorno-Karabakh in wars in 1988-1994, in 2020, and in 2023, after which Azerbaijan reestablished control of the territory and its Armenian population departed; the two states negotiate over a peace treaty and the delimitation of their border. Armenia''s alignment is disputed between its membership in the Russian-led CSTO and Eurasian Economic Union and closer ties with the EU. Georgia contests its own external orientation, including EU accession, a law on foreign-funded organisations, and election results, while Abkhazia and South Ossetia -- the subject of conflicts in the early 1990s and the 2008 Russia-Georgia war -- remain outside Tbilisi''s control and are backed by Russia. A proposed transit corridor across Armenia''s Syunik province, and competition among Russia, Turkey, Iran, Israel and the United States over energy, security and connectivity, run through the region.',
 editorial_summary_de = 'Der Südkaukasus ist eine kleine Region, die an Russland, die Türkei und den Iran grenzt und in die die Interessen der Europäischen Union und der Vereinigten Staaten hineinreichen. Seine wichtigsten Bruchlinien sind langjährig. Armenien und Aserbaidschan haben in Kriegen 1988-1994, 2020 und 2023 um Bergkarabach gekämpft; danach stellte Aserbaidschan die Kontrolle über das Gebiet wieder her, und dessen armenische Bevölkerung verließ es. Die beiden Staaten verhandeln über einen Friedensvertrag und die Grenzziehung. Armeniens Ausrichtung ist umstritten zwischen seiner Mitgliedschaft in der russisch geführten OVKS und der Eurasischen Wirtschaftsunion und engeren Beziehungen zur EU. Georgien streitet über seine eigene außenpolitische Ausrichtung, darunter den EU-Beitritt, ein Gesetz über ausländisch finanzierte Organisationen und Wahlergebnisse, während Abchasien und Südossetien -- Gegenstand von Konflikten in den frühen 1990er Jahren und des russisch-georgischen Krieges von 2008 -- außerhalb der Kontrolle Tiflis'' bleiben und von Russland unterstützt werden. Ein geplanter Transitkorridor durch Armeniens Provinz Sjunik sowie der Wettbewerb zwischen Russland, der Türkei, dem Iran, Israel und den Vereinigten Staaten um Energie, Sicherheit und Konnektivität durchziehen die Region.'
WHERE id='caucasus_theater';

-- ---------------- armenia_western_pivot ----------------
UPDATE friction_nodes SET
 description_en = 'The contested question of Armenia''s external alignment, between the Russian-led Collective Security Treaty Organization (CSTO) and Eurasian Economic Union (EAEU) on one side and the European Union and the West on the other. It encompasses Armenia''s security arrangements, trade dependencies, steps toward EU association and accession, Russian economic measures affecting Armenian trade, and a domestic political contest fought along this axis.',
 description_de = 'Die umstrittene Frage von Armeniens außenpolitischer Ausrichtung zwischen der russisch geführten Organisation des Vertrags über kollektive Sicherheit (OVKS) und der Eurasischen Wirtschaftsunion (EAWU) einerseits und der Europäischen Union und dem Westen andererseits. Sie umfasst Armeniens Sicherheitsarrangements, Handelsabhängigkeiten, Schritte in Richtung EU-Assoziierung und -Beitritt, russische Wirtschaftsmaßnahmen mit Auswirkungen auf den armenischen Handel sowie einen innenpolitischen Streit entlang dieser Achse.',
 editorial_summary_en = 'Armenia''s external alignment is a central and contested question of the country''s politics. Armenia is a member of the Russian-led CSTO and Eurasian Economic Union and has depended on Russia for security and trade. Its defeats in the wars over Nagorno-Karabakh opened a debate over those arrangements and over closer relations with the European Union, including trade measures, an association and accession debate, and high-level European engagement. Armenian politics divides between forces favouring alignment with Russia and the Russian-led blocs and those favouring integration with the EU, and national elections have been contested on this axis. Russia has applied economic measures affecting Armenian exports and has publicly stated that an EU turn would carry economic consequences. The dispute involves security guarantees, trade dependence, energy and domestic political competition at once.',
 editorial_summary_de = 'Armeniens außenpolitische Ausrichtung ist eine zentrale und umstrittene Frage der Politik des Landes. Armenien ist Mitglied der russisch geführten OVKS und der Eurasischen Wirtschaftsunion und war in Sicherheit und Handel von Russland abhängig. Seine Niederlagen in den Kriegen um Bergkarabach eröffneten eine Debatte über diese Arrangements und über engere Beziehungen zur Europäischen Union, einschließlich Handelsmaßnahmen, einer Assoziierungs- und Beitrittsdebatte und hochrangiger europäischer Kontakte. Die armenische Politik teilt sich zwischen Kräften, die eine Ausrichtung auf Russland und die russisch geführten Bündnisse befürworten, und solchen, die eine Integration in die EU befürworten; nationale Wahlen wurden entlang dieser Achse ausgetragen. Russland hat Wirtschaftsmaßnahmen ergriffen, die armenische Ausfuhren betreffen, und öffentlich erklärt, eine Wende zur EU habe wirtschaftliche Folgen. Der Streit betrifft zugleich Sicherheitsgarantien, Handelsabhängigkeit, Energie und den innenpolitischen Wettbewerb.'
WHERE id='armenia_western_pivot';

-- ---------------- armenia_azerbaijan_settlement ----------------
UPDATE friction_nodes SET
 description_en = 'The conflict between Armenia and Azerbaijan and efforts to settle it. The dispute is centred on Nagorno-Karabakh, a territory internationally recognised as part of Azerbaijan and inhabited by ethnic Armenians until 2023, fought over in wars in 1988-1994, in 2020, and in 2023, after which Azerbaijan reestablished control and the region''s Armenian population left. Contested issues include a peace treaty, border delimitation, the status of detainees and prisoners, accountability and war-crimes claims, mutual territorial and constitutional claims, and the parallel normalisation between Armenia and Turkey, whose shared border has been closed since the 1990s. Border clashes and ceasefire violations have recurred.',
 description_de = 'Der Konflikt zwischen Armenien und Aserbaidschan und die Bemühungen um seine Beilegung. Der Streit dreht sich um Bergkarabach, ein völkerrechtlich als Teil Aserbaidschans anerkanntes und bis 2023 von ethnischen Armeniern bewohntes Gebiet, um das in Kriegen 1988-1994, 2020 und 2023 gekämpft wurde; danach stellte Aserbaidschan die Kontrolle wieder her, und die armenische Bevölkerung der Region ging fort. Umstritten sind ein Friedensvertrag, die Grenzziehung, der Status von Gefangenen und Inhaftierten, Fragen der Verantwortung und Kriegsverbrechensvorwürfe, gegenseitige territoriale und verfassungsrechtliche Ansprüche sowie die parallele Normalisierung zwischen Armenien und der Türkei, deren gemeinsame Grenze seit den 1990er Jahren geschlossen ist. Grenzgefechte und Verstöße gegen den Waffenstillstand traten wiederholt auf.',
 editorial_summary_en = 'The Armenia-Azerbaijan conflict is the region''s longest-running interstate dispute, centred on Nagorno-Karabakh, a territory internationally recognised as Azerbaijani and inhabited by ethnic Armenians. It was fought over in a first war in 1988-1994, a second war in 2020, and a 2023 Azerbaijani operation, after which Azerbaijan reestablished full control and the territory''s Armenian population departed. The two states have negotiated toward a peace treaty and the delimitation of their border, with outstanding issues including the return of prisoners and detainees, accountability and war-crimes allegations, mutual constitutional and territorial claims, and guarantees against renewed fighting. In parallel, Armenia and Turkey -- whose shared border has been closed since the 1990s -- have pursued normalisation, including talks on trade and reopening rail and road links. The situation spans a diplomatic track and a persistent risk of renewed border clashes.',
 editorial_summary_de = 'Der Konflikt zwischen Armenien und Aserbaidschan ist der am längsten andauernde zwischenstaatliche Streit der Region und dreht sich um Bergkarabach, ein völkerrechtlich als aserbaidschanisch anerkanntes und von ethnischen Armeniern bewohntes Gebiet. Um es wurde in einem ersten Krieg 1988-1994, einem zweiten Krieg 2020 und einer aserbaidschanischen Operation 2023 gekämpft; danach stellte Aserbaidschan die vollständige Kontrolle wieder her, und die armenische Bevölkerung des Gebiets ging fort. Die beiden Staaten haben über einen Friedensvertrag und die Grenzziehung verhandelt, mit offenen Fragen wie der Rückkehr von Gefangenen und Inhaftierten, Verantwortungs- und Kriegsverbrechensvorwürfen, gegenseitigen verfassungsrechtlichen und territorialen Ansprüchen und Garantien gegen erneute Kämpfe. Parallel dazu haben Armenien und die Türkei -- deren gemeinsame Grenze seit den 1990er Jahren geschlossen ist -- eine Normalisierung verfolgt, einschließlich Gesprächen über Handel und die Wiedereröffnung von Bahn- und Straßenverbindungen. Die Lage umfasst einen diplomatischen Weg und ein anhaltendes Risiko erneuter Grenzgefechte.'
WHERE id='armenia_azerbaijan_settlement';

-- ---------------- georgia_geopolitical_drift (also neutralize name) ----------------
UPDATE friction_nodes SET
 name_en = 'Georgia''s external orientation and internal disputes',
 name_de = 'Georgiens außenpolitische Ausrichtung und innere Auseinandersetzungen',
 description_en = 'Disputes over Georgia''s external orientation and domestic politics. At issue are the country''s EU accession candidacy; a law requiring registration of organisations that receive foreign funding, and disagreement over its scope and comparability to laws in Russia and in Western states; contested election results and protests; and the status of Abkhazia and South Ossetia, which separated from Georgian control in conflicts in the early 1990s and the 2008 Russia-Georgia war and are backed by Russia. These issues divide the governing party, the opposition and EU institutions over the country''s direction.',
 description_de = 'Auseinandersetzungen über Georgiens außenpolitische Ausrichtung und Innenpolitik. Umstritten sind der EU-Beitrittskandidatenstatus des Landes; ein Gesetz, das die Registrierung von Organisationen mit ausländischer Finanzierung verlangt, sowie Meinungsverschiedenheiten über dessen Reichweite und Vergleichbarkeit mit Gesetzen in Russland und in westlichen Staaten; umstrittene Wahlergebnisse und Proteste; und der Status von Abchasien und Südossetien, die sich in Konflikten in den frühen 1990er Jahren und im russisch-georgischen Krieg 2008 der georgischen Kontrolle entzogen und von Russland unterstützt werden. Diese Fragen spalten die Regierungspartei, die Opposition und EU-Institutionen über die Richtung des Landes.',
 editorial_summary_en = 'Georgia, a state on Russia''s southern border, is the subject of recurring disputes over its external orientation and internal politics. It holds EU candidate status, and disagreements over progress toward accession are central. A law requiring organisations that receive foreign funding to register drew large protests and criticism from EU institutions; the government compares it to transparency laws in Western states, while opponents compare it to Russian legislation. Election results and the conduct of votes have been contested between the governing party and the opposition, at times accompanied by street protests and police response. Abkhazia and South Ossetia, which separated from Georgian control in conflicts in the early 1990s and again during the 2008 Russia-Georgia war, remain outside Tbilisi''s authority and are backed by Russia. The node is maintained as a standing placeholder for a region where tensions can escalate quickly.',
 editorial_summary_de = 'Georgien, ein Staat an Russlands Südgrenze, ist Gegenstand wiederkehrender Auseinandersetzungen über seine außenpolitische Ausrichtung und seine Innenpolitik. Es besitzt den EU-Kandidatenstatus, und Meinungsverschiedenheiten über die Fortschritte beim Beitritt stehen im Zentrum. Ein Gesetz, das Organisationen mit ausländischer Finanzierung zur Registrierung verpflichtet, löste große Proteste und Kritik von EU-Institutionen aus; die Regierung vergleicht es mit Transparenzgesetzen in westlichen Staaten, während Gegner es mit russischer Gesetzgebung vergleichen. Wahlergebnisse und der Ablauf von Abstimmungen wurden zwischen der Regierungspartei und der Opposition bestritten, zeitweise begleitet von Straßenprotesten und Polizeieinsätzen. Abchasien und Südossetien, die sich in Konflikten in den frühen 1990er Jahren und erneut während des russisch-georgischen Krieges 2008 der georgischen Kontrolle entzogen, bleiben außerhalb der Autorität Tiflis'' und werden von Russland unterstützt. Der Knoten wird als dauerhafter Platzhalter für eine Region geführt, in der Spannungen schnell eskalieren können.'
WHERE id='georgia_geopolitical_drift';

-- ---------------- zangezur_corridor ----------------
UPDATE friction_nodes SET
 description_en = 'A proposed transit route across Armenia''s Syunik province connecting the main territory of Azerbaijan with its Nakhchivan exclave, and potentially onward to Turkey, the Caspian and Central Asia; also referred to as the "Trump Route" or TRIPP. Contested issues include sovereignty and control over the section crossing Armenian territory, questions of extraterritoriality, the effect on Iran''s land border with Armenia, Russia''s role, and the balance between trade connectivity and security concerns.',
 description_de = 'Eine geplante Transitroute durch Armeniens Provinz Sjunik, die das Kernland Aserbaidschans mit seiner Exklave Nachitschewan und möglicherweise weiter mit der Türkei, dem Kaspischen Meer und Zentralasien verbindet; auch als "Trump-Route" oder TRIPP bezeichnet. Umstritten sind Souveränität und Kontrolle über den durch armenisches Gebiet führenden Abschnitt, Fragen der Extraterritorialität, die Auswirkung auf Irans Landgrenze zu Armenien, Russlands Rolle sowie das Gleichgewicht zwischen Handelskonnektivität und Sicherheitsbedenken.',
 editorial_summary_en = 'The Zangezur corridor is a proposed transport link that would cross Armenia''s southern Syunik province to connect the main territory of Azerbaijan with its Nakhchivan exclave, and, if extended, link Turkey with the Caspian and Central Asia. Proposals have included an arrangement referred to as the "Trump Route" or TRIPP, involving a United States operating role. The route is contested on several grounds: whether and how Armenia retains sovereignty and control over the section on its territory; Iran''s opposition to an arrangement that would cut its land border with Armenia; Russia''s role in monitoring or guaranteeing transit; and the trade-off between the economic benefits of connectivity and the security concerns of the states affected. As a physical link between the peace process and regional trade, the corridor draws together the interests of Armenia, Azerbaijan, Turkey, Iran, Russia and the United States in a single route.',
 editorial_summary_de = 'Der Sangesur-Korridor ist eine geplante Verkehrsverbindung, die durch Armeniens südliche Provinz Sjunik verlaufen würde, um das Kernland Aserbaidschans mit seiner Exklave Nachitschewan zu verbinden und, sofern verlängert, die Türkei mit dem Kaspischen Meer und Zentralasien. Vorschläge umfassten eine als "Trump-Route" oder TRIPP bezeichnete Regelung mit einer US-amerikanischen Betreiberrolle. Die Route ist aus mehreren Gründen umstritten: ob und wie Armenien Souveränität und Kontrolle über den Abschnitt auf seinem Gebiet behält; Irans Ablehnung einer Regelung, die seine Landgrenze zu Armenien durchtrennen würde; Russlands Rolle bei der Überwachung oder Absicherung des Transits; und der Abwägung zwischen dem wirtschaftlichen Nutzen der Konnektivität und den Sicherheitsbedenken der betroffenen Staaten. Als physische Verbindung zwischen dem Friedensprozess und dem regionalen Handel bündelt der Korridor die Interessen Armeniens, Aserbaidschans, der Türkei, des Irans, Russlands und der Vereinigten Staaten in einer einzigen Route.'
WHERE id='zangezur_corridor';

-- ---------------- caucasus_power_competition ----------------
UPDATE friction_nodes SET
 description_en = 'Competition among external powers -- Russia, Turkey, Iran, Israel and the United States -- for influence in the South Caucasus. It runs through Azerbaijani energy resources and export routes (the state company SOCAR, the Southern Gas Corridor, Caspian hydrocarbons), security and defence ties, the dispute between Israel and Turkey around recognition of the Armenian Genocide, tensions between Russia and Azerbaijan, and competing connectivity axes such as the Zangezur route and the International North-South Transport Corridor.',
 description_de = 'Der Wettbewerb externer Mächte -- Russland, Türkei, Iran, Israel und die Vereinigten Staaten -- um Einfluss im Südkaukasus. Er verläuft über aserbaidschanische Energieressourcen und Exportrouten (die staatliche Gesellschaft SOCAR, den Südlichen Gaskorridor, kaspische Kohlenwasserstoffe), Sicherheits- und Verteidigungsbeziehungen, den Streit zwischen Israel und der Türkei um die Anerkennung des Völkermords an den Armeniern, Spannungen zwischen Russland und Aserbaidschan sowie konkurrierende Konnektivitätsachsen wie die Sangesur-Route und den Internationalen Nord-Süd-Transportkorridor.',
 editorial_summary_en = 'The South Caucasus lies at the meeting point of several external powers that compete for influence as the regional balance shifts. Azerbaijan''s energy resources -- managed through the state company SOCAR and exported via the Southern Gas Corridor -- underpin its relations with Europe and Turkey, and Caspian hydrocarbons draw wider interest. Israel and Azerbaijan maintain close security and energy ties, and recognition of the Armenian Genocide by outside states is a point of contention between Israel and Turkey and has drawn Azerbaijani objection. Relations between Russia and Azerbaijan have been strained by incidents including detentions of nationals and a strike on a SOCAR facility. Iran opposes external military presence near its northern border. Competing transport projects -- the Zangezur route and the Iran-Russia International North-South Transport Corridor -- add an economic dimension to the contest among Russia, Turkey, Iran, Israel and the United States.',
 editorial_summary_de = 'Der Südkaukasus liegt am Schnittpunkt mehrerer externer Mächte, die um Einfluss konkurrieren, während sich das regionale Gleichgewicht verschiebt. Aserbaidschans Energieressourcen -- verwaltet über die staatliche Gesellschaft SOCAR und exportiert über den Südlichen Gaskorridor -- untermauern seine Beziehungen zu Europa und der Türkei, und kaspische Kohlenwasserstoffe wecken breiteres Interesse. Israel und Aserbaidschan unterhalten enge Sicherheits- und Energiebeziehungen, und die Anerkennung des Völkermords an den Armeniern durch außenstehende Staaten ist ein Streitpunkt zwischen Israel und der Türkei und hat aserbaidschanischen Widerspruch hervorgerufen. Die Beziehungen zwischen Russland und Aserbaidschan sind durch Vorfälle wie die Festnahme von Staatsbürgern und einen Angriff auf eine SOCAR-Anlage belastet. Der Iran lehnt eine externe Militärpräsenz nahe seiner Nordgrenze ab. Konkurrierende Verkehrsprojekte -- die Sangesur-Route und der iranisch-russische Internationale Nord-Süd-Transportkorridor -- fügen dem Wettstreit zwischen Russland, der Türkei, dem Iran, Israel und den Vereinigten Staaten eine wirtschaftliche Dimension hinzu.'
WHERE id='caucasus_power_competition';

COMMIT;
