
-- us_fed_independence (75 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_fed_independence', 'us_fed_independence fn_anchor', '{"ar": ["رئيس الاحتياطي الفيدرالي", "محافظ الاحتياطي الفيدرالي", "استقلال الاحتياطي الفيدرالي", "جيروم باول", "كيفن وارش", "ليزا كوك", "ميشيل بومان", "كيفن هاسيت", "اللجنة الفيدرالية للسوق المفتوحة"], "de": ["Fed-Chef", "Notenbankchef", "Fed-Gouverneur", "Fed-Vorständin", "Fed-Vorstand", "Unabhängigkeit der US-Notenbank", "Notenbank-Unabhängigkeit"], "en": ["Fed chair", "Fed chairman", "Fed chief", "Federal Reserve chair", "Fed governor", "Federal Reserve governor", "Fed independence", "Federal Reserve independence", "central bank independence", "Powell", "Kevin Warsh", "Lisa Cook", "Michelle Bowman", "Hassett", "FOMC"], "es": ["presidente de la Fed", "gobernador de la Fed", "independencia de la Fed"], "fr": ["président de la Fed", "gouverneur de la Fed", "indépendance de la Fed"], "hi": ["फेड अध्यक्ष", "फेड गवर्नर", "फेड की स्वतंत्रता", "जेरोम पॉवेल", "केविन वार्श", "लिसा कुक", "मिशेल बोमन", "केविन हासेट"], "it": ["presidente della Fed", "governatore della Fed", "indipendenza della Fed"], "ja": ["FRB議長", "FRB理事", "FRBの独立性", "パウエル", "ウォーシュ", "リサ・クック", "ボウマン", "ハセット", "連邦公開市場委員会"], "ru": ["глава ФРС", "член совета управляющих ФРС", "независимость ФРС", "Пауэлл", "Уорш", "Лиза Кук", "Боуман", "Хассет", "Комитет по открытым рынкам"], "zh": ["美联储主席", "美联储理事", "美联储独立性", "鲍威尔", "沃什", "丽莎·库克", "鲍曼", "哈塞特", "联邦公开市场委员会"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_epstein_elite_network (22 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_epstein_elite_network', 'us_epstein_elite_network fn_anchor', '{"ar": ["إبستين", "غيسلين ماكسويل"], "de": [], "en": ["Epstein", "Ghislaine", "Giuffre", "Wexner", "Leon Black", "Mandelson", "Zorro Ranch", "Little St. James"], "es": [], "fr": [], "hi": ["एपस्टीन", "गिस्लेन मैक्सवेल"], "it": [], "ja": ["エプスタイン", "ギレーヌ・マクスウェル"], "ru": ["Эпштейн", "Гислейн Максвелл", "Джуффре", "Векснер", "Мандельсон"], "zh": ["爱泼斯坦", "吉丝莲", "朱弗雷"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_interior_immigration_enforcement (46 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_interior_immigration_enforcement', 'us_interior_immigration_enforcement fn_anchor', '{"ar": ["إدارة الهجرة والجمارك", "ترحيل", "مركز احتجاز"], "de": ["ICE-Gewahrsam", "Einwanderungsbehörde", "Heimatschutzministerium", "Abschiebung", "abgeschoben", "Haftanstalt", "Abschiebehaft", "Zufluchtsstadt"], "en": ["ICE", "DHS", "Homeland Security", "deport", "immigration detention", "detention center", "detention centre", "detainee", "expedited removal", "removal flight", "TPS", "Temporary Protected Status", "sanctuary city", "sanctuary state", "Alligator Alcatraz", "border czar"], "es": ["el ICE", "deportación", "deportado", "centro de detención", "ciudad santuario"], "fr": ["expulsion", "centre de rétention"], "hi": ["आईसीई", "निर्वासन", "हिरासत केंद्र"], "it": ["deportazione"], "ja": ["移民税関捜査局", "強制送還", "収容施設"], "ru": ["депортация", "центр содержания"], "zh": ["移民及海关执法局", "驱逐出境", "拘留中心"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_electoral_legitimacy (70 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_electoral_legitimacy', 'us_electoral_legitimacy fn_anchor', '{"ar": ["انتخابات التجديد النصفي", "إعادة تقسيم الدوائر", "الاقتراع", "تزوير الانتخابات"], "de": ["Zwischenwahl", "Wahlbezirk", "Neuzuschnitt", "Briefwahl", "Stimmzettel", "Wählerverzeichnis", "Wählerausweis", "Wahlbetrug", "Wahlintegrität"], "en": ["midterm", "redistricting", "congressional map", "voting map", "gerrymander", "ballot", "mail-in", "absentee", "voter ID", "voter roll", "voter purge", "proof of citizenship", "citizenship requirement", "voter intimidation", "Voting Rights Act", "voting rights", "election fraud", "election integrity", "election security", "election interference", "voting machine", "poll watcher", "primary election", "electoral college", "turnout"], "es": ["elecciones de mitad de mandato", "redistribución de distritos", "voto por correo", "papeleta", "padrón electoral", "fraude electoral"], "fr": ["élections de mi-mandat", "redécoupage", "vote par correspondance", "fraude électorale"], "hi": ["मध्यावधि चुनाव", "परिसीमन", "मतपत्र", "चुनावी धोखाधड़ी"], "it": ["elezioni di midterm", "ridefinizione dei collegi", "voto per corrispondenza", "frode elettorale"], "ja": ["中間選挙", "選挙区割り", "郵便投票", "選挙不正"], "ru": ["промежуточные выборы", "перекройка округов", "бюллетень", "списки избирателей", "фальсификация выборов"], "zh": ["中期选举", "选区重划", "邮寄选票", "选民身份", "选举舞弊"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_judicial_constraint (103 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_judicial_constraint', 'us_judicial_constraint fn_anchor', '{"ar": ["المحكمة العليا الأمريكية", "الجنسية بالولادة", "قاض فيدرالي", "فصل السلطات", "أمر تنفيذي"], "de": ["US-Supreme-Court", "Oberster Gerichtshof der USA", "Staatsbürgerschaftsrecht", "Geburtsortsprinzip", "Bundesrichter", "Berufungsgericht", "einstweilige Verfügung", "Gewaltenteilung", "verfassungswidrig", "Unabhängigkeit der Justiz", "Dekret", "Verfügung"], "en": ["SCOTUS", "US Supreme Court", "U.S. Supreme Court", "Supreme Court justice", "chief justice", "Supreme Court rules", "Supreme Court ruling", "Supreme Court blocks", "Supreme Court upholds", "Supreme Court allows", "Supreme Court rejects", "Supreme Court denies", "Supreme Court strikes", "Supreme Court clears", "Supreme Court sides", "Supreme Court hears", "Supreme Court weighs", "Supreme Court backs", "Supreme Court lets", "Supreme Court tosses", "Supreme Court expands", "Supreme Court restores", "birthright citizenship", "federal judge", "appeals court", "district judge", "injunction", "shadow docket", "stay of the ruling", "separation of powers", "judicial independence", "judicial review", "unconstitutional", "presidential power", "executive power", "executive order", "Clarence Thomas", "Coney Barrett", "Sotomayor", "Kavanaugh", "Gorsuch", "Ketanji", "Neil Gorsuch"], "es": ["Tribunal Supremo de EE", "ciudadanía por nacimiento", "juez federal", "medida cautelar", "separación de poderes", "inconstitucional", "orden ejecutiva"], "fr": ["Cour suprême des États-Unis", "droit du sol", "juge fédéral", "injonction", "séparation des pouvoirs", "inconstitutionnel", "décret présidentiel"], "hi": ["अमेरिकी सुप्रीम कोर्ट", "जन्मसिद्ध नागरिकता", "संघीय न्यायाधीश", "शक्तियों का पृथक्करण", "कार्यकारी आदेश"], "it": ["cittadinanza per nascita", "giudice federale", "ingiunzione", "separazione dei poteri", "incostituzionale", "ordine esecutivo"], "ja": ["米連邦最高裁", "出生地主義", "連邦判事", "三権分立", "大統領令"], "ru": ["Верховный суд США", "гражданство по рождению", "федеральный судья", "судебный запрет", "разделение властей", "указ президента"], "zh": ["美国最高法院", "出生公民权", "联邦法官", "禁令", "三权分立", "违宪", "行政命令"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_executive_loyalty (49 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_executive_loyalty', 'us_executive_loyalty fn_anchor', '{"ar": ["بام بوندي", "غابارد", "المدعي العام"], "de": ["Justizministerin", "Justizminister", "Generalstaatsanwalt", "Generalinspekteur", "FBI-Direktor", "Geheimdienstchefin", "Geheimdienstchef", "Kabinettsumbildung"], "en": ["Pam Bondi", "Noem", "Gabbard", "Kash Patel", "Todd Blanche", "Jay Clayton", "attorney general", "inspector general", "watchdog fired", "FBI director", "intelligence chief", "national intelligence", "cabinet shakeup", "cabinet reshuffle"], "es": ["fiscal general", "director del FBI", "jefa de inteligencia", "remodelación del gabinete"], "fr": ["procureur général"], "hi": ["अटॉर्नी जनरल"], "it": ["procuratore generale"], "ja": ["パム・ボンディ", "ギャバード", "司法長官"], "ru": ["Пэм Бонди", "Ноэм", "Габбард", "Кэш Пател", "генеральный прокурор", "директор ФБР", "глава разведки"], "zh": ["帕姆·邦迪", "诺姆", "加巴德", "卡什·帕特尔", "司法部长", "联邦调查局局长", "情报总监"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_political_violence (41 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_political_violence', 'us_political_violence fn_anchor', '{"ar": ["الخدمة السرية", "محاولة اغتيال", "العنف السياسي"], "de": ["Attentat", "Attentatsversuch", "politische Gewalt", "Extremist"], "en": ["Secret Service", "assassination attempt", "assassination plot", "attempted assassination", "political violence", "politically motivated", "Correspondents", "Cole Allen", "extremist", "foiled plot", "sniper"], "es": ["Servicio Secreto", "intento de asesinato", "atentado", "violencia política", "extremista"], "fr": ["tentative d''assassinat", "violence politique"], "hi": ["सीक्रेट सर्विस", "हत्या का प्रयास", "राजनीतिक हिंसा"], "it": ["tentato omicidio", "attentato", "violenza politica"], "ja": ["シークレットサービス", "暗殺未遂", "政治的暴力"], "ru": ["Секретная служба", "покушение", "политическое насилие", "экстремист"], "zh": ["特勤局", "暗杀未遂", "政治暴力"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- us_press_freedom (57 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'us_press_freedom', 'us_press_freedom fn_anchor', '{"ar": ["رخصة البث", "حرية الصحافة", "الرقابة"], "de": ["Sendelizenz", "Rundfunklizenz", "Pressefreiheit", "Erster Verfassungszusatz", "Zensur", "öffentlich-rechtlicher Rundfunk"], "en": ["Kimmel", "broadcast license", "broadcast licence", "license review", "FCC chair", "FCC orders", "FCC opens", "press freedom", "freedom of the press", "First Amendment", "censorship", "editorial independence", "NPR", "PBS", "public broadcasting", "Comey", "CPJ", "Committee to Protect Journalists"], "es": ["licencia de emisión", "libertad de prensa", "Primera Enmienda", "censura"], "fr": ["licence de diffusion", "liberté de la presse", "Premier Amendement", "censure"], "hi": ["प्रेस की स्वतंत्रता", "सेंसरशिप"], "it": ["licenza di trasmissione", "libertà di stampa", "Primo Emendamento", "censura"], "ja": ["キンメル", "放送免許", "報道の自由", "検閲"], "ru": ["Киммел", "вещательная лицензия", "свобода прессы", "Первая поправка", "цензура", "Коми"], "zh": ["基梅尔", "广播执照", "新闻自由", "第一修正案", "审查", "科米"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();
