-- us_china_theater: completeness fields (Phase 2 step 8) -- name_de,
-- description_en/_de, editorial_summary_en/_de for the theater and all five
-- active atomics.
--
-- Prose is neutral, fact-based and evergreen per the FN-description rule:
-- no framing, no motive attribution, no stance vocabulary, no temporality.
-- All framing lives in narratives_v2. Where the prose mentions how coverage
-- splits, it reports the split as an observable fact rather than adopting a
-- side (same house style as arctic_theater / greenland_control).
--
-- The theater is also RENAMED: "US-China strategic competition" implied the
-- geographic flashpoints (Taiwan, South China Sea, Korea, Panama, Latin
-- America, the Arctic) which are owned by their own theaters. The scope
-- approved on 2026-07-16 is the bilateral economic and technological dyad.

BEGIN;

-- ============================ THEATER ============================
UPDATE friction_nodes SET
  name_en = 'US-China economic and technological competition',
  name_de = 'Wirtschaftlicher und technologischer Wettbewerb USA-China',
  description_en = 'The bilateral economic and technological contest between the United States and China: tariffs and trade investigations, export controls on advanced semiconductors, the competition over artificial intelligence, dependence on Chinese critical-mineral supply, and the leader-level diplomacy conducted alongside them. Both governments hold and use restrictive instruments — Washington licenses access to advanced chips and design tools, Beijing licenses rare-earth exports and decides on market access and foreign acquisitions. The geographic flashpoints where the two also compete are carried by separate theaters.',
  description_de = 'Der bilaterale wirtschaftliche und technologische Wettstreit zwischen den Vereinigten Staaten und China: Zölle und Handelsuntersuchungen, Exportkontrollen für Spitzenhalbleiter, der Wettbewerb um künstliche Intelligenz, die Abhängigkeit von chinesischen kritischen Rohstoffen sowie die begleitende Diplomatie auf Führungsebene. Beide Regierungen verfügen über restriktive Instrumente und setzen sie ein: Washington lizenziert den Zugang zu Spitzenchips und Entwurfswerkzeugen, Peking lizenziert Exporte Seltener Erden und entscheidet über Marktzugang und ausländische Übernahmen. Die geografischen Brennpunkte, an denen beide ebenfalls konkurrieren, werden in eigenen Theatern geführt.',
  editorial_summary_en = 'The United States and China are engaged in a bilateral contest conducted almost entirely through economic and technological instruments. Five strands run through it: tariffs and Section 301 investigations, with US tariff authority itself subject to domestic litigation; export controls on advanced semiconductors, design tools and lithography, coordinated with allied governments; a close race in artificial intelligence in which Chinese models have narrowed the capability gap and firms on both sides contest access, users and blacklisting; dependence on Chinese rare-earth mining, refining and magnet production, met with stockpiling and allied minerals agreements; and leader-level summitry that produced tariff reductions, restored agricultural and aircraft purchases, and an agreed dialogue on artificial intelligence. Restriction runs in both directions: Washington controls what may be exported, while Beijing has withheld approval for chips US authorities had cleared, listed US rare-earth producers under its own export controls, barred procurement from US firms, and blocked a US acquisition of a Chinese AI developer. Coverage divides on observable lines: Western and allied outlets treat the contest as one to be managed and won, Chinese state media present restriction as suppression of legitimate development and cooperation as the alternative, a self-critical Western strand argues the instruments are imposing costs at home, and Russian state media read the relationship as evidence of a multipolar order.',
  editorial_summary_de = 'Die Vereinigten Staaten und China tragen einen bilateralen Wettstreit aus, der fast ausschließlich mit wirtschaftlichen und technologischen Instrumenten geführt wird. Fünf Stränge durchziehen ihn: Zölle und Section-301-Verfahren, wobei die US-Zollbefugnis selbst Gegenstand innerstaatlicher Gerichtsverfahren ist; Exportkontrollen für Spitzenhalbleiter, Entwurfswerkzeuge und Lithografie, abgestimmt mit verbündeten Regierungen; ein enges Rennen in der künstlichen Intelligenz, in dem chinesische Modelle den Leistungsabstand verringert haben und Firmen beider Seiten um Zugang, Nutzer und Listungen streiten; die Abhängigkeit von chinesischer Förderung, Raffination und Magnetproduktion Seltener Erden, der mit Reservehaltung und Rohstoffabkommen unter Verbündeten begegnet wird; sowie Gipfeldiplomatie, aus der Zollsenkungen, wieder aufgenommene Agrar- und Flugzeugkäufe und ein vereinbarter Dialog zur künstlichen Intelligenz hervorgingen. Beschränkungen wirken in beide Richtungen: Washington kontrolliert, was ausgeführt werden darf, während Peking die Einfuhr von Chips verweigerte, die US-Behörden freigegeben hatten, US-Produzenten Seltener Erden auf die eigene Exportkontrollliste setzte, die Beschaffung bei US-Firmen untersagte und eine US-Übernahme eines chinesischen KI-Entwicklers blockierte. Die Berichterstattung teilt sich entlang beobachtbarer Linien: westliche und verbündete Medien behandeln den Wettstreit als steuer- und gewinnbar, chinesische Staatsmedien deuten Beschränkungen als Unterdrückung legitimer Entwicklung und Kooperation als Alternative, ein selbstkritischer westlicher Strang sieht die Instrumente Kosten im Inland verursachen, und russische Staatsmedien lesen die Beziehung als Beleg einer multipolaren Ordnung.',
  updated_at = now()
WHERE id = 'us_china_theater';

-- ============================ ATOMIC: summit diplomacy ============================
UPDATE friction_nodes SET
  name_de = 'Gipfeldiplomatie und Beziehungsmanagement',
  description_en = 'Leader-level contact between Washington and Beijing and the management of the bilateral relationship around it: state visits and summit meetings, the accompanying business delegations, and the outcomes announced from them, including tariff adjustments, agricultural and aircraft purchases and dialogue channels. The agenda routinely extends beyond the dyad to third-party files such as Iran, Taiwan and North Korea, which are carried by their own theaters.',
  description_de = 'Kontakte auf Führungsebene zwischen Washington und Peking und das Management der bilateralen Beziehung darum herum: Staatsbesuche und Gipfeltreffen, die begleitenden Wirtschaftsdelegationen sowie die daraus verkündeten Ergebnisse, darunter Zollanpassungen, Agrar- und Flugzeugkäufe und Dialogkanäle. Die Tagesordnung reicht regelmäßig über die Dyade hinaus zu Drittthemen wie Iran, Taiwan und Nordkorea, die in eigenen Theatern geführt werden.',
  editorial_summary_en = 'Leader-level diplomacy is the largest single strand of coverage in the US-China relationship. A state visit to Beijing brought the US president and a delegation of company chief executives to meetings with Xi Jinping, followed by a reciprocal invitation to Washington. The announced outcomes were economic: reciprocal tariff reductions, renewed import permits for US beef, soybean purchase commitments, an aircraft order, and agreement to open an intergovernmental dialogue on artificial intelligence. Other agenda items — Iran, Taiwan, North Korea — produced no announced agreement. Coverage of the same events divides sharply: Chinese state media present the meetings as a new chapter of major-power cooperation, Western and allied outlets split between reading them as a working stabilisation of the rivalry and as a thin return for a state visit, and Russian state media read them as evidence of relative American decline. A large share of Western reporting is descriptive rather than evaluative.',
  editorial_summary_de = 'Diplomatie auf Führungsebene ist der größte einzelne Berichterstattungsstrang der Beziehung zwischen den USA und China. Ein Staatsbesuch in Peking führte den US-Präsidenten und eine Delegation von Unternehmenschefs zu Treffen mit Xi Jinping, gefolgt von einer Gegeneinladung nach Washington. Die verkündeten Ergebnisse waren wirtschaftlicher Natur: wechselseitige Zollsenkungen, erneuerte Einfuhrgenehmigungen für US-Rindfleisch, Zusagen zum Sojabohnenkauf, eine Flugzeugbestellung und die Vereinbarung, einen zwischenstaatlichen Dialog zur künstlichen Intelligenz aufzunehmen. Weitere Tagesordnungspunkte — Iran, Taiwan, Nordkorea — brachten keine verkündete Einigung. Die Berichterstattung über dieselben Ereignisse geht deutlich auseinander: chinesische Staatsmedien präsentieren die Treffen als neues Kapitel der Großmächtekooperation, westliche und verbündete Medien schwanken zwischen der Lesart einer funktionierenden Stabilisierung der Rivalität und der einer dünnen Ausbeute für einen Staatsbesuch, und russische Staatsmedien deuten sie als Beleg relativen amerikanischen Machtverlusts. Ein großer Teil der westlichen Berichterstattung ist beschreibend statt wertend.',
  updated_at = now()
WHERE id = 'us_china_summit_diplomacy';

-- ============================ ATOMIC: trade and tariffs ============================
UPDATE friction_nodes SET
  name_de = 'Handels- und Zollwettbewerb',
  description_en = 'Tariffs, trade investigations and market-access disputes between the United States and China: Section 301 proceedings, tariff rates and their escalation or reduction, anti-dumping measures, agricultural access for US soybeans and beef, treatment of Chinese electric vehicles in the US market, and government procurement restrictions applied in both directions. US tariff authority has been subject to domestic litigation, and both governments have applied and withdrawn measures during the period.',
  description_de = 'Zölle, Handelsuntersuchungen und Streitigkeiten über Marktzugang zwischen den Vereinigten Staaten und China: Section-301-Verfahren, Zollsätze und deren Erhöhung oder Senkung, Antidumpingmaßnahmen, Marktzugang für US-Sojabohnen und -Rindfleisch, die Behandlung chinesischer Elektrofahrzeuge im US-Markt sowie Beschaffungsbeschränkungen der öffentlichen Hand in beide Richtungen. Die US-Zollbefugnis war Gegenstand innerstaatlicher Gerichtsverfahren; beide Regierungen haben im Zeitraum Maßnahmen ergriffen und wieder zurückgenommen.',
  editorial_summary_en = 'The tariff relationship moved through escalation and partial de-escalation. The United States opened Section 301 investigations covering China and a number of other trading partners; a domestic court ruling narrowed the tariff authority those measures rest on; and the Beijing summit produced reciprocal reductions on some goods together with renewed agricultural access. China applied countermeasures of its own, barring government procurement from dozens of US companies and keeping retaliation in reserve. Disputes also run through specific sectors: Chinese electric vehicles and the question of their access to the US market, soybean and beef purchases, and tariff evasion through third countries. Coverage divides less evenly here than elsewhere in the dyad. Chinese state media frame the measures as unilateral coercion outside the multilateral system. Western coverage is predominantly skeptical of the campaign — arguing it has raised costs and uncertainty for US industry and farmers while strengthening Beijing''s position — and an argument that tariff pressure is producing results is comparatively rare in headline coverage.',
  editorial_summary_de = 'Das Zollverhältnis durchlief Eskalation und teilweise Deeskalation. Die Vereinigten Staaten eröffneten Section-301-Untersuchungen gegen China und eine Reihe weiterer Handelspartner; ein innerstaatliches Gerichtsurteil beschnitt die Zollbefugnis, auf der diese Maßnahmen beruhen; und der Pekinger Gipfel brachte wechselseitige Senkungen für einige Waren sowie erneuerten Agrarmarktzugang. China ergriff eigene Gegenmaßnahmen, untersagte die öffentliche Beschaffung bei Dutzenden US-Unternehmen und hielt Vergeltung in Reserve. Streit besteht auch in einzelnen Sektoren: chinesische Elektrofahrzeuge und die Frage ihres Zugangs zum US-Markt, Sojabohnen- und Rindfleischkäufe sowie Zollumgehung über Drittstaaten. Die Berichterstattung ist hier weniger ausgewogen als sonst in der Dyade. Chinesische Staatsmedien deuten die Maßnahmen als unilateralen Zwang außerhalb des multilateralen Systems. Die westliche Berichterstattung steht der Kampagne überwiegend skeptisch gegenüber — sie habe Kosten und Unsicherheit für US-Industrie und Landwirte erhöht und zugleich Pekings Position gestärkt — während das Argument, Zolldruck bringe Ergebnisse, in der Schlagzeilenberichterstattung vergleichsweise selten vorkommt.',
  updated_at = now()
WHERE id = 'us_china_trade_tariffs';

-- ============================ ATOMIC: export controls ============================
UPDATE friction_nodes SET
  name_de = 'Exportkontrollen und Halbleiterzugang',
  description_en = 'Restrictions on the movement of advanced semiconductor technology between the United States and China: entity-list designations, licensing conditions attached to Nvidia and other US chip sales, controls on lithography equipment coordinated with allied governments, and enforcement against diversion and smuggling. Controls operate in both directions — US authorities license what may be exported, while Chinese authorities decide what may be imported and have withheld approval for chips the United States had cleared.',
  description_de = 'Beschränkungen für den Transfer fortgeschrittener Halbleitertechnologie zwischen den Vereinigten Staaten und China: Aufnahmen in die Entity List, Auflagen für Chipverkäufe von Nvidia und anderen US-Anbietern, mit verbündeten Regierungen abgestimmte Kontrollen für Lithografieanlagen sowie die Verfolgung von Umgehung und Schmuggel. Die Kontrollen wirken in beide Richtungen: US-Behörden lizenzieren, was ausgeführt werden darf, chinesische Behörden entscheiden über die Einfuhr und verweigerten die Freigabe für Chips, welche die Vereinigten Staaten bereits genehmigt hatten.',
  editorial_summary_en = 'Export controls are the principal instrument through which the United States acts on the technology relationship, and their operation has become two-sided. Washington maintains entity-list designations and licensing conditions on advanced chip sales, coordinates lithography controls with allied governments, and enforces against diversion — including a prosecution over the diversion of billions of dollars of Nvidia chips and a settlement with a US equipment maker over unlawful exports. Beijing''s response has moved beyond objection: it has withheld approval for H200 imports that US authorities had cleared for export, conditioned approvals on its own terms, and pressed domestic substitution. Chinese firms have also acquired US chip tools through Southeast Asian intermediaries. Coverage divides on disjoint lines: Western, allied and specialist outlets treat the controls as protection of a lead with direct military relevance, while Chinese state media present them as suppression of legitimate development that disrupts global chip supply chains and is failing on its own terms.',
  editorial_summary_de = 'Exportkontrollen sind das Hauptinstrument, mit dem die Vereinigten Staaten auf das Technologieverhältnis einwirken, und ihre Anwendung ist zweiseitig geworden. Washington unterhält Entity-List-Aufnahmen und Auflagen für den Verkauf von Spitzenchips, stimmt Lithografiekontrollen mit verbündeten Regierungen ab und verfolgt Umgehungen — darunter ein Strafverfahren wegen der Umleitung von Nvidia-Chips im Milliardenwert und ein Vergleich mit einem US-Anlagenbauer wegen unrechtmäßiger Ausfuhren. Pekings Reaktion geht über Protest hinaus: Es verweigerte die Freigabe für H200-Einfuhren, welche die US-Behörden zur Ausfuhr freigegeben hatten, knüpfte Genehmigungen an eigene Bedingungen und trieb die heimische Substitution voran. Chinesische Firmen beschafften US-Chipwerkzeuge zudem über südostasiatische Zwischenhändler. Die Berichterstattung verläuft entlang getrennter Linien: westliche, verbündete und Fachmedien behandeln die Kontrollen als Schutz eines militärisch unmittelbar relevanten Vorsprungs, während chinesische Staatsmedien sie als Unterdrückung legitimer Entwicklung darstellen, die globale Chip-Lieferketten stört und an den eigenen Zielen scheitert.',
  updated_at = now()
WHERE id = 'us_china_tech_restrictions';

-- ============================ ATOMIC: AI primacy ============================
UPDATE friction_nodes SET
  name_de = 'Wettlauf um die Vorherrschaft bei künstlicher Intelligenz',
  description_en = 'The competition between US and Chinese firms and governments for capability and market position in artificial intelligence: model performance and training cost, access to compute, competition for users in each other''s markets, defence blacklisting of Chinese technology companies and the litigation it draws, disputes over model access and distillation, restrictions on cross-border acquisition of AI developers, and an intergovernmental dialogue on artificial intelligence agreed between the two governments.',
  description_de = 'Der Wettbewerb zwischen US-amerikanischen und chinesischen Unternehmen und Regierungen um Leistungsfähigkeit und Marktposition bei künstlicher Intelligenz: Modellleistung und Trainingskosten, Zugang zu Rechenkapazität, Wettbewerb um Nutzer in den jeweiligen Märkten, die Aufnahme chinesischer Technologieunternehmen auf Verteidigungslisten und die daraus folgenden Klagen, Streit über Modellzugriff und Distillation, Beschränkungen für grenzüberschreitende Übernahmen von KI-Entwicklern sowie ein zwischen beiden Regierungen vereinbarter Dialog zur künstlichen Intelligenz.',
  editorial_summary_en = 'Artificial intelligence is the strand where the capability gap has narrowed most visibly. Chinese models reached the frontier at lower training cost, Chinese firms began competing for users inside the US market, and both governments treated the field as strategic. The contest is conducted with every available commercial and regulatory instrument: the US Defense Department listed Chinese technology companies as supporting the Chinese military, drawing lawsuits from the firms named; a US AI developer accused a Chinese counterpart of obtaining illicit access to its models, and the Chinese firm restricted its employees from using the US developer''s tools in turn; Washington issued warnings over model distillation; and Beijing blocked a US acquisition of a Chinese AI developer and tightened rules on outbound investment. Alongside the rivalry the two governments agreed to open an intergovernmental dialogue on artificial intelligence. Coverage divides on disjoint lines: Western, allied and specialist outlets describe a close race in which both sides use hard tactics, while Chinese state media attribute Chinese progress to domestic research investment and characterise US accusations and blacklisting as attempts to suppress a competitor.',
  editorial_summary_de = 'Künstliche Intelligenz ist der Strang, in dem sich der Leistungsabstand am sichtbarsten verringert hat. Chinesische Modelle erreichten die Spitze bei geringeren Trainingskosten, chinesische Firmen begannen im US-Markt um Nutzer zu werben, und beide Regierungen behandelten das Feld als strategisch. Der Wettstreit wird mit allen verfügbaren kommerziellen und regulatorischen Mitteln geführt: Das US-Verteidigungsministerium führte chinesische Technologieunternehmen als Unterstützer des chinesischen Militärs, was Klagen der genannten Firmen nach sich zog; ein US-KI-Entwickler warf einem chinesischen Wettbewerber unzulässigen Zugriff auf seine Modelle vor, woraufhin dieser seinen Mitarbeitern die Nutzung der Werkzeuge des US-Entwicklers untersagte; Washington warnte vor Modell-Distillation; und Peking blockierte eine US-Übernahme eines chinesischen KI-Entwicklers und verschärfte die Regeln für Auslandsinvestitionen. Parallel zur Rivalität vereinbarten beide Regierungen einen zwischenstaatlichen Dialog zur künstlichen Intelligenz. Die Berichterstattung verläuft entlang getrennter Linien: westliche, verbündete und Fachmedien beschreiben ein enges Rennen, in dem beide Seiten harte Mittel einsetzen, während chinesische Staatsmedien den chinesischen Fortschritt heimischer Forschungsinvestition zuschreiben und US-Vorwürfe und Listungen als Versuche der Unterdrückung eines Wettbewerbers darstellen.',
  updated_at = now()
WHERE id = 'us_china_ai_primacy';

-- ============================ ATOMIC: critical minerals ============================
UPDATE friction_nodes SET
  name_de = 'Hebelwirkung kritischer Rohstoffe',
  description_en = 'Dependence on Chinese supply of rare earths and other critical minerals, and the measures taken around it: Chinese export licensing and export-control listings covering rare earths and processed magnet materials, US strategic stockpiling and Defense Department offtake arrangements, critical-minerals agreements between the United States and the European Union and Japan, and support for mining and processing capacity outside China. China holds a dominant share of global refining and magnet production, and a bilateral arrangement on rare-earth supply has been in effect during the period.',
  description_de = 'Die Abhängigkeit von chinesischen Lieferungen Seltener Erden und anderer kritischer Rohstoffe und die Maßnahmen darum herum: chinesische Exportlizenzierung und Exportkontrolllisten für Seltene Erden und verarbeitete Magnetwerkstoffe, strategische Reservehaltung der USA und Abnahmevereinbarungen des Verteidigungsministeriums, Rohstoffabkommen zwischen den Vereinigten Staaten und der Europäischen Union sowie Japan und die Förderung von Förder- und Verarbeitungskapazität außerhalb Chinas. China hält einen dominierenden Anteil an der weltweiten Raffination und Magnetproduktion; eine bilaterale Vereinbarung zur Versorgung mit Seltenen Erden war im Zeitraum in Kraft.',
  editorial_summary_en = 'Critical minerals are the strand where the asymmetry runs the other way. China holds a dominant share of rare-earth mining, refining and magnet production, and has used export licensing as an instrument — including placing two US rare-earth producers on its own export-control list. A bilateral arrangement on rare-earth supply has been in effect, with its extension discussed at the Beijing summit, though Chinese curbs continued to bind in the meantime. The US response is industrial rather than regulatory: a multibillion-dollar strategic stockpile, Defense Department offtake and investment arrangements with non-Chinese producers, and critical-minerals agreements concluded with the European Union and Japan. Third countries with their own deposits, including Brazil, have declined to align exclusively with either side. Coverage divides on disjoint lines: Western, allied and industry outlets treat the dependence as a strategic vulnerability to be engineered away, while Chinese state media present export licensing as lawful regulation of dual-use materials and the allied minerals agreements as exclusive blocs that fragment global trade.',
  editorial_summary_de = 'Bei kritischen Rohstoffen verläuft die Asymmetrie in die andere Richtung. China hält einen dominierenden Anteil an Förderung, Raffination und Magnetproduktion Seltener Erden und hat Exportlizenzierung als Instrument eingesetzt — unter anderem durch die Aufnahme zweier US-Produzenten Seltener Erden auf die eigene Exportkontrollliste. Eine bilaterale Vereinbarung zur Versorgung mit Seltenen Erden war in Kraft, ihre Verlängerung wurde beim Pekinger Gipfel erörtert, während chinesische Beschränkungen zwischenzeitlich weiter wirkten. Die US-Antwort ist industrieller statt regulatorischer Natur: eine milliardenschwere strategische Reserve, Abnahme- und Investitionsvereinbarungen des Verteidigungsministeriums mit nichtchinesischen Produzenten sowie Rohstoffabkommen mit der Europäischen Union und Japan. Drittstaaten mit eigenen Vorkommen, darunter Brasilien, haben eine ausschließliche Bindung an eine der beiden Seiten abgelehnt. Die Berichterstattung verläuft entlang getrennter Linien: westliche, verbündete und Industriemedien behandeln die Abhängigkeit als strategische Verwundbarkeit, die technisch zu überwinden ist, während chinesische Staatsmedien Exportlizenzierung als rechtmäßige Regulierung von Dual-Use-Material und die Rohstoffabkommen der Verbündeten als exklusive Blöcke darstellen, die den Welthandel fragmentieren.',
  updated_at = now()
WHERE id = 'us_china_critical_minerals';

COMMIT;
