-- us_domestic_theater: bilingual completeness fields (§6, 2026-07-20).
--
-- description_* is the neutral, evergreen definition of the terrain: WHAT the
-- node covers, no stance, no dated specifics that rot. editorial_summary_* may
-- reference the current period's substance but still describes the dispute
-- rather than taking a side -- all framing lives in narratives_v2.
--
-- Deliberately absent from every description here: "polarisation", "crackdown",
-- "purge", "backsliding", "authoritarian", "assault on". Those are framings,
-- and each of them appears in narratives_v2 where it belongs.
--
-- UPDATE only, no DELETE.

BEGIN;

UPDATE friction_nodes SET
  description_en = 'Conflicts over the powers, staffing and rules of United States federal institutions, and over how those institutions treat people inside the country. Covers the courts and executive authority, the central bank, election administration, immigration enforcement in the interior, federal personnel, the security of political figures, media regulation, and the investigation of elite networks. Foreign coverage treats these as indicators of American reliability and of the standards Washington applies abroad.',
  description_de = 'Konflikte über die Befugnisse, die Besetzung und die Regeln von US-Bundesinstitutionen sowie darüber, wie diese Institutionen Menschen im Inland behandeln. Umfasst Gerichte und Exekutivgewalt, die Notenbank, die Wahlorganisation, den Einwanderungsvollzug im Landesinneren, Bundespersonal, den Schutz politischer Amtsträger, die Medienaufsicht und die Aufklärung von Elitennetzwerken. Ausländische Berichterstattung sieht darin Indikatoren für die Verlässlichkeit der USA und für die Maßstäbe, die Washington im Ausland anlegt.',
  editorial_summary_en = 'Eight distinct disputes run in parallel here. Interior immigration enforcement and the Epstein files generate the largest volume and the widest non-English coverage. The Supreme Court sits at the centre of several at once, having rejected the birthright-citizenship order and struck down the global tariff authority while upholding removal power elsewhere. A contested Federal Reserve succession, a rolling cycle of cabinet departures, a redistricting and ballot-rules fight ahead of the midterms, repeated security incidents around political figures, and regulatory pressure on broadcasters complete the set.',
  editorial_summary_de = 'Acht eigenständige Auseinandersetzungen laufen hier parallel. Der Einwanderungsvollzug im Landesinneren und die Epstein-Akten erzeugen das größte Volumen und die breiteste fremdsprachige Berichterstattung. Der Supreme Court steht gleich in mehreren im Mittelpunkt: Er wies die Anordnung zum Geburtsortsprinzip zurück und kippte die globale Zollbefugnis, bestätigte andernorts aber die Entlassungsbefugnis. Eine umstrittene Fed-Nachfolge, eine fortlaufende Kette von Kabinettsabgängen, ein Streit um Wahlkreise und Stimmzettelregeln vor den Zwischenwahlen, wiederholte Sicherheitsvorfälle um politische Amtsträger und regulatorischer Druck auf Sender vervollständigen das Bild.',
  updated_at = NOW()
WHERE id = 'us_domestic_theater';

UPDATE friction_nodes SET
  description_en = 'Disputes over how United States elections are administered: the drawing of congressional district boundaries, rules on mail and absentee balloting, voter identification and citizenship-verification requirements, maintenance of voter rolls, and the scope of the Voting Rights Act. Contested through state legislatures and the federal courts.',
  description_de = 'Auseinandersetzungen über die Organisation von Wahlen in den USA: der Zuschnitt von Kongresswahlkreisen, Regeln zur Brief- und Abwesenheitswahl, Ausweis- und Staatsbürgerschaftsnachweise, die Pflege der Wählerverzeichnisse und die Reichweite des Voting Rights Act. Ausgetragen über die Parlamente der Bundesstaaten und die Bundesgerichte.',
  editorial_summary_en = 'A redistricting contest runs across Texas, Florida, California, Virginia, Utah and South Carolina, with both parties redrawing maps and litigating the results. A Supreme Court ruling narrowing the Voting Rights Act reopened map fights in several states. Federal judges blocked a Postal Service order restricting mail balloting; House Republicans advanced a proof-of-citizenship requirement. An FBI raid on an Ohio voting-rights organisation drew attention shortly before the midterms.',
  editorial_summary_de = 'Ein Streit um Wahlkreiszuschnitte zieht sich durch Texas, Florida, Kalifornien, Virginia, Utah und South Carolina, wobei beide Parteien Karten neu zeichnen und die Ergebnisse beklagen. Ein Urteil des Supreme Court zur Einschränkung des Voting Rights Act ließ Kartenstreitigkeiten in mehreren Bundesstaaten neu aufleben. Bundesrichter stoppten eine Anordnung der Post zur Einschränkung der Briefwahl; die Republikaner im Repräsentantenhaus brachten eine Nachweispflicht der Staatsbürgerschaft voran.',
  updated_at = NOW()
WHERE id = 'us_electoral_legitimacy';

UPDATE friction_nodes SET
  description_en = 'Litigation over the reach of United States executive authority and the rulings that decide it: emergency and merits decisions of the Supreme Court, injunctions issued by federal district judges, and appellate review. Covers both decisions constraining the executive and decisions expanding its discretion.',
  description_de = 'Rechtsstreitigkeiten über die Reichweite der US-Exekutivgewalt und die Urteile, die darüber entscheiden: Eil- und Hauptsacheentscheidungen des Supreme Court, einstweilige Verfügungen von Bundesbezirksrichtern und Berufungsverfahren. Umfasst sowohl Entscheidungen, die die Exekutive begrenzen, als auch solche, die ihren Ermessensspielraum erweitern.',
  editorial_summary_en = 'The Court rejected an attempt to limit birthright citizenship and ruled the global tariff order an unlawful use of executive power, prompting a replacement 10% tariff. It blocked the removal of a Federal Reserve governor while upholding removal power over other agencies, and expanded immigration discretion in TPS and southern-border decisions. Lower courts blocked a mail-ballot order and the defunding of public broadcasters.',
  editorial_summary_de = 'Das Gericht wies den Versuch zurück, das Geburtsortsprinzip einzuschränken, und erklärte die globale Zollanordnung für einen unrechtmäßigen Gebrauch der Exekutivgewalt, woraufhin ein pauschaler Zoll von 10 Prozent folgte. Es stoppte die Abberufung einer Fed-Vorständin, bestätigte aber die Entlassungsbefugnis gegenüber anderen Behörden und erweiterte das Ermessen bei TPS- und Grenzentscheidungen. Untergerichte stoppten eine Briefwahlanordnung und die Mittelstreichung für öffentliche Sender.',
  updated_at = NOW()
WHERE id = 'us_judicial_constraint';

UPDATE friction_nodes SET
  description_en = 'Departures, dismissals and replacements among senior United States federal officials: cabinet secretaries, the attorney general, intelligence and law-enforcement leadership, inspectors general and federal prosecutors. Covers both the appointments process and the reasons given for removals.',
  description_de = 'Abgänge, Entlassungen und Neubesetzungen unter hohen US-Bundesbeamten: Kabinettsmitglieder, die Justizministerin, die Führung von Nachrichtendiensten und Strafverfolgung, Generalinspekteure und Bundesstaatsanwälte. Umfasst sowohl das Ernennungsverfahren als auch die genannten Gründe für Abberufungen.',
  editorial_summary_en = 'The attorney general was removed after appearing before the House Oversight Committee on the Epstein files; the homeland security secretary departed following a fatal shooting by an officer in Minneapolis; the director of national intelligence resigned. The FBI dismissed agents who had worked on earlier investigations touching the president. Several posts were filled on a temporary basis pending Senate confirmation.',
  editorial_summary_de = 'Die Justizministerin wurde nach ihrem Auftritt vor dem Kontrollausschuss des Repräsentantenhauses zu den Epstein-Akten abberufen; die Heimatschutzministerin schied nach tödlichen Schüssen eines Beamten in Minneapolis aus; die Koordinatorin der Nachrichtendienste trat zurück. Das FBI entließ Beamte, die an früheren Ermittlungen mit Bezug zum Präsidenten gearbeitet hatten. Mehrere Posten wurden bis zur Bestätigung durch den Senat kommissarisch besetzt.',
  updated_at = NOW()
WHERE id = 'us_executive_loyalty';

UPDATE friction_nodes SET
  description_en = 'The relationship between the United States executive and the Federal Reserve: nomination and confirmation of the chair and governors, the legal limits on removing them, and disputes over the central bank''s autonomy in setting policy. Distinct from routine monetary-policy coverage, which concerns rate decisions rather than institutional control.',
  description_de = 'Das Verhältnis zwischen der US-Exekutive und der Federal Reserve: Nominierung und Bestätigung des Vorsitzes und der Gouverneure, die rechtlichen Grenzen ihrer Abberufung und Streit über die Autonomie der Notenbank bei der Politikgestaltung. Abzugrenzen von der routinemäßigen Geldpolitik-Berichterstattung, die Zinsentscheidungen und nicht institutionelle Kontrolle betrifft.',
  editorial_summary_en = 'Kevin Warsh was nominated to succeed Jerome Powell as chair and cleared the Senate committee stage. An attempt to remove governor Lisa Cook was blocked in court, and a Justice Department referral against Powell was later dropped. Powell served out his term, publicly warning that the institution was undergoing a stress test and that lost credibility would be difficult to restore.',
  editorial_summary_de = 'Kevin Warsh wurde als Nachfolger von Jerome Powell für den Vorsitz nominiert und passierte die Ausschussstufe im Senat. Der Versuch, die Gouverneurin Lisa Cook abzuberufen, wurde gerichtlich gestoppt; eine Anzeige des Justizministeriums gegen Powell wurde später fallengelassen. Powell beendete seine Amtszeit und warnte öffentlich, die Institution durchlaufe einen Stresstest und verlorene Glaubwürdigkeit sei schwer wiederherzustellen.',
  updated_at = NOW()
WHERE id = 'us_fed_independence';

UPDATE friction_nodes SET
  description_en = 'Immigration enforcement conducted inside the United States rather than at the border: arrests and removals by Immigration and Customs Enforcement, detention facilities and conditions within them, judicial review of individual cases, and disputes between federal agencies and state or city governments over cooperation. Border, cartel and bilateral trade questions belong to the US-Mexico theater.',
  description_de = 'Einwanderungsvollzug innerhalb der USA statt an der Grenze: Festnahmen und Abschiebungen durch die Einwanderungsbehörde ICE, Hafteinrichtungen und die Bedingungen darin, gerichtliche Überprüfung von Einzelfällen sowie Streit zwischen Bundesbehörden und Bundesstaaten oder Städten über die Zusammenarbeit. Grenz-, Kartell- und bilaterale Handelsfragen gehören zum US-Mexiko-Feld.',
  editorial_summary_en = 'Congress approved a large multi-year funding increase for the agency. Deaths in custody rose and a measles outbreak was recorded at a Texas facility; judges ordered individual releases, including of a five-year-old and an 86-year-old French national. Agents were deployed to airports during a partial government shutdown, and their planned presence at stadiums during the World Cup drew majority public opposition in polling. State and city governments clashed with federal authorities over cooperation, and a county charged an officer over a non-fatal shooting.',
  editorial_summary_de = 'Der Kongress bewilligte eine große mehrjährige Mittelaufstockung für die Behörde. Todesfälle in Gewahrsam nahmen zu, in einer Einrichtung in Texas wurden Masern festgestellt; Richter ordneten Freilassungen an, darunter die eines Fünfjährigen und einer 86-jährigen Französin. Beamte wurden während eines teilweisen Regierungsstillstands an Flughäfen eingesetzt, ihre geplante Präsenz in Stadien während der WM stieß in Umfragen mehrheitlich auf Ablehnung. Bundesstaaten und Städte gerieten mit Bundesbehörden über die Zusammenarbeit aneinander.',
  updated_at = NOW()
WHERE id = 'us_interior_immigration_enforcement';

UPDATE friction_nodes SET
  description_en = 'The investigation and disclosure of records concerning Jeffrey Epstein and the people connected to him: Justice Department file releases, congressional depositions and contempt proceedings, civil litigation and settlements, and parallel inquiries opened by other governments. Centred on United States court and congressional process, with subjects in several countries.',
  description_de = 'Ermittlungen und Aktenfreigaben zu Jeffrey Epstein und den mit ihm verbundenen Personen: Freigaben des Justizministeriums, Vernehmungen und Missachtungsverfahren im Kongress, Zivilklagen und Vergleiche sowie parallele Untersuchungen anderer Regierungen. Zentriert auf US-Gerichts- und Kongressverfahren, mit Betroffenen in mehreren Ländern.',
  editorial_summary_en = 'The Justice Department released successive batches of files and video. Bill and Hillary Clinton testified and later faced contempt resolutions; Ghislaine Maxwell invoked the Fifth Amendment before the House Oversight Committee; the attorney general was subpoenaed and subsequently removed. Consequences reached well beyond the United States: a British former ambassador left the Labour Party and the prime minister''s chief of staff resigned, a Goldman Sachs lawyer stepped down, French prosecutors searched premises linked to a former minister, and Norway and Poland opened inquiries.',
  editorial_summary_de = 'Das Justizministerium gab nacheinander Aktenpakete und Videomaterial frei. Bill und Hillary Clinton sagten aus und sahen sich später Missachtungsanträgen gegenüber; Ghislaine Maxwell verweigerte vor dem Kontrollausschuss die Aussage; die Justizministerin wurde vorgeladen und anschließend abberufen. Die Folgen reichten weit über die USA hinaus: Ein früherer britischer Botschafter verließ die Labour-Partei und der Stabschef des Premierministers trat zurück, eine Anwältin von Goldman Sachs schied aus, französische Staatsanwälte durchsuchten Räume mit Bezug zu einem Ex-Minister, und Norwegen und Polen leiteten Untersuchungen ein.',
  updated_at = NOW()
WHERE id = 'us_epstein_elite_network';

UPDATE friction_nodes SET
  description_en = 'Attacks, attempted attacks and threats directed at United States political figures and institutions, and the protective and judicial response: Secret Service operations, prosecutions of suspects, security arrangements for officials and judges, and disclosed plots against political events.',
  description_de = 'Angriffe, Angriffsversuche und Drohungen gegen politische Amtsträger und Institutionen in den USA sowie die Schutz- und Justizreaktion: Einsätze des Secret Service, Strafverfahren gegen Verdächtige, Sicherheitsvorkehrungen für Amtsträger und Richter sowie aufgedeckte Anschlagspläne auf politische Veranstaltungen.',
  editorial_summary_en = 'Shots were fired at the White House Correspondents'' Dinner, from which the president was evacuated; a suspect was charged and pleaded not guilty, and officials later said the president was the likely target. A separate armed man was killed entering the Mar-a-Lago perimeter, gunfire was exchanged near the White House and near the vice-president''s motorcade, and the FBI reported foiling a drone-and-sniper plot against an event. A member of Congress was attacked at a town hall in Minneapolis, and a Supreme Court justice described heightened security and threats to the judiciary.',
  editorial_summary_de = 'Beim Korrespondentendinner im Weißen Haus fielen Schüsse, der Präsident wurde evakuiert; ein Verdächtiger wurde angeklagt und bekannte sich nicht schuldig, Behörden nannten den Präsidenten später als wahrscheinliches Ziel. Ein bewaffneter Mann wurde beim Eindringen auf das Gelände von Mar-a-Lago erschossen, nahe dem Weißen Haus und dem Konvoi des Vizepräsidenten fielen Schüsse, und das FBI vereitelte nach eigenen Angaben einen Anschlagsplan mit Drohnen und Scharfschützen. Ein Kongressmitglied wurde bei einer Bürgerversammlung in Minneapolis angegriffen.',
  updated_at = NOW()
WHERE id = 'us_political_violence';

UPDATE friction_nodes SET
  description_en = 'The relationship between United States federal authority and news organisations: Federal Communications Commission action on broadcast licences, funding decisions affecting public broadcasters, press access to government departments, defamation litigation brought against news outlets, and First Amendment rulings arising from these.',
  description_de = 'Das Verhältnis zwischen US-Bundesbehörden und Nachrichtenorganisationen: Maßnahmen der Rundfunkaufsicht FCC zu Sendelizenzen, Finanzierungsentscheidungen für öffentliche Sender, Pressezugang zu Ministerien, Verleumdungsklagen gegen Medien und die daraus folgenden Urteile zum Ersten Verfassungszusatz.',
  editorial_summary_en = 'The FCC opened licence reviews at stations carrying a network programme after a presenter''s joke about the first lady, and the network''s lawyers accused the regulator of acting for political reasons. A federal judge blocked an order ending funding for NPR and PBS on First Amendment grounds. The Pentagon moved to restrict press access again after losing in court, a $10 billion defamation suit was refiled against a newspaper, and the Committee to Protect Journalists and foreign outlets recorded visa revocations affecting a Costa Rican newspaper''s executives.',
  editorial_summary_de = 'Die FCC leitete Lizenzüberprüfungen bei Sendern ein, die ein Netzwerkprogramm ausstrahlen, nachdem ein Moderator einen Witz über die First Lady gemacht hatte; die Anwälte des Senders warfen der Aufsicht politisch motiviertes Handeln vor. Ein Bundesrichter stoppte unter Berufung auf den Ersten Verfassungszusatz die Streichung der Mittel für NPR und PBS. Das Pentagon schränkte den Pressezugang nach einer Niederlage vor Gericht erneut ein, eine Verleumdungsklage über 10 Milliarden Dollar gegen eine Zeitung wurde neu eingereicht.',
  updated_at = NOW()
WHERE id = 'us_press_freedom';

COMMIT;
