-- Capital / representative map point per centroid ([lon, lat] GeoJSON).
-- Used by the FN map to draw conflict-to-participant spokes and
-- capital-to-capital arcs for global rivalries. Regional groupings get a
-- representative capital; diffuse non-state actors get none.

ALTER TABLE centroids_v3 ADD COLUMN IF NOT EXISTS map_point jsonb;

UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[29.36,-3.38]}'   WHERE id = 'AFRICA-BURUNDI';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[43.15,11.59]}'   WHERE id = 'AFRICA-DJIBOUTI';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[15.27,-4.32]}'   WHERE id = 'AFRICA-DRC';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[38.93,15.34]}'   WHERE id = 'AFRICA-ERITREA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[38.75,9.02]}'    WHERE id = 'AFRICA-ETHIOPIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[36.82,-1.29]}'   WHERE id = 'AFRICA-KENYA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[7.49,9.06]}'     WHERE id = 'AFRICA-NIGERIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[30.06,-1.94]}'   WHERE id = 'AFRICA-RWANDA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[2.11,13.51]}'    WHERE id = 'AFRICA-SAHEL';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[45.32,2.05]}'    WHERE id = 'AFRICA-SOMALIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[32.58,0.35]}'    WHERE id = 'AFRICA-UGANDA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-58.38,-34.6]}'  WHERE id = 'AMERICAS-ARGENTINA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-68.15,-16.5]}'  WHERE id = 'AMERICAS-BOLIVIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-47.88,-15.79]}' WHERE id = 'AMERICAS-BRAZIL';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-75.7,45.42]}'   WHERE id = 'AMERICAS-CANADA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-90.51,14.63]}'  WHERE id = 'AMERICAS-CENTRAL';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-70.65,-33.45]}' WHERE id = 'AMERICAS-CHILE';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-74.07,4.71]}'   WHERE id = 'AMERICAS-COLOMBIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-82.37,23.11]}'  WHERE id = 'AMERICAS-CUBA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-58.16,6.8]}'    WHERE id = 'AMERICAS-GUYANA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-99.13,19.43]}'  WHERE id = 'AMERICAS-MEXICO';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-77.03,-12.05]}' WHERE id = 'AMERICAS-PERU';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-77.04,38.9]}'   WHERE id = 'AMERICAS-USA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-66.9,10.49]}'   WHERE id = 'AMERICAS-VENEZUELA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[116.4,39.9]}'    WHERE id = 'ASIA-CHINA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[85.32,27.72]}'   WHERE id = 'ASIA-HIMALAYA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[77.21,28.61]}'   WHERE id = 'ASIA-INDIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[139.69,35.69]}'  WHERE id = 'ASIA-JAPAN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[125.75,39.03]}'  WHERE id = 'ASIA-NORKOREA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[73.06,33.69]}'   WHERE id = 'ASIA-PAKISTAN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[100.5,13.76]}'   WHERE id = 'ASIA-SOUTHEAST';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[126.98,37.57]}'  WHERE id = 'ASIA-SOUTHKOREA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[121.56,25.03]}'  WHERE id = 'ASIA-TAIWAN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[44.51,40.18]}'   WHERE id = 'EUROPE-ARMENIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[49.87,40.41]}'   WHERE id = 'EUROPE-AZERBAIJAN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[20.46,44.79]}'   WHERE id = 'EUROPE-BALKANS';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[24.11,56.95]}'   WHERE id = 'EUROPE-BALTIC';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[2.35,48.86]}'    WHERE id = 'EUROPE-FRANCE';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[13.41,52.52]}'   WHERE id = 'EUROPE-GERMANY';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-51.72,64.18]}'  WHERE id = 'EUROPE-GREENLAND';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[19.04,47.5]}'    WHERE id = 'EUROPE-HUNGARY';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[18.07,59.33]}'   WHERE id = 'EUROPE-NORDIC';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[37.62,55.76]}'   WHERE id = 'EUROPE-RUSSIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[17.11,48.15]}'   WHERE id = 'EUROPE-SLOVAKIA';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[12.5,41.9]}'     WHERE id = 'EUROPE-SOUTH';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[-0.13,51.51]}'   WHERE id = 'EUROPE-UK';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[30.52,50.45]}'   WHERE id = 'EUROPE-UKRAINE';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[21.01,52.23]}'   WHERE id = 'EUROPE-VISEGRAD';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[31.24,30.04]}'   WHERE id = 'MIDEAST-EGYPT';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[54.37,24.45]}'   WHERE id = 'MIDEAST-GULF';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[51.39,35.69]}'   WHERE id = 'MIDEAST-IRAN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[44.36,33.32]}'   WHERE id = 'MIDEAST-IRAQ';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[35.21,31.77]}'   WHERE id = 'MIDEAST-ISRAEL';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[35.5,33.89]}'    WHERE id = 'MIDEAST-LEVANT';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[35.2,31.9]}'     WHERE id = 'MIDEAST-PALESTINE';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[46.68,24.71]}'   WHERE id = 'MIDEAST-SAUDI';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[32.85,39.93]}'   WHERE id = 'MIDEAST-TURKEY';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[44.21,15.35]}'   WHERE id = 'MIDEAST-YEMEN';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[4.35,50.85]}'    WHERE id = 'NON-STATE-EU';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[4.4,50.88]}'     WHERE id = 'NON-STATE-NATO';
UPDATE centroids_v3 SET map_point = '{"type":"Point","coordinates":[149.13,-35.28]}' WHERE id = 'OCEANIA-AUSTRALIA';
