-- us_canada_theater completeness fields (FN_THEATER_BUILD_SPEC §0a step 8, §6).
-- description_en/_de + editorial_summary_en/_de for the theater and all 3 atomics.
-- Neutral, fact-based, evergreen per house rule: no framing, no motive attribution,
-- no temporality. Framing lives only in narratives_v2. name_en/name_de were set in
-- the 01_structure migration.
SET client_encoding TO 'UTF8';

UPDATE friction_nodes SET
  description_en = 'The confrontation between the United States and Canada across trade, sovereignty and the internal cohesion of the Canadian federation. Three axes run through it: tariffs and the renegotiation of the trilateral trade agreement; rhetoric about annexation and statehood alongside disputes over jointly financed border infrastructure; and a secession movement in Alberta whose organisers have held contacts with American officials. The two economies are deeply integrated and the two states are treaty allies, which is what makes the dispute distinct from an ordinary trade conflict.',
  description_de = 'Die Konfrontation zwischen den USA und Kanada in den Bereichen Handel, Souveränität und innerer Zusammenhalt des kanadischen Bundesstaates. Drei Achsen durchziehen sie: Zölle und die Neuverhandlung des trilateralen Handelsabkommens; Rhetorik über Annexion und Staatlichkeit sowie Streit über gemeinsam finanzierte Grenzinfrastruktur; und eine Sezessionsbewegung in Alberta, deren Organisatoren Kontakte zu amerikanischen Amtsträgern unterhielten. Beide Volkswirtschaften sind eng verflochten und beide Staaten sind Bündnispartner — das unterscheidet den Streit von einem gewöhnlichen Handelskonflikt.',
  editorial_summary_en = 'Canada and the United States share the world''s longest land border, a trilateral trade agreement, a joint air-defence command and roughly three-quarters of Canadian exports. That integration is the backdrop against which a tariff campaign, public discussion of annexation and statehood, a threat to withhold a jointly financed border crossing, and the withdrawal of a diplomatic invitation have moved the relationship onto contested ground. The Canadian response has run across party lines and has extended to consumer boycotts, domestic-procurement campaigns and trade openings toward India, China and Asian markets. A third axis is domestic: a referendum push in Alberta, a landlocked province holding most of Canada''s oil reserves, whose organisers have met American officials — drawing objections from the federal government, provincial premiers, First Nations treaty holders and the courts. Russian, Chinese and Iranian state media cover the dispute as evidence of Western fracture rather than taking either side.',
  editorial_summary_de = 'Kanada und die USA teilen die längste Landgrenze der Welt, ein trilaterales Handelsabkommen, ein gemeinsames Luftverteidigungskommando und rund drei Viertel der kanadischen Ausfuhren. Vor diesem Hintergrund haben eine Zollkampagne, öffentliche Debatten über Annexion und Staatlichkeit, die Drohung, einen gemeinsam finanzierten Grenzübergang zurückzuhalten, und die Rücknahme einer diplomatischen Einladung die Beziehung auf strittiges Terrain verschoben. Die kanadische Reaktion verlief parteiübergreifend und reichte bis zu Verbraucherboykotten, Kampagnen für heimische Beschaffung und Handelsöffnungen nach Indien, China und Asien. Eine dritte Achse ist innenpolitisch: ein Referendumsvorstoß in Alberta, einer Binnenprovinz mit dem Großteil der kanadischen Ölreserven, deren Organisatoren amerikanische Amtsträger trafen — mit Einwänden der Bundesregierung, von Provinzpremiers, Vertragspartnern der First Nations und der Gerichte. Russische, chinesische und iranische Staatsmedien behandeln den Streit als Beleg westlicher Zerrissenheit, ohne Partei zu ergreifen.',
  updated_at = NOW()
WHERE id = 'us_canada_theater';

UPDATE friction_nodes SET
  description_en = 'The tariff and trade-agreement dispute between the United States and Canada. It covers duties imposed and threatened on Canadian goods, the reopening of the trilateral trade agreement, sector-specific measures on steel, aluminium, softwood lumber, aircraft and vehicles, Canadian counter-tariffs and their extension, congressional votes on the tariff authority, and Canada''s parallel pursuit of trade agreements with India, China and Asian partners.',
  description_de = 'Der Zoll- und Handelsabkommensstreit zwischen den USA und Kanada. Er umfasst verhängte und angedrohte Abgaben auf kanadische Waren, die Wiedereröffnung des trilateralen Handelsabkommens, sektorspezifische Maßnahmen bei Stahl, Aluminium, Nadelholz, Flugzeugen und Fahrzeugen, kanadische Gegenzölle und deren Verlängerung, Abstimmungen im Kongress über die Zollbefugnis sowie Kanadas parallele Bemühungen um Handelsabkommen mit Indien, China und asiatischen Partnern.',
  editorial_summary_en = 'Trade is the largest and most continuous strand of the US-Canada confrontation. Duties have been imposed or threatened across steel and aluminium, softwood lumber, vehicles and aircraft, with an aircraft decertification threat attached to a proposed fifty per cent rate. Canada has extended counter-measures and both governments have moved in and out of negotiation, while the trilateral agreement covering the three North American economies has been reopened for renegotiation, at points with Mexico and the United States meeting without Canada. The dispute has drawn opposition inside the United States as well, including a House vote to overturn the tariffs with cross-party support, and it has pushed Canada toward trade agreements with India, China and Asian markets — which has in turn drawn further tariff threats.',
  editorial_summary_de = 'Der Handel ist der größte und durchgängigste Strang der Konfrontation zwischen den USA und Kanada. Abgaben wurden auf Stahl und Aluminium, Nadelholz, Fahrzeuge und Flugzeuge verhängt oder angedroht, verbunden mit der Drohung, kanadischen Flugzeugen die Zulassung zu entziehen, bei einem geplanten Satz von fünfzig Prozent. Kanada hat Gegenmaßnahmen verlängert, beide Regierungen traten wiederholt in Verhandlungen ein und aus, und das trilaterale Abkommen der drei nordamerikanischen Volkswirtschaften wurde zur Neuverhandlung geöffnet — zeitweise trafen sich Mexiko und die USA ohne Kanada. Der Streit stieß auch innerhalb der USA auf Widerstand, darunter ein Votum des Repräsentantenhauses zur Aufhebung der Zölle mit parteiübergreifender Unterstützung. Er hat Kanada zu Handelsabkommen mit Indien, China und asiatischen Märkten gedrängt, was wiederum weitere Zolldrohungen nach sich zog.',
  updated_at = NOW()
WHERE id = 'us_canada_trade_coercion';

UPDATE friction_nodes SET
  description_en = 'The dispute over Canadian sovereignty in relation to the United States. It covers public statements about annexation and Canada becoming a US state, the threat to withhold opening of the Gordie Howe International Bridge between Detroit and Windsor, the withdrawal of Canada''s invitation to the Board of Peace, demands relating to the Golden Dome missile-defence programme, and the Canadian response — including consumer boycotts, domestic-purchasing campaigns and statements on the post-war international order.',
  description_de = 'Der Streit um die kanadische Souveränität im Verhältnis zu den USA. Er umfasst öffentliche Äußerungen über eine Annexion und einen Beitritt Kanadas als US-Bundesstaat, die Drohung, die Eröffnung der Gordie-Howe-Brücke zwischen Detroit und Windsor zurückzuhalten, die Rücknahme der kanadischen Einladung zum Board of Peace, Forderungen im Zusammenhang mit dem Raketenabwehrprogramm Golden Dome sowie die kanadische Reaktion — darunter Verbraucherboykotte, Kampagnen für heimische Käufe und Äußerungen zur internationalen Nachkriegsordnung.',
  editorial_summary_en = 'Alongside the tariff dispute runs a distinct argument about status. Public discussion of annexation and of Canada as a fifty-first state has been accompanied by concrete instruments: a threat to keep closed the Gordie Howe International Bridge, a crossing Canada financed, and the withdrawal of the Canadian prime minister''s invitation to the Board of Peace following a speech at Davos on the post-war order. Demands relating to cost-sharing for the Golden Dome missile-defence programme run alongside them. The Canadian response has been cross-party and has extended beyond government to consumer boycotts and domestic-purchasing campaigns, with polling showing the confrontation consolidating rather than dividing Canadian opinion. Coverage from Russian and Chinese state outlets treats the annexation discussion as a case of expansionism within the Americas rather than endorsing either side.',
  editorial_summary_de = 'Neben dem Zollstreit verläuft eine eigene Auseinandersetzung über den Status. Öffentliche Debatten über eine Annexion und über Kanada als einundfünfzigsten Bundesstaat gingen mit konkreten Instrumenten einher: der Drohung, die Gordie-Howe-Brücke geschlossen zu halten — einen von Kanada finanzierten Übergang — und der Rücknahme der Einladung des kanadischen Premierministers zum Board of Peace nach einer Rede in Davos über die Nachkriegsordnung. Hinzu kommen Forderungen zur Kostenbeteiligung am Raketenabwehrprogramm Golden Dome. Die kanadische Reaktion war parteiübergreifend und reichte über die Regierung hinaus bis zu Verbraucherboykotten und Kampagnen für heimische Käufe; Umfragen zeigen, dass die Konfrontation die kanadische Öffentlichkeit eher zusammenführt als spaltet. Russische und chinesische Staatsmedien behandeln die Annexionsdebatte als Fall von Expansionismus in Amerika, ohne eine der beiden Seiten zu unterstützen.',
  updated_at = NOW()
WHERE id = 'canada_sovereignty_pressure';

UPDATE friction_nodes SET
  description_en = 'The secession movement in the Canadian province of Alberta and its contacts with the United States. It covers the petition and signature drive for an independence referendum, the provincial government''s decision to put a separation question to a vote, court challenges to the referendum, opposition from the federal government, other provinces, former prime ministers and First Nations treaty holders, and reported meetings between separatist organisers and American officials along with the resulting foreign-interference inquiries.',
  description_de = 'Die Sezessionsbewegung in der kanadischen Provinz Alberta und ihre Kontakte in die USA. Sie umfasst die Petitions- und Unterschriftenkampagne für ein Unabhängigkeitsreferendum, die Entscheidung der Provinzregierung, eine Abspaltungsfrage zur Abstimmung zu stellen, gerichtliche Anfechtungen des Referendums, den Widerstand der Bundesregierung, anderer Provinzen, früherer Premierminister und der Vertragspartner der First Nations sowie berichtete Treffen zwischen separatistischen Organisatoren und amerikanischen Amtsträgern und die daraus folgenden Untersuchungen zu ausländischer Einflussnahme.',
  editorial_summary_en = 'Alberta holds most of Canada''s oil reserves, has no coastline, and depends on federal decisions over pipelines, environmental rules and fiscal transfers. A separatist organisation has gathered signatures to trigger a referendum on leaving Canada, and the provincial government has moved to put a separation question on a ballot; the courts have at points quashed the bid, and Elections Alberta has sought disclosure of the group''s finances following a dispute over access to the electors list. Opposition has come from the federal government, other provincial premiers, two former prime ministers and First Nations leaders who hold treaty rights across the province. What connects the movement to the wider theater is the reported contact between its organisers and officials of the US administration, which prompted federal statements on respecting Canadian sovereignty, accusations of treason from another premier, and inquiries into foreign interference that found no evidence of it.',
  editorial_summary_de = 'Alberta verfügt über den Großteil der kanadischen Ölreserven, hat keine Küste und ist auf Bundesentscheidungen zu Pipelines, Umweltauflagen und Finanzausgleich angewiesen. Eine separatistische Organisation hat Unterschriften gesammelt, um ein Referendum über den Austritt aus Kanada auszulösen, und die Provinzregierung hat Schritte unternommen, eine Abspaltungsfrage auf einen Stimmzettel zu setzen; Gerichte haben den Vorstoß zeitweise gekippt, und Elections Alberta verlangte Offenlegung der Finanzen der Gruppe nach einem Streit über den Zugriff auf das Wählerverzeichnis. Widerstand kam von der Bundesregierung, anderen Provinzpremiers, zwei früheren Premierministern und Vertretern der First Nations, die provinzweit Vertragsrechte halten. Mit dem übergeordneten Schauplatz verbindet die Bewegung der berichtete Kontakt ihrer Organisatoren zu Amtsträgern der US-Regierung — er führte zu Erklärungen des Bundes zur Achtung der kanadischen Souveränität, zu Landesverratsvorwürfen eines anderen Premiers und zu Untersuchungen wegen ausländischer Einflussnahme, die keine Belege dafür fanden.',
  updated_at = NOW()
WHERE id = 'alberta_separatism_us_ties';
