-- eu_cohesion_theater — Phase 2 completeness fields (FN_THEATER_BUILD_SPEC §6).
-- name_de + description_en/_de + editorial_summary_en/_de for the theater and its
-- 6 active atomics. Prose is neutral, factual, evergreen: it names the phenomenon
-- and describes how coverage divides (attributed), without the FN itself taking a
-- stance or attributing motive. Framing lives in narratives_v2, not here.
-- (feedback_fn_descriptions_neutral)
SET client_encoding TO 'UTF8';

-- ============================ THEATER ============================
UPDATE friction_nodes SET
  name_de = 'Politische Fragmentierung Europas',
  description_en = 'The contest over the European Union''s internal cohesion and the balance of authority between its institutions and its member states. It runs along several axes: rule-of-law and budget-conditionality disputes between Brussels and national governments; the division over migration and asylum policy; the realignment of Europe''s political right and the debate over cooperation with national-conservative parties; and domestic polarisation within Germany, France and Hungary. The friction is internal to the Union, distinct from its disputes with the United States, with Russia, or over Ukraine, which are covered in separate theaters.',
  description_de = 'Der Streit um den inneren Zusammenhalt der Europäischen Union und das Kräfteverhältnis zwischen ihren Institutionen und ihren Mitgliedstaaten. Er verläuft entlang mehrerer Achsen: Konflikte um Rechtsstaatlichkeit und die Konditionalität des Haushalts zwischen Brüssel und den nationalen Regierungen; die Spaltung über Migrations- und Asylpolitik; die Neuordnung der europäischen Rechten und die Debatte über die Zusammenarbeit mit nationalkonservativen Parteien; sowie die innenpolitische Polarisierung in Deutschland, Frankreich und Ungarn. Die Friktion ist unionsintern und damit getrennt von den Auseinandersetzungen mit den Vereinigten Staaten, mit Russland oder um die Ukraine, die in eigenen Theatern behandelt werden.',
  editorial_summary_en = 'The European Union''s internal cohesion is contested on several fronts at once. Brussels and national governments clash over rule-of-law conditionality and the next multiannual budget; member states divide over migration and asylum, from Spain''s mass regularisation to Italy''s offshore processing in Albania to the delayed entry-exit border system; Europe''s political right is reordering itself, as the European People''s Party debates cooperation with the Conservatives and Reformists and Patriots for Europe groups and the long-standing "cordon sanitaire" is tested; and domestic politics polarise inside the largest member states, with the AfD in Germany, the Rassemblement National in France and a change of government in Hungary. Coverage is itself divided: national-conservative and sovereigntist outlets frame Brussels as overreaching and the exclusion of insurgent parties as anti-democratic, mainstream liberal outlets frame the same movements as a threat to the rule of law and EU unity, and Russian and Chinese state media amplify every rift as evidence of Western decline. The disputes are internal to the Union; its external frictions with Washington, Moscow and over Ukraine are treated elsewhere.',
  editorial_summary_de = 'Der innere Zusammenhalt der Europäischen Union ist an mehreren Fronten zugleich umstritten. Brüssel und die nationalen Regierungen streiten über die Rechtsstaatlichkeits-Konditionalität und den nächsten mehrjährigen Haushalt; die Mitgliedstaaten sind in der Migrations- und Asylfrage gespalten, von Spaniens Massenregularisierung über Italiens ausgelagerte Verfahren in Albanien bis zum verzögerten Ein- und Ausreisesystem an den Grenzen; die europäische Rechte ordnet sich neu, während die Europäische Volkspartei über die Zusammenarbeit mit den Fraktionen der Konservativen und Reformer sowie der Patrioten für Europa debattiert und der langjährige „Cordon sanitaire" auf die Probe gestellt wird; und die Innenpolitik der größten Mitgliedstaaten polarisiert sich, mit der AfD in Deutschland, dem Rassemblement National in Frankreich und einem Regierungswechsel in Ungarn. Die Berichterstattung ist selbst geteilt: nationalkonservative und souveränistische Medien deuten Brüssel als übergriffig und den Ausschluss aufstrebender Parteien als undemokratisch, liberale Mainstream-Medien deuten dieselben Bewegungen als Gefahr für Rechtsstaat und EU-Einheit, und russische und chinesische Staatsmedien verstärken jeden Riss als Beleg westlichen Niedergangs. Die Konflikte sind unionsintern; die äußeren Friktionen mit Washington, Moskau und um die Ukraine werden andernorts behandelt.',
  updated_at = NOW()
WHERE id = 'eu_cohesion_theater';

-- ============================ hungary_rule_of_law ============================
UPDATE friction_nodes SET
  name_en = 'Hungary, rule of law and the EU',
  name_de = 'Ungarn, Rechtsstaatlichkeit und die EU',
  description_en = 'The dispute over rule of law, EU funds and institutional power centred on Hungary. It spans the conditionality mechanism under which the European Commission has withheld cohesion and recovery money over concerns about judicial independence, media pluralism, public procurement and civil society, and the domestic contest over those same institutions following the change of government that ended Viktor Orban''s tenure. Recurring flashpoints include frozen EU funds, Article 7 proceedings, the constitutional and presidential order, and Hungary''s use of its vote in the European Council.',
  description_de = 'Die Auseinandersetzung um Rechtsstaatlichkeit, EU-Mittel und institutionelle Macht mit Schwerpunkt Ungarn. Sie umfasst den Konditionalitätsmechanismus, unter dem die Europäische Kommission Kohäsions- und Aufbaugelder wegen Bedenken zu richterlicher Unabhängigkeit, Medienvielfalt, öffentlicher Auftragsvergabe und Zivilgesellschaft zurückgehalten hat, sowie den innenpolitischen Streit um eben diese Institutionen nach dem Regierungswechsel, der die Amtszeit von Viktor Orban beendete. Wiederkehrende Brennpunkte sind eingefrorene EU-Mittel, Verfahren nach Artikel 7, die verfassungs- und präsidialrechtliche Ordnung sowie Ungarns Nutzung seiner Stimme im Europäischen Rat.',
  editorial_summary_en = 'Hungary has been the sharpest test of the European Union''s rule-of-law tools. For years the Commission withheld cohesion and recovery funds under the conditionality mechanism, citing judicial independence, media pluralism, public procurement and the treatment of civil society and academia, while Budapest countered that Brussels was punishing a democratically elected government and infringing national sovereignty. The change of government that ended Viktor Orban''s tenure reopened the same questions from the inside, as the new administration moves against institutions, foundations and appointments inherited from the previous era and contests the presidency and constitutional order. Coverage divides between outlets that treat the conditionality fight as a necessary defence of shared European standards and those that read it, and the domestic reckoning that followed, as political score-settling; Russian state media frame the episode as proof of Brussels'' coercion of member states. Hungary''s separate use of its European Council vote on Ukraine is covered in the Ukraine theater.',
  editorial_summary_de = 'Ungarn war der schärfste Test für die Rechtsstaatlichkeits-Instrumente der Europäischen Union. Jahrelang hielt die Kommission unter dem Konditionalitätsmechanismus Kohäsions- und Aufbaumittel zurück und verwies auf richterliche Unabhängigkeit, Medienvielfalt, öffentliche Auftragsvergabe sowie den Umgang mit Zivilgesellschaft und Wissenschaft, während Budapest entgegnete, Brüssel bestrafe eine demokratisch gewählte Regierung und verletze die nationale Souveränität. Der Regierungswechsel, der die Amtszeit von Viktor Orban beendete, öffnete dieselben Fragen von innen, als die neue Regierung gegen Institutionen, Stiftungen und Personalentscheidungen der Vorgängerära vorgeht und die Präsidentschaft sowie die Verfassungsordnung in Frage stellt. Die Berichterstattung teilt sich zwischen Medien, die den Konditionalitätsstreit als notwendige Verteidigung gemeinsamer europäischer Standards deuten, und solchen, die ihn und die folgende innenpolitische Abrechnung als politische Vergeltung lesen; russische Staatsmedien rahmen die Episode als Beleg für Brüssels Zwang gegenüber den Mitgliedstaaten. Ungarns gesonderte Nutzung seiner Stimme im Europäischen Rat zur Ukraine wird im Ukraine-Theater behandelt.',
  updated_at = NOW()
WHERE id = 'hungary_rule_of_law';

-- ============================ afd_and_german_polarisation ============================
UPDATE friction_nodes SET
  name_en = 'AfD and German political polarisation',
  name_de = 'AfD und die politische Polarisierung Deutschlands',
  description_en = 'The domestic conflict in Germany over the Alternative für Deutschland (AfD) and the boundaries of its participation in political life. It covers the party''s electoral rise, its classification by the domestic-intelligence service (Verfassungsschutz), the "Brandmauer" or firewall by which other parties decline to cooperate with it, debates over a possible ban, and disputes over its access to office, state secrets and public institutions. The friction is internal to German politics.',
  description_de = 'Der innenpolitische Konflikt in Deutschland um die Alternative für Deutschland (AfD) und die Grenzen ihrer Teilhabe am politischen Leben. Er umfasst den Aufstieg der Partei bei Wahlen, ihre Einstufung durch den Verfassungsschutz, die „Brandmauer", mit der andere Parteien eine Zusammenarbeit ablehnen, Debatten über ein mögliches Verbot sowie Streit über ihren Zugang zu Ämtern, Staatsgeheimnissen und öffentlichen Institutionen. Die Friktion ist innenpolitisch deutsch.',
  editorial_summary_en = 'The rise of the Alternative für Deutschland has become the central fault line of German domestic politics. The party''s strength in the polls and in regional parliaments runs up against the "Brandmauer", the refusal of the other parties to govern or legislate with it, the domestic-intelligence classification of parts of it as extremist, recurring debate over an outright ban, and moves to limit its access to office and to state secrets. Its congresses, leadership under Alice Weidel and Tino Chrupalla, and street mobilisations draw large counter-protests. Coverage is sharply split: parts of the conservative and sovereigntist press frame the firewall and the intelligence classification as the establishment excluding millions of voters, while the liberal mainstream frames the party as a threat to the constitutional order that the firewall exists to contain; Russian state outlets frame state measures against the party as evidence of German or EU censorship. Allegations of the party''s ties to Moscow surface here but the broader Russian-influence dimension belongs to the Russia-Europe theater.',
  editorial_summary_de = 'Der Aufstieg der Alternative für Deutschland ist zur zentralen Bruchlinie der deutschen Innenpolitik geworden. Die Stärke der Partei in Umfragen und in Landesparlamenten stößt auf die „Brandmauer", die Weigerung der übrigen Parteien, mit ihr zu regieren oder Gesetze zu beschließen, auf die Einstufung von Teilen der Partei als extremistisch durch den Verfassungsschutz, auf wiederkehrende Debatten über ein Verbot und auf Bestrebungen, ihren Zugang zu Ämtern und Staatsgeheimnissen zu begrenzen. Ihre Parteitage, die Führung unter Alice Weidel und Tino Chrupalla sowie Straßenmobilisierungen ziehen große Gegenproteste nach sich. Die Berichterstattung ist tief gespalten: Teile der konservativen und souveränistischen Presse deuten Brandmauer und Geheimdiensteinstufung als Ausschluss von Millionen Wählern durch das Establishment, während der liberale Mainstream die Partei als Gefahr für die verfassungsmäßige Ordnung deutet, zu deren Eindämmung die Brandmauer bestehe; russische Staatsmedien rahmen staatliche Maßnahmen gegen die Partei als deutsche oder EU-Zensur. Vorwürfe über Verbindungen der Partei nach Moskau tauchen hier auf, doch die weitergehende russische Einflussdimension gehört in das Russland-Europa-Theater.',
  updated_at = NOW()
WHERE id = 'afd_and_german_polarisation';

-- ============================ french_nationalist_challenge ============================
UPDATE friction_nodes SET
  name_en = 'French political instability and the national-populist challenge',
  name_de = 'Politische Instabilität Frankreichs und die nationalpopulistische Herausforderung',
  description_en = 'The instability of French national politics and the contest around the Rassemblement National (RN). It covers the sequence of minority governments, no-confidence votes and budget standoffs, the RN''s electoral advance and the legal cases affecting Marine Le Pen and the rise of Jordan Bardella, and the wider argument over sovereignty, the presidential system and the 2027 succession. The friction is internal to French politics.',
  description_de = 'Die Instabilität der französischen Innenpolitik und der Streit um das Rassemblement National (RN). Er umfasst die Abfolge von Minderheitsregierungen, Misstrauensvoten und Haushaltsblockaden, den Wahlerfolg des RN sowie die Gerichtsverfahren um Marine Le Pen und den Aufstieg von Jordan Bardella und die umfassendere Auseinandersetzung über Souveränität, das präsidiale System und die Nachfolge 2027. Die Friktion ist innenpolitisch französisch.',
  editorial_summary_en = 'French politics has entered a phase of chronic instability, with successive minority governments surviving or falling on no-confidence votes and unable to pass budgets through a hung National Assembly. Running through it is the advance of the Rassemblement National: its polling lead, the judicial cases affecting Marine Le Pen and her eligibility, and the rise of Jordan Bardella as the party positions for the 2027 presidential election. Coverage divides between outlets that present the party''s progress and Le Pen''s legal troubles as the establishment and the courts obstructing a movement with genuine popular support, and those that present the same party as a challenge to republican norms and the governing gridlock as the cost of its rise; Russian state media frame French turmoil as evidence of a failing model. The dispute is internal to France; French positions in transatlantic and Ukraine matters are covered in the relevant theaters.',
  editorial_summary_de = 'Die französische Politik ist in eine Phase chronischer Instabilität eingetreten, in der aufeinanderfolgende Minderheitsregierungen an Misstrauensvoten überleben oder scheitern und in einer Nationalversammlung ohne Mehrheit keine Haushalte verabschieden können. Sie wird durchzogen vom Vormarsch des Rassemblement National: seinem Vorsprung in Umfragen, den Gerichtsverfahren um Marine Le Pen und ihre Wählbarkeit sowie dem Aufstieg von Jordan Bardella, während sich die Partei für die Präsidentschaftswahl 2027 in Stellung bringt. Die Berichterstattung teilt sich zwischen Medien, die den Erfolg der Partei und Le Pens juristische Probleme als Behinderung einer Bewegung mit echtem Rückhalt durch Establishment und Justiz darstellen, und solchen, die dieselbe Partei als Herausforderung republikanischer Normen und den Regierungsstillstand als Preis ihres Aufstiegs deuten; russische Staatsmedien rahmen die französischen Turbulenzen als Beleg eines scheiternden Modells. Der Streit ist innerfranzösisch; französische Positionen in transatlantischen und Ukraine-Fragen werden in den jeweiligen Theatern behandelt.',
  updated_at = NOW()
WHERE id = 'french_nationalist_challenge';

-- ============================ eu_migration_burden_sharing ============================
UPDATE friction_nodes SET
  name_en = 'EU migration and asylum policy',
  name_de = 'Migrations- und Asylpolitik der EU',
  description_en = 'The division among EU member states and institutions over migration and asylum. It covers the implementation of the Pact on Migration and Asylum and its solidarity and burden-sharing rules, the contrast between restrictive measures and regularisation schemes across member states, the externalisation of asylum processing to third countries, the entry-exit and border systems, and disputes over returns, detention and the role of the courts. The friction is internal to the Union.',
  description_de = 'Die Spaltung zwischen EU-Mitgliedstaaten und Institutionen in der Migrations- und Asylpolitik. Sie umfasst die Umsetzung des Migrations- und Asylpakts mit seinen Solidaritäts- und Lastenteilungsregeln, den Gegensatz zwischen restriktiven Maßnahmen und Regularisierungsprogrammen in den Mitgliedstaaten, die Auslagerung von Asylverfahren in Drittstaaten, die Ein- und Ausreise- sowie Grenzsysteme und Streitfragen um Rückführungen, Inhaftierung und die Rolle der Gerichte. Die Friktion ist unionsintern.',
  editorial_summary_en = 'Migration remains one of the most persistent lines of division inside the European Union. The Pact on Migration and Asylum and its solidarity mechanism set member states against one another over how much of the burden each must carry, while national approaches diverge sharply, from Spain''s mass regularisation of undocumented migrants to Italy''s offshore processing in Albania to tightened returns and border controls elsewhere. The rollout of the entry-exit border system, court rulings on detention and asylum, and the argument over externalisation to third countries add further friction between capitals, the Commission, the European Parliament and the judiciary. Coverage splits between outlets that treat generous or rights-based measures as legally required solidarity and those that treat restriction and externalisation as the necessary response to public pressure, with the European People''s Party and its critics openly at odds; each national episode is read through that divide.',
  editorial_summary_de = 'Migration bleibt eine der beständigsten Trennlinien innerhalb der Europäischen Union. Der Migrations- und Asylpakt und sein Solidaritätsmechanismus stellen die Mitgliedstaaten gegeneinander in der Frage, wie viel Last jeder tragen muss, während die nationalen Ansätze weit auseinandergehen, von Spaniens Massenregularisierung von Migranten ohne Papiere über Italiens ausgelagerte Verfahren in Albanien bis zu verschärften Rückführungen und Grenzkontrollen andernorts. Die Einführung des Ein- und Ausreisesystems an den Grenzen, Gerichtsurteile zu Inhaftierung und Asyl sowie der Streit über die Auslagerung in Drittstaaten schaffen weitere Reibung zwischen den Hauptstädten, der Kommission, dem Europäischen Parlament und der Justiz. Die Berichterstattung teilt sich zwischen Medien, die großzügige oder rechtebasierte Maßnahmen als rechtlich gebotene Solidarität behandeln, und solchen, die Restriktion und Auslagerung als notwendige Antwort auf den öffentlichen Druck sehen, wobei die Europäische Volkspartei und ihre Kritiker offen im Streit liegen; jede nationale Episode wird durch diese Spaltung gelesen.',
  updated_at = NOW()
WHERE id = 'eu_migration_burden_sharing';

-- ============================ eu_budget_sovereignty ============================
UPDATE friction_nodes SET
  name_en = 'EU budget, own resources and regulatory sovereignty',
  name_de = 'EU-Haushalt, Eigenmittel und regulatorische Souveränität',
  description_en = 'The dispute over the European Union''s budget and the reach of its regulation into member-state competences. It covers the multiannual financial framework and the Commission''s proposals for new own resources and taxes, the conditionality tying disbursement to rule-of-law compliance, the reform of the Common Agricultural Policy and cohesion funds, and the pushback against Green Deal measures such as the combustion-engine phase-out and permitting rules. The friction runs between Brussels and national capitals and among net contributors and recipients.',
  description_de = 'Die Auseinandersetzung um den Haushalt der Europäischen Union und die Reichweite ihrer Regulierung in die Zuständigkeiten der Mitgliedstaaten. Sie umfasst den mehrjährigen Finanzrahmen und die Vorschläge der Kommission für neue Eigenmittel und Abgaben, die Konditionalität, die Auszahlungen an die Einhaltung der Rechtsstaatlichkeit bindet, die Reform der Gemeinsamen Agrarpolitik und der Kohäsionsfonds sowie den Widerstand gegen Maßnahmen des Green Deal wie das Aus für den Verbrennungsmotor und Genehmigungsregeln. Die Friktion verläuft zwischen Brüssel und den nationalen Hauptstädten sowie zwischen Nettozahlern und Empfängern.',
  editorial_summary_en = 'The European Union''s budget has become a proxy for a larger argument over how much money and authority should sit in Brussels. Negotiations over the next multiannual financial framework pit net contributors against recipients, while the Commission''s push for new own resources and EU-level taxes to avoid cuts meets resistance in national capitals. Layered onto it are the conditionality that ties funds to rule-of-law compliance, the contested reform of the Common Agricultural Policy and cohesion funds, and a backlash against Green Deal regulation, from the combustion-engine phase-out to permitting and reporting rules. Coverage divides between outlets that frame stronger central financing and regulation as necessary for a capable Union and those that frame it as overreach into national competences and taxpayers'' money; the agricultural and industrial dimensions bring farmers'' and business lobbies into the same divide.',
  editorial_summary_de = 'Der Haushalt der Europäischen Union ist zum Stellvertreter einer größeren Auseinandersetzung darüber geworden, wie viel Geld und Autorität in Brüssel liegen sollen. Die Verhandlungen über den nächsten mehrjährigen Finanzrahmen stellen Nettozahler gegen Empfänger, während der Vorstoß der Kommission für neue Eigenmittel und Abgaben auf EU-Ebene, um Kürzungen zu vermeiden, in den nationalen Hauptstädten auf Widerstand stößt. Hinzu kommen die Konditionalität, die Mittel an die Einhaltung der Rechtsstaatlichkeit bindet, die umstrittene Reform der Gemeinsamen Agrarpolitik und der Kohäsionsfonds sowie ein Widerstand gegen die Green-Deal-Regulierung, vom Aus für den Verbrennungsmotor bis zu Genehmigungs- und Berichtspflichten. Die Berichterstattung teilt sich zwischen Medien, die eine stärkere zentrale Finanzierung und Regulierung als notwendig für eine handlungsfähige Union deuten, und solchen, die darin einen Übergriff in nationale Zuständigkeiten und in Steuergelder sehen; die agrar- und industriepolitische Dimension bringt Bauern- und Wirtschaftsverbände in dieselbe Spaltung.',
  updated_at = NOW()
WHERE id = 'eu_budget_sovereignty';

-- ============================ eu_right_realignment ============================
UPDATE friction_nodes SET
  description_en = 'The reordering of Europe''s political right and the debate over cooperation between mainstream and national-conservative parties. It covers the balance among the European Parliament''s groups, the European People''s Party (EPP), the European Conservatives and Reformists (ECR) and Patriots for Europe (PfE), the erosion of the "cordon sanitaire" by which centrist parties have declined to govern with national-populist parties, joint votes and coalitions that cross that line, and the cross-border coordination of sovereigntist movements. The friction is internal to European party politics.',
  description_de = 'Die Neuordnung der europäischen Rechten und die Debatte über die Zusammenarbeit zwischen Mainstream- und nationalkonservativen Parteien. Sie umfasst das Kräfteverhältnis zwischen den Fraktionen des Europäischen Parlaments, der Europäischen Volkspartei (EVP), den Europäischen Konservativen und Reformern (EKR) und den Patrioten für Europa (PfE), die Aufweichung des „Cordon sanitaire", mit dem zentristische Parteien eine Regierung mit nationalpopulistischen Parteien abgelehnt haben, gemeinsame Abstimmungen und Koalitionen über diese Linie hinweg sowie die grenzüberschreitende Koordinierung souveränistischer Bewegungen. Die Friktion ist innerhalb der europäischen Parteipolitik angesiedelt.',
  editorial_summary_en = 'Europe''s political right is realigning, and the question of who will cooperate with whom has become a defining fault line of Union politics. In the European Parliament the European People''s Party increasingly passes measures with the Conservatives and Reformists and the Patriots for Europe rather than with the centre-left, while national-conservative parties coordinate across borders and position for a larger share of power. Running beneath it is the "cordon sanitaire", the long-standing refusal of mainstream parties to govern with national-populist ones, which is being tested and in places abandoned. Coverage divides between outlets that frame the realignment as the belated normalisation of parties with millions of voters and a legitimate majority, and those that frame it as the mainstream right lending respectability to movements it once excluded and eroding a norm that protected liberal democracy; Russian and Chinese state media present the shift as the decline of the European centre. It is distinct from the domestic party contests in Germany, France and Hungary, which have their own nodes.',
  editorial_summary_de = 'Die europäische Rechte ordnet sich neu, und die Frage, wer mit wem zusammenarbeitet, ist zu einer prägenden Bruchlinie der Unionspolitik geworden. Im Europäischen Parlament verabschiedet die Europäische Volkspartei zunehmend Maßnahmen mit den Konservativen und Reformern und den Patrioten für Europa statt mit der Mitte-Links-Seite, während sich nationalkonservative Parteien über Grenzen hinweg koordinieren und sich einen größeren Machtanteil sichern wollen. Darunter liegt der „Cordon sanitaire", die langjährige Weigerung der Mainstream-Parteien, mit nationalpopulistischen zu regieren, die nun auf die Probe gestellt und mancherorts aufgegeben wird. Die Berichterstattung teilt sich zwischen Medien, die die Neuordnung als überfällige Normalisierung von Parteien mit Millionen Wählern und legitimer Mehrheit deuten, und solchen, die darin sehen, wie die etablierte Rechte Bewegungen Ansehen verleiht, die sie einst ausschloss, und eine Norm aushöhlt, die die liberale Demokratie schützte; russische und chinesische Staatsmedien präsentieren den Wandel als Niedergang der europäischen Mitte. Sie ist von den nationalen Parteienkämpfen in Deutschland, Frankreich und Ungarn zu unterscheiden, die eigene Knoten haben.',
  updated_at = NOW()
WHERE id = 'eu_right_realignment';
