-- Taiwan Strait theater: bilingual completeness fields (§6) for the theater + 4 atomics.
--
-- Prose rule (feedback_fn_descriptions_neutral): descriptions and editorial summaries are
-- neutral, fact-based and evergreen -- no framing words, no motive attribution, no
-- temporality. Contested terms stay out of this layer: "separatist" and "Taiwan
-- independence" are matching aliases and appear inside narratives_v2 claims, never here.
-- Where the two sides' terminology differs (e.g. what Beijing calls law enforcement),
-- the text attributes the term rather than adopting it.

BEGIN;

UPDATE friction_nodes SET
  description_en = 'The dispute over Taiwan''s political status and the military, diplomatic and economic contest surrounding it. Beijing claims the island as Chinese territory and has not renounced the use of force to take it; Taipei governs the island separately and rejects that claim. Four axes run through the theater: Chinese military and coast guard activity around the island and the deterrence response to it; the scope and reliability of United States arms supply and security policy; political influence activity directed at Taiwan and the contest over it among the island''s parties; and Taiwan''s diplomatic recognition and participation in international organisations. The United States and Japan are parties to the security dimension without maintaining formal diplomatic relations with Taipei.',
  description_de = 'Der Streit über den politischen Status Taiwans und der militärische, diplomatische und wirtschaftliche Wettstreit darum. Peking beansprucht die Insel als chinesisches Territorium und hat dem Einsatz von Gewalt zu ihrer Einnahme nicht abgeschworen; Taipeh regiert die Insel getrennt und weist diesen Anspruch zurück. Vier Achsen durchziehen das Theater: chinesische Militär- und Küstenwachaktivitäten rund um die Insel und die darauf gerichtete Abschreckung; Umfang und Verlässlichkeit der US-Waffenlieferungen und Sicherheitspolitik; die auf Taiwan gerichtete politische Einflussnahme und der Wettstreit darüber zwischen den Parteien der Insel; sowie Taiwans diplomatische Anerkennung und Teilhabe an internationalen Organisationen. Die USA und Japan sind Parteien der Sicherheitsdimension, ohne formelle diplomatische Beziehungen zu Taipeh zu unterhalten.',
  editorial_summary_en = 'The Taiwan Strait is where the People''s Republic of China''s claim to Taiwan meets the island''s separate government and the security arrangements of the United States and Japan. Beijing holds that the island is part of China and has not renounced the use of force; Taipei governs it separately, and Washington maintains unofficial relations, supplies arms under the Taiwan Relations Act, and has long declined to state explicitly whether it would intervene militarily. The contest runs on four axes that this theater tracks separately: aircraft, naval and coast guard activity around the island together with the exercises and Strait transits conducted in response; the scale and dependability of American arms supply, alongside Taiwan''s own defence budget and conscription debates; political influence activity directed at the island, including the party-to-party channel between the Chinese Communist Party and the Kuomintang, economic inducements, and reported espionage and disinformation; and Taiwan''s shrinking set of formal diplomatic partners, its exclusion from bodies such as the World Health Assembly, and the restrictions placed on its officials'' travel. Coverage divides along predictable lines: Western, Japanese and regional outlets describe Chinese activity as coercion of a democracy, Chinese and Russian state media describe the same activity as lawful enforcement of sovereignty against foreign interference, and a distinct strand of Western reporting questions whether American commitments will hold.',
  editorial_summary_de = 'In der Taiwanstraße trifft der Anspruch der Volksrepublik China auf Taiwan auf die eigenständige Regierung der Insel und die Sicherheitsarrangements der USA und Japans. Peking hält die Insel für einen Teil Chinas und hat dem Einsatz von Gewalt nicht abgeschworen; Taipeh regiert sie getrennt, und Washington unterhält inoffizielle Beziehungen, liefert Waffen nach dem Taiwan Relations Act und hat es lange vermieden, ausdrücklich zu erklären, ob es militärisch eingreifen würde. Der Wettstreit verläuft auf vier Achsen, die dieses Theater getrennt verfolgt: Luft-, See- und Küstenwachaktivitäten rund um die Insel samt der darauf folgenden Manöver und Durchfahrten; Umfang und Verlässlichkeit der amerikanischen Waffenlieferungen neben Taiwans eigenen Debatten über Verteidigungshaushalt und Wehrpflicht; die auf die Insel gerichtete politische Einflussnahme, darunter der Parteikanal zwischen der Kommunistischen Partei Chinas und der Kuomintang, wirtschaftliche Anreize sowie berichtete Spionage und Desinformation; und Taiwans schrumpfender Kreis formeller diplomatischer Partner, sein Ausschluss aus Gremien wie der Weltgesundheitsversammlung und die Beschränkungen für Reisen seiner Amtsträger. Die Berichterstattung teilt sich entlang erwartbarer Linien.'
WHERE id = 'taiwan_strait_theater';

UPDATE friction_nodes SET
  description_en = 'Chinese military and coast guard operations in the air and waters around Taiwan, and the responses of Taiwan and its security partners. Covers aircraft and naval movements across the Taiwan Strait median line and into Taiwan''s air defence identification zone, coast guard patrols that Beijing describes as law enforcement, aircraft carrier transits and large-scale exercises, alongside Taiwan''s combat readiness drills and the Strait transits conducted by the navies of the United States, Japan and other states. It also covers activity below the threshold of armed force: undersea cable damage, balloon overflights, sand dredging and cyber operations. Taiwan-held offshore islands, including Kinmen, Matsu, Penghu, the Pratas and Taiping, are recurring locations.',
  description_de = 'Chinesische Militär- und Küstenwachoperationen im Luftraum und in den Gewässern rund um Taiwan sowie die Reaktionen Taiwans und seiner Sicherheitspartner. Erfasst Flug- und Schiffsbewegungen über die Mittellinie der Taiwanstraße und in Taiwans Luftverteidigungszone, Küstenwachpatrouillen, die Peking als Rechtsdurchsetzung bezeichnet, Trägerdurchfahrten und große Manöver, daneben Taiwans Bereitschaftsübungen und die Durchfahrten der Marinen der USA, Japans und weiterer Staaten. Erfasst auch Aktivitäten unterhalb der Schwelle bewaffneter Gewalt: Beschädigung von Seekabeln, Ballonüberflüge, Sandbaggerei und Cyberoperationen. Von Taiwan gehaltene vorgelagerte Inseln, darunter Kinmen, Matsu, Penghu, die Pratas-Inseln und Taiping, sind wiederkehrende Schauplätze.',
  editorial_summary_en = 'This node covers the military and sub-military activity around Taiwan and the responses to it. On one side: sorties across the median line and into the air defence identification zone, coast guard patrols to the island''s east that Beijing characterises as regularised law enforcement, aircraft carrier movements through the Strait, and exercises that rehearse blockade and landing operations. On the other: Taiwan''s combat readiness drills, its investment in drones and asymmetric systems, and the Taiwan Strait transits conducted by American, Japanese, Canadian, Australian and European vessels, each of which draws a Chinese response. A distinct strand runs below the threshold of armed force -- undersea cable breaks affecting outlying islands, balloons, sand dredging and cyber operations -- and is often the more consequential day to day. The same events carry opposite descriptions depending on the outlet: an incursion or a routine patrol, a provocation or a lawful response.',
  editorial_summary_de = 'Dieser Knoten erfasst die militärischen und untermilitärischen Aktivitäten rund um Taiwan und die Reaktionen darauf. Auf der einen Seite: Einsätze über die Mittellinie und in die Luftverteidigungszone, Küstenwachpatrouillen östlich der Insel, die Peking als regularisierte Rechtsdurchsetzung bezeichnet, Trägerbewegungen durch die Meerenge und Manöver, die Blockade- und Landungsoperationen proben. Auf der anderen: Taiwans Bereitschaftsübungen, seine Investitionen in Drohnen und asymmetrische Systeme sowie die Durchfahrten amerikanischer, japanischer, kanadischer, australischer und europäischer Schiffe, auf die jeweils eine chinesische Reaktion folgt. Ein eigener Strang verläuft unterhalb der Schwelle bewaffneter Gewalt: Brüche von Seekabeln zu den vorgelagerten Inseln, Ballons, Sandbaggerei und Cyberoperationen. Dieselben Ereignisse werden je nach Medium gegensätzlich beschrieben.'
WHERE id = 'taiwan_military_pressure';

UPDATE friction_nodes SET
  description_en = 'United States arms supply to Taiwan and the scope of American security policy toward the island, together with Taiwan''s own defence effort. Covers arms sales, congressional approvals, deliveries and the delivery backlog; the Taiwan Relations Act and the Six Assurances; and the long-standing American practice of not stating explicitly whether it would intervene militarily, which is discussed as strategic ambiguity. Also covers the treatment of Taiwan in wider United States-China negotiations, and Taiwan''s defence budget, conscription and asymmetric-warfare programmes, which are contested in Taiwan''s legislature and raised by Washington as a question of burden sharing.',
  description_de = 'US-Waffenlieferungen an Taiwan und der Umfang der amerikanischen Sicherheitspolitik gegenüber der Insel, zusammen mit Taiwans eigener Verteidigungsanstrengung. Erfasst Rüstungsverkäufe, Genehmigungen durch den Kongress, Lieferungen und den Lieferrückstand; den Taiwan Relations Act und die Sechs Zusicherungen; sowie die langjährige amerikanische Praxis, nicht ausdrücklich zu erklären, ob militärisch eingegriffen würde, die als strategische Ambiguität erörtert wird. Erfasst zudem die Behandlung Taiwans in den weiteren Verhandlungen zwischen den USA und China sowie Taiwans Verteidigungshaushalt, Wehrpflicht und asymmetrische Programme, die im taiwanischen Parlament umstritten sind und von Washington als Frage der Lastenteilung angesprochen werden.',
  editorial_summary_en = 'Taiwan buys most of its major weapons from the United States, which supplies them under the Taiwan Relations Act while maintaining no formal diplomatic relations and declining to say explicitly whether it would defend the island. This node tracks that relationship in both directions. On the American side: which packages are approved, delivered, reviewed or delayed; the size of the undelivered backlog; official statements on whether policy has changed; and the appearance of Taiwan on the agenda of United States-China summitry, where arms sales have been described as a negotiating asset. On the Taiwanese side: a defence budget and special-budget process contested between the governing party and the opposition, extended conscription, and a shift toward drones and other asymmetric systems, all of which Washington raises as burden sharing. Coverage splits three ways rather than two. Chinese and Russian state media treat the arms relationship as a breach of the one-China principle. Western and regional outlets are consistently supportive of Taiwan but divide between reporting the commitment as intact and questioning whether it will hold -- so the critical register here comes largely from the island''s own supporters.',
  editorial_summary_de = 'Taiwan bezieht die meisten seiner schweren Waffen aus den USA, die sie nach dem Taiwan Relations Act liefern, ohne formelle diplomatische Beziehungen zu unterhalten und ohne ausdrücklich zu erklären, ob sie die Insel verteidigen würden. Dieser Knoten verfolgt diese Beziehung in beide Richtungen. Auf amerikanischer Seite: welche Pakete genehmigt, geliefert, überprüft oder verzögert werden; der Umfang des Lieferrückstands; offizielle Aussagen zu einer etwaigen Änderung der Politik; und das Auftauchen Taiwans auf der Tagesordnung der Gipfel zwischen den USA und China, bei denen Rüstungsverkäufe als Verhandlungsgut bezeichnet wurden. Auf taiwanischer Seite: ein zwischen Regierungspartei und Opposition umstrittener Verteidigungs- und Sonderhaushalt, die verlängerte Wehrpflicht und die Hinwendung zu Drohnen und anderen asymmetrischen Systemen. Die Berichterstattung teilt sich dreifach statt zweifach: Der kritische Ton stammt hier großenteils von den Unterstützern der Insel selbst.',
  name_de = 'US-Sicherheitszusage und Waffenlieferungen'
WHERE id = 'taiwan_us_security_commitment';

UPDATE friction_nodes SET
  description_en = 'Political influence activity directed at Taiwan from the mainland, and the contest over it inside Taiwan. Covers united front work, including the party-to-party channel between the Chinese Communist Party and the Kuomintang and the mainland visits of Kuomintang delegations; economic incentives and preferential policies offered to Taiwanese citizens and firms; cross-strait forums and people-to-people exchanges; entry bans and commercial restrictions directed at people Beijing designates as supporters of independence; and reported espionage, cognitive-warfare and disinformation operations. Taiwan''s own party competition over China policy, including legislative disputes and recall campaigns, forms part of the same contest.',
  description_de = 'Vom Festland auf Taiwan gerichtete politische Einflussnahme und der Wettstreit darüber innerhalb Taiwans. Erfasst Einheitsfrontarbeit, darunter den Parteikanal zwischen der Kommunistischen Partei Chinas und der Kuomintang sowie die Festlandbesuche von Kuomintang-Delegationen; wirtschaftliche Anreize und Vorzugsregelungen für taiwanische Bürger und Unternehmen; Foren und zwischenmenschlichen Austausch über die Meerenge; Einreiseverbote und geschäftliche Beschränkungen gegen Personen, die Peking als Unterstützer der Unabhängigkeit einstuft; sowie berichtete Spionage-, Kognitions- und Desinformationsoperationen. Taiwans eigener Parteienwettstreit über die China-Politik, einschließlich parlamentarischer Auseinandersetzungen und Abwahlkampagnen, ist Teil desselben Wettstreits.',
  editorial_summary_en = 'Alongside the military dimension runs a political one, conducted through party channels, money and information rather than ships and aircraft. Its most visible element is the relationship between the Chinese Communist Party and the Kuomintang: chairwoman Cheng Li-wun''s delegation visits to the mainland and her meeting with Xi Jinping, revived party-to-party think-tank forums, and the economic incentives announced around them. Alongside the courtship sits its opposite -- entry bans and commercial restrictions on people Beijing designates as independence supporters -- and a reported intelligence dimension, including espionage cases inside Taiwan''s military and disinformation and cognitive-warfare campaigns aimed at Taiwanese voters. The island''s own politics is the terrain: the governing party and the opposition disagree over how far to engage the mainland and how much to spend on defence, and each side''s position is amplified by different outlets. Reporting divides sharply on the same facts, with Chinese and Russian state media presenting exchanges as goodwill toward compatriots and Western, Japanese and regional outlets presenting the same activity as subversion.',
  editorial_summary_de = 'Neben der militärischen verläuft eine politische Dimension, die über Parteikanäle, Geld und Information statt über Schiffe und Flugzeuge geführt wird. Ihr sichtbarstes Element ist das Verhältnis zwischen der Kommunistischen Partei Chinas und der Kuomintang: die Festlandbesuche der Vorsitzenden Cheng Li-wun und ihr Treffen mit Xi Jinping, wiederbelebte Think-Tank-Foren beider Parteien und die dabei angekündigten wirtschaftlichen Anreize. Neben dem Werben steht dessen Gegenteil -- Einreiseverbote und geschäftliche Beschränkungen gegen von Peking benannte Personen -- sowie eine berichtete nachrichtendienstliche Dimension, darunter Spionagefälle im taiwanischen Militär und Desinformationskampagnen. Taiwans eigene Politik ist das Terrain: Regierungspartei und Opposition sind uneins über das Maß der Annäherung und die Verteidigungsausgaben.',
  name_de = 'Politische Einflussnahme und Einheitsfrontarbeit'
WHERE id = 'taiwan_political_warfare';

UPDATE friction_nodes SET
  description_en = 'Taiwan''s diplomatic status and its participation in international bodies. Covers its remaining formal diplomatic partners and changes among them; efforts by Beijing to reduce that number and to restrict the travel of Taiwanese officials, including overflight and transit clearances; Taiwan''s exclusion from the World Health Assembly, ICAO and other organisations, and the competing readings of United Nations General Assembly Resolution 2758; representative offices that operate in the absence of formal relations, and the disputes they have triggered; parliamentary visits to Taipei and the responses to them; and the terminology governments and international bodies use for the island.',
  description_de = 'Taiwans diplomatischer Status und seine Teilhabe an internationalen Gremien. Erfasst die verbliebenen formellen diplomatischen Partner und Veränderungen in deren Kreis; Bemühungen Pekings, diese Zahl zu verringern und Reisen taiwanischer Amtsträger einschließlich Überflug- und Transitgenehmigungen zu beschränken; Taiwans Ausschluss von der Weltgesundheitsversammlung, der ICAO und weiteren Organisationen sowie die konkurrierenden Lesarten der UN-Resolution 2758; Repräsentanzen, die ohne formelle Beziehungen arbeiten, und die dadurch ausgelösten Streitfälle; parlamentarische Besuche in Taipeh und die Reaktionen darauf; sowie die Begriffe, die Regierungen und internationale Gremien für die Insel verwenden.',
  editorial_summary_en = 'Taiwan maintains formal diplomatic relations with a small and shrinking number of states, and unofficial relations through representative offices with many more. This node tracks the contest over both. It covers pressure on the remaining partners and the periodic switches of recognition; the blocking of Taiwanese leaders'' travel through denied overflight and transit clearances, which has curtailed presidential trips; exclusion from the World Health Assembly and ICAO; and the argument over whether United Nations General Assembly Resolution 2758 settled the island''s status, which Beijing asserts and Taipei and several Western governments dispute. Individual bilateral disputes recur -- Lithuania''s representative office and the trade consequences that followed, an office opened with Somaliland, and the responses to parliamentary delegations visiting Taipei. Naming is itself contested: whether the island is called Taiwan, Chinese Taipei, the Taiwan region or the Republic of China signals a position rather than a neutral choice.',
  editorial_summary_de = 'Taiwan unterhält formelle diplomatische Beziehungen zu einer kleinen und schrumpfenden Zahl von Staaten und inoffizielle Beziehungen über Repräsentanzen zu deutlich mehr. Dieser Knoten verfolgt den Wettstreit um beides: den Druck auf die verbliebenen Partner und die zeitweiligen Anerkennungswechsel; die Blockade von Reisen taiwanischer Politiker durch verweigerte Überflug- und Transitgenehmigungen, die Präsidentenreisen beschnitten hat; den Ausschluss von der Weltgesundheitsversammlung und der ICAO; sowie den Streit darüber, ob die UN-Resolution 2758 den Status der Insel geklärt hat, was Peking behauptet und Taipeh sowie mehrere westliche Regierungen bestreiten. Einzelne bilaterale Streitfälle wiederholen sich, etwa Litauens Repräsentanz und die folgenden Handelskonsequenzen. Auch die Benennung ist umstritten und signalisiert eine Position.',
  name_de = 'Internationale Anerkennung und diplomatischer Status'
WHERE id = 'taiwan_international_recognition';

COMMIT;
