-- Seed global friction nodes - Part 2: Atomic FNs (EUROPE, ASIA-PACIFIC, AFRICA, AMERICAS, ARCTIC)
-- 2026-06-20

INSERT INTO friction_nodes (id, name_en, fn_type, centroid_ids, member_fn_ids, display_order, is_active) VALUES

-- ATOMIC FNs (EUROPE)
('ukraine_battlefield', 'Ukraine battlefield operations', 'atomic', ARRAY['EUROPE-UKRAINE','EUROPE-RUSSIA'], NULL, 20, true),
('western_aid_to_ukraine', 'Western aid to Ukraine', 'atomic', ARRAY['EUROPE-UKRAINE','AMERICAS-USA','EUROPE-EU'], NULL, 21, true),
('ukraine_peace_negotiations', 'Ukraine peace negotiations', 'atomic', ARRAY['EUROPE-UKRAINE','EUROPE-RUSSIA'], NULL, 22, true),
('ukraine_official_corruption', 'Ukrainian official corruption investigations', 'atomic', ARRAY['EUROPE-UKRAINE'], NULL, 23, true),
('nato_deterrence', 'NATO-Russia military deterrence on Eastern flank', 'atomic', ARRAY['EUROPE-RUSSIA','EUROPE-POLAND','EUROPE-BALTICS','AMERICAS-USA','EUROPE-GERMANY'], NULL, 24, true),
('sanctions_and_economy', 'Sanctions regime and economic warfare', 'atomic', ARRAY['EUROPE-RUSSIA','EUROPE-EU','AMERICAS-USA'], NULL, 25, true),
('baltic_security', 'Baltic states security and NATO guarantees', 'atomic', ARRAY['EUROPE-RUSSIA','EUROPE-ESTONIA','EUROPE-LATVIA','EUROPE-LITHUANIA','AMERICAS-USA'], NULL, 26, true),
('energy_security_leverage', 'Russian gas leverage and energy security', 'atomic', ARRAY['EUROPE-RUSSIA','EUROPE-EU','AMERICAS-USA'], NULL, 27, true),
('greenland_sovereignty', 'Greenland sovereignty and Arctic geopolitics', 'atomic', ARRAY['EUROPE-DENMARK','EUROPE-GREENLAND','AMERICAS-USA','AMERICAS-CANADA'], NULL, 28, true),
('transatlantic_trade', 'Transatlantic trade disputes and tariffs', 'atomic', ARRAY['EUROPE-EU','AMERICAS-USA'], NULL, 29, true),
('strategic_autonomy', 'European strategic autonomy and decoupling', 'atomic', ARRAY['EUROPE-EU','AMERICAS-USA','ASIA-PACIFIC-CHINA'], NULL, 30, true),
('defence_dependence', 'Defence burden-sharing and NATO spending', 'atomic', ARRAY['EUROPE-EU','AMERICAS-USA'], NULL, 31, true),
('hungary_rule_of_law', 'Hungary rule of law and EU institutions conflict', 'atomic', ARRAY['EUROPE-HUNGARY','EUROPE-EU'], NULL, 32, true),
('slovakia_alignment', 'Slovakia sovereignty and realignment pressures', 'atomic', ARRAY['EUROPE-SLOVAKIA','EUROPE-EU','EUROPE-RUSSIA'], NULL, 33, true),
('migration_burden_sharing', 'Migration burden-sharing and border conflicts', 'atomic', ARRAY['EUROPE-EU'], NULL, 34, true),
('budget_and_sovereignty', 'EU budget, Recovery Fund and sovereignty disputes', 'atomic', ARRAY['EUROPE-EU','EUROPE-HUNGARY','EUROPE-SLOVAKIA','EUROPE-POLAND'], NULL, 35, true),
('afd_and_german_polarisation', 'AfD and German political polarisation', 'atomic', ARRAY['EUROPE-GERMANY'], NULL, 36, true),
('french_nationalist_challenge', 'French nationalist movement and sovereignty', 'atomic', ARRAY['EUROPE-FRANCE'], NULL, 37, true),
('post_brexit_realignment', 'Post-Brexit UK-EU relationship', 'atomic', ARRAY['EUROPE-UK','EUROPE-EU'], NULL, 38, true),
('italian_populist_government', 'Italian right-wing populism and EU tensions', 'atomic', ARRAY['EUROPE-ITALY','EUROPE-EU'], NULL, 39, true),
('serbia_kosovo_tensions', 'Serbia-Kosovo status and normalisation', 'atomic', ARRAY['EUROPE-SERBIA','EUROPE-KOSOVO'], NULL, 40, true),
('bosnia_fragmentation', 'Bosnia institutional fragmentation', 'atomic', ARRAY['EUROPE-BOSNIA'], NULL, 41, true),
('armenia_azerbaijan_settlement', 'Armenia-Azerbaijan peace settlement and normalization', 'atomic', ARRAY['EUROPE-ARMENIA','EUROPE-AZERBAIJAN','EUROPE-RUSSIA','MIDEAST-TURKEY','AMERICAS-USA','EUROPE-EU','MIDEAST-IRAN'], NULL, 42, true),
('nagorno_karabakh_aftermath', 'Nagorno-Karabakh humanitarian crisis and war crimes accountability', 'atomic', ARRAY['EUROPE-ARMENIA','EUROPE-AZERBAIJAN','EUROPE-RUSSIA','MIDEAST-TURKEY','AMERICAS-USA','EUROPE-EU'], NULL, 43, true),
('zangezur_corridor', 'Zangezur corridor transit and regional connectivity', 'atomic', ARRAY['EUROPE-ARMENIA','EUROPE-AZERBAIJAN','MIDEAST-TURKEY','MIDEAST-IRAN'], NULL, 44, true),
('regional_power_competition', 'Russia-Turkey-Iran competition and regional balance', 'atomic', ARRAY['EUROPE-ARMENIA','EUROPE-AZERBAIJAN','EUROPE-RUSSIA','MIDEAST-TURKEY','MIDEAST-IRAN','AMERICAS-USA','EUROPE-EU'], NULL, 45, true),

-- ATOMIC FNs (ASIA-PACIFIC)
('security_alignment', 'AUKUS and Indo-Pacific security partnership', 'atomic', ARRAY['ASIA-PACIFIC-AUSTRALIA','ASIA-PACIFIC-CHINA','AMERICAS-USA','ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-SOUTH-KOREA'], NULL, 46, true),
('economic_coercion', 'Economic sanctions and trade weaponization', 'atomic', ARRAY['ASIA-PACIFIC-AUSTRALIA','ASIA-PACIFIC-CHINA'], NULL, 47, true),
('pacific_island_alignment', 'Geopolitical competition in Pacific island states', 'atomic', ARRAY['ASIA-PACIFIC-AUSTRALIA','ASIA-PACIFIC-CHINA','ASIA-PACIFIC-FIJI','ASIA-PACIFIC-SOLOMON-ISLANDS'], NULL, 48, true),
('taiwan_sovereignty', 'Taiwan sovereignty dispute', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','ASIA-PACIFIC-TAIWAN','AMERICAS-USA'], NULL, 49, true),
('taiwan_military_pressure', 'Military pressure and deterrence around Taiwan', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','ASIA-PACIFIC-TAIWAN','AMERICAS-USA'], NULL, 50, true),
('taiwan_semiconductor_dependence', 'Semiconductor strategic dependence and supply chain security', 'atomic', ARRAY['ASIA-PACIFIC-TAIWAN','ASIA-PACIFIC-CHINA','AMERICAS-USA','ASIA-PACIFIC-JAPAN'], NULL, 51, true),
('taiwan_international_recognition', 'Taiwan international recognition and diplomatic status', 'atomic', ARRAY['ASIA-PACIFIC-TAIWAN','ASIA-PACIFIC-CHINA'], NULL, 52, true),
('south_china_sea_claims', 'Maritime territorial claims and UNCLOS interpretation', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','ASIA-PACIFIC-PHILIPPINES','ASIA-PACIFIC-VIETNAM','ASIA-PACIFIC-MALAYSIA','ASIA-PACIFIC-INDONESIA','ASIA-PACIFIC-BRUNEI'], NULL, 53, true),
('freedom_of_navigation', 'Freedom of navigation and great power operations', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','AMERICAS-USA'], NULL, 54, true),
('reef_militarisation', 'Artificial islands militarisation and counter-presence', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','ASIA-PACIFIC-PHILIPPINES','ASIA-PACIFIC-VIETNAM','AMERICAS-USA'], NULL, 55, true),
('fisheries_conflict', 'Fisheries enforcement and maritime harassment', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','ASIA-PACIFIC-PHILIPPINES','ASIA-PACIFIC-VIETNAM'], NULL, 56, true),
('north_korea_missile_program', 'North Korean ballistic and nuclear missile programme', 'atomic', ARRAY['ASIA-PACIFIC-NORTH-KOREA','ASIA-PACIFIC-SOUTH-KOREA','AMERICAS-USA'], NULL, 57, true),
('peninsula_deterrence', 'Peninsula military deterrence and posture', 'atomic', ARRAY['ASIA-PACIFIC-NORTH-KOREA','ASIA-PACIFIC-SOUTH-KOREA','AMERICAS-USA'], NULL, 58, true),
('north_korea_international_pressure', 'International sanctions and pressure regime on North Korea', 'atomic', ARRAY['ASIA-PACIFIC-NORTH-KOREA','AMERICAS-USA','ASIA-PACIFIC-CHINA','ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-SOUTH-KOREA'], NULL, 59, true),
('reunification_and_identity', 'Korean reunification question and national identity', 'atomic', ARRAY['ASIA-PACIFIC-NORTH-KOREA','ASIA-PACIFIC-SOUTH-KOREA'], NULL, 60, true),
('north_korea_china_leverage', 'China leverage over North Korea and sanctions enforcement', 'atomic', ARRAY['ASIA-PACIFIC-NORTH-KOREA','ASIA-PACIFIC-CHINA'], NULL, 61, true),
('kashmir_dispute', 'Kashmir territorial dispute and border tensions', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-PAKISTAN','ASIA-PACIFIC-CHINA'], NULL, 62, true),
('cross_border_militancy', 'Cross-border militancy and proxy accusations', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-PAKISTAN'], NULL, 63, true),
('nuclear_deterrence_balance', 'Nuclear deterrence balance and strategic stability', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-PAKISTAN'], NULL, 64, true),
('water_sharing_indus', 'Indus waters treaty and resource sharing disputes', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-PAKISTAN'], NULL, 65, true),
('ladakh_lac_dispute', 'Ladakh and LAC border militarization', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-CHINA'], NULL, 66, true),
('himalayan_strategic_competition', 'Himalayan strategic competition and infrastructure', 'atomic', ARRAY['ASIA-PACIFIC-INDIA','ASIA-PACIFIC-CHINA','ASIA-PACIFIC-BHUTAN'], NULL, 67, true),
('senkaku_diaoyu_islands', 'Senkaku/Diaoyu islands territorial dispute', 'atomic', ARRAY['ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-CHINA'], NULL, 68, true),
('east_china_sea_claims', 'East China Sea overlapping continental shelf claims', 'atomic', ARRAY['ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-CHINA','ASIA-PACIFIC-SOUTH-KOREA'], NULL, 69, true),
('historical_memory_conflicts', 'Historical memory and memory wars', 'atomic', ARRAY['ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-CHINA'], NULL, 70, true),
('myanmar_military_rule', 'Military rule and anti-junta resistance', 'atomic', ARRAY['ASIA-PACIFIC-MYANMAR','NON-STATE-ANTI-JUNTA'], NULL, 71, true),
('ethnic_armed_conflicts', 'Ethnic armed conflicts and autonomy demands', 'atomic', ARRAY['ASIA-PACIFIC-MYANMAR','NON-STATE-ETHNIC-MILITIAS'], NULL, 72, true),
('china_border_influence', 'Chinese influence on border stability and conflicts', 'atomic', ARRAY['ASIA-PACIFIC-MYANMAR','ASIA-PACIFIC-CHINA'], NULL, 73, true),

-- ATOMIC FNs (AFRICA)
('ethiopia_tigray_aftermath', 'Tigray conflict aftermath and war crimes accountability', 'atomic', ARRAY['AFRICA-ETHIOPIA','AFRICA-ERITREA','AFRICA-EGYPT','AMERICAS-USA','EUROPE-UK'], NULL, 74, true),
('ethiopia_amhara_conflict', 'Amhara insurgency and border tensions', 'atomic', ARRAY['AFRICA-ETHIOPIA','AFRICA-ERITREA','NON-STATE-OROMIA-LIBERATION-FRONT'], NULL, 75, true),
('somalia_al_shabaab', 'Al-Shabaab insurgency and counter-terror operations', 'atomic', ARRAY['AFRICA-SOMALIA','AFRICA-KENYA','AMERICAS-USA','AFRICA-TURKEY','NON-STATE-AL-SHABAAB'], NULL, 76, true),
('ethiopia_somaliland_access', 'Ethiopian sea access and Red Sea port competition', 'atomic', ARRAY['AFRICA-ETHIOPIA','AFRICA-SOMALIA','AFRICA-EGYPT','AFRICA-DJIBOUTI','AFRICA-ERITREA'], NULL, 77, true),
('sahel_jihadist_insurgency', 'Jihadist insurgency and militant group operations', 'atomic', ARRAY['AFRICA-MALI','AFRICA-NIGER','AFRICA-BURKINA-FASO','AFRICA-NIGERIA','AFRICA-MAURITANIA','NON-STATE-JIHADISTS'], NULL, 78, true),
('french_withdrawal_legacy', 'Post-French security vacuum and great power competition', 'atomic', ARRAY['AFRICA-MALI','AFRICA-NIGER','AFRICA-BURKINA-FASO','EUROPE-FRANCE','AMERICAS-USA','EUROPE-RUSSIA'], NULL, 79, true),
('russian_security_presence', 'Wagner and Russian military expansion in Sahel', 'atomic', ARRAY['AFRICA-MALI','AFRICA-NIGER','AFRICA-BURKINA-FASO','EUROPE-RUSSIA','EUROPE-FRANCE','AMERICAS-USA'], NULL, 80, true),
('regional_regime_consolidation', 'Military junta consolidation and democratic backsliding', 'atomic', ARRAY['AFRICA-MALI','AFRICA-NIGER','AFRICA-BURKINA-FASO'], NULL, 81, true),
('eastern_congo_armed_groups', 'Armed group proliferation and territorial control', 'atomic', ARRAY['AFRICA-DRC','AFRICA-RWANDA','AFRICA-UGANDA','AFRICA-BURUNDI'], NULL, 82, true),
('m23_conflict', 'M23 insurgency and regional proxy dynamics', 'atomic', ARRAY['AFRICA-DRC','AFRICA-RWANDA','AFRICA-UGANDA','AFRICA-BURUNDI','NON-STATE-M23'], NULL, 83, true),
('critical_minerals_competition', 'Cobalt and coltan extraction and supply chain control', 'atomic', ARRAY['AFRICA-DRC','ASIA-PACIFIC-CHINA','AMERICAS-USA','AFRICA-RWANDA'], NULL, 84, true),
('regional_intervention_forces', 'MONUSCO, AU and regional military deployments', 'atomic', ARRAY['AFRICA-DRC','AFRICA-RWANDA','AFRICA-UGANDA','AFRICA-BURUNDI','AFRICA-ANGOLA'], NULL, 85, true),

-- ATOMIC FNs (AMERICAS)
('us_electoral_legitimacy', 'Electoral legitimacy and democratic backsliding', 'atomic', ARRAY['AMERICAS-USA'], NULL, 86, true),
('federal_state_authority', 'Federal versus state authority and governance', 'atomic', ARRAY['AMERICAS-USA'], NULL, 87, true),
('immigration_border_politics', 'Immigration and Mexico-US border politics', 'atomic', ARRAY['AMERICAS-USA','AMERICAS-MEXICO','AMERICAS-CENTRAL-AMERICA'], NULL, 88, true),
('culture_war_conflicts', 'National culture war conflicts and polarisation', 'atomic', ARRAY['AMERICAS-USA'], NULL, 89, true),
('technology_restrictions', 'Technology controls and semiconductor restrictions', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA'], NULL, 90, true),
('trade_and_tariffs', 'Trade and tariff competition', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA'], NULL, 91, true),
('investment_screening', 'Foreign investment restrictions and capital controls', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA'], NULL, 92, true),
('strategic_supply_chains', 'Strategic supply chain competition and dependencies', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA','ASIA-PACIFIC-JAPAN','ASIA-PACIFIC-SOUTH-KOREA','ASIA-PACIFIC-TAIWAN'], NULL, 93, true),
('nuclear_arms_control', 'Nuclear arms control and strategic stability', 'atomic', ARRAY['AMERICAS-USA','EUROPE-RUSSIA'], NULL, 94, true),
('election_interference', 'Election interference and information warfare', 'atomic', ARRAY['AMERICAS-USA','EUROPE-RUSSIA'], NULL, 95, true),
('arctic_competition', 'Arctic energy and territorial competition', 'atomic', ARRAY['AMERICAS-USA','EUROPE-RUSSIA'], NULL, 96, true),
('ukraine_proxy_war', 'Ukraine war and NATO proxy dynamics', 'atomic', ARRAY['AMERICAS-USA','EUROPE-RUSSIA','EUROPE-UKRAINE'], NULL, 97, true),
('venezuela_political_transition', 'Venezuela regime change and political transition', 'atomic', ARRAY['LATAM-VENEZUELA','AMERICAS-USA','AMERICAS-COLOMBIA','AMERICAS-BRAZIL'], NULL, 98, true),
('us_venezuela_relations', 'US-Venezuela confrontation and foreign policy', 'atomic', ARRAY['LATAM-VENEZUELA','AMERICAS-USA','AMERICAS-COLOMBIA'], NULL, 99, true),
('sanctions_and_oil', 'Sanctions, oil exports and economic pressure', 'atomic', ARRAY['LATAM-VENEZUELA','AMERICAS-USA'], NULL, 100, true),
('essequibo_dispute', 'Essequibo territorial dispute with Guyana', 'atomic', ARRAY['LATAM-VENEZUELA','LATAM-GUYANA','AMERICAS-BRAZIL','AMERICAS-USA'], NULL, 101, true),
('embargo_and_sanctions', 'US embargo and sanctions regime', 'atomic', ARRAY['LATAM-CUBA','AMERICAS-USA'], NULL, 102, true),
('migration_pressures', 'Migration and refugee pressures', 'atomic', ARRAY['LATAM-CUBA','AMERICAS-USA','AMERICAS-MEXICO'], NULL, 103, true),
('regime_survival', 'Cuban regime survival and external pressure', 'atomic', ARRAY['LATAM-CUBA','AMERICAS-USA'], NULL, 104, true),
('infrastructure_influence', 'Chinese Belt and Road versus US USAID influence', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA','AMERICAS-BRAZIL','AMERICAS-MEXICO','AMERICAS-PERU'], NULL, 105, true),
('trade_dependence', 'Trade dependence and manufacturing competition', 'atomic', ARRAY['AMERICAS-USA','ASIA-PACIFIC-CHINA','AMERICAS-BRAZIL','AMERICAS-MEXICO'], NULL, 106, true),
('strategic_resources', 'Lithium and strategic minerals competition', 'atomic', ARRAY['ASIA-PACIFIC-CHINA','AMERICAS-USA','AMERICAS-CHILE','AMERICAS-ARGENTINA','AMERICAS-BOLIVIA','AMERICAS-PERU'], NULL, 107, true),

-- ATOMIC FNs (ARCTIC)
('shipping_routes', 'Arctic shipping routes and passage competition', 'atomic', ARRAY['EUROPE-RUSSIA','AMERICAS-USA','EUROPE-NORWAY','AMERICAS-CANADA','ASIA-PACIFIC-CHINA','EUROPE-EU'], NULL, 108, true),
('greenland_control', 'Greenland strategic control and Arctic geopolitics', 'atomic', ARRAY['EUROPE-DENMARK','EUROPE-GREENLAND','AMERICAS-USA','AMERICAS-CANADA'], NULL, 109, true),
('military_presence', 'Arctic military build-up and NATO expansion', 'atomic', ARRAY['EUROPE-RUSSIA','AMERICAS-USA','EUROPE-NORWAY','AMERICAS-CANADA','EUROPE-FINLAND','EUROPE-SWEDEN'], NULL, 110, true),
('critical_resources', 'Arctic resources competition and climate access', 'atomic', ARRAY['EUROPE-RUSSIA','AMERICAS-USA','EUROPE-DENMARK','AMERICAS-CANADA','ASIA-PACIFIC-CHINA','EUROPE-EU','EUROPE-NORWAY'], NULL, 111, true)

ON CONFLICT (id) DO NOTHING;
