-- japan_china_theater: bilingual completeness fields (FN_THEATER_BUILD_SPEC 0a step 8)
--
-- name_de, description_en/_de, editorial_summary_en/_de for the theater and all five
-- atomics. Prose is neutral, factual, evergreen: no framing words ("militarism",
-- "coercion", "aggression" as fact), no motive attribution, no temporality beyond
-- dated historical facts. Contested labels stay in narratives_v2 only.
--
-- Modeled on arctic_theater / greenland_control / ukraine_battlefield description style.

BEGIN;

-- ============ THEATER ============
UPDATE friction_nodes SET
  name_de = 'Japanisch-chinesische strategische Rivalität',
  description_en = $$Strategic competition between Japan and China spanning five dimensions: the Senkaku/Diaoyu Islands and adjacent East China Sea waters, Japan's position on the Taiwan question, Japan's defense posture and the constitutional constraints on it, Chinese trade and travel measures applied to Japan, and disputes over the interpretation of wartime history. Each dimension carries its own vocabulary and set of actors, and the five interact with each other over time.$$,
  description_de = $$Strategischer Wettbewerb zwischen Japan und China entlang fünf Dimensionen: die Senkaku/Diaoyu-Inseln und die angrenzenden Gewässer des Ostchinesischen Meeres, Japans Position in der Taiwan-Frage, Japans Verteidigungshaltung und die verfassungsrechtlichen Beschränkungen dafür, chinesische Handels- und Reisemaßnahmen gegenüber Japan sowie Streitfragen zur Deutung der Kriegsgeschichte. Jede Dimension hat ein eigenes Vokabular und eigene Akteure, und die fünf Dimensionen wirken im Zeitverlauf aufeinander ein.$$,
  editorial_summary_en = $$Japan and China are Northeast Asia's two largest economies and have moved between periods of diplomatic engagement and acute friction since normalizing relations in 1972. Five distinct dimensions structure the relationship: a territorial dispute over the Senkaku/Diaoyu Islands and East China Sea maritime boundaries, patrolled by both countries' coast guards; Japan's statements and legal posture on a potential Taiwan Strait contingency, which China regards as bearing on its own sovereignty; Japan's defense budget, equipment policy and constitutional debate, conducted against the backdrop of China's military modernization; Chinese export licensing, travel advisories and import rules applied to Japanese trade and travel; and a set of disputes over the commemoration and interpretation of Japan's wartime conduct in China, including Yasukuni Shrine, the Nanjing Massacre, and the treatment of forced laborers and so-called "comfort women." Coverage of each dimension draws on distinct vocabularies and institutional actors, and diplomatic friction in one dimension has historically coincided with renewed attention to the others.$$,
  editorial_summary_de = $$Japan und China sind die beiden größten Volkswirtschaften Nordostasiens und bewegen sich seit der Normalisierung ihrer Beziehungen 1972 zwischen Phasen diplomatischer Annäherung und akuter Spannung. Fünf Dimensionen prägen das Verhältnis: ein Territorialstreit um die Senkaku/Diaoyu-Inseln und die Seegrenzen im Ostchinesischen Meer, patrouilliert von den Küstenwachen beider Länder; Japans Aussagen und rechtliche Haltung zu einem möglichen Konflikt in der Taiwanstraße, den China als seine eigene Souveränität betreffend ansieht; Japans Verteidigungshaushalt, Rüstungspolitik und Verfassungsdebatte vor dem Hintergrund der chinesischen Militärmodernisierung; chinesische Exportlizenzierung, Reisewarnungen und Importregeln gegenüber japanischem Handel und Reiseverkehr; sowie Streitfragen zum Gedenken an und zur Deutung von Japans Kriegsverhalten in China, darunter der Yasukuni-Schrein, das Massaker von Nanking sowie der Umgang mit Zwangsarbeitern und sogenannten "Trostfrauen". Die Berichterstattung zu jeder Dimension folgt eigenen Vokabularen und institutionellen Akteuren, und diplomatische Spannungen in einer Dimension gingen historisch häufig mit erneuter Aufmerksamkeit für die anderen einher.$$,
  updated_at = now()
WHERE id = 'japan_china_theater';

-- ============ japan_china_taiwan_question ============
UPDATE friction_nodes SET
  name_de = 'Japans Rolle in der Taiwan-Frage',
  description_en = $$Japan's public statements and legal posture on a potential military contingency in the Taiwan Strait, and China's diplomatic response to them. Covers debate over Japan's invocation of collective self-defense doctrine in relation to Taiwan, Taiwan Strait transits by Japanese naval vessels, and diplomatic incidents -- including at each country's embassy -- that followed public remarks on the subject.$$,
  description_de = $$Japans öffentliche Äußerungen und rechtliche Haltung zu einem möglichen militärischen Konflikt in der Taiwanstraße sowie Chinas diplomatische Reaktionen darauf. Umfasst die Debatte über Japans Berufung auf die Doktrin der kollektiven Selbstverteidigung im Zusammenhang mit Taiwan, Durchfahrten japanischer Marineschiffe durch die Taiwanstraße sowie diplomatische Zwischenfälle -- auch an den jeweiligen Botschaften beider Länder --, die auf öffentliche Äußerungen zu diesem Thema folgten.$$,
  editorial_summary_en = $$Japan's position on Taiwan sits close to the center of its relationship with China because Taiwan lies at the edge of Japan's own southwestern island chain: a Taiwan Strait contingency would occur within reach of Japanese territory and shipping lanes. Japanese officials have at times described such a contingency as a matter engaging Japan's own security, including under the country's collective self-defense doctrine, and Japanese naval vessels have transited the Taiwan Strait. China regards Taiwan as an internal matter and treats foreign statements on it as bearing on its own sovereignty; Japanese remarks on the subject have prompted formal protests, demands for retraction, and diplomatic friction including incidents at each country's embassy. The dispute is distinct from the wider Taiwan Strait confrontation between China, Taiwan and the United States: its terrain is the bilateral Japan-China relationship, triggered by and centered on Japan's own statements and posture.$$,
  editorial_summary_de = $$Japans Position zu Taiwan steht nahe am Zentrum seines Verhältnisses zu China, da Taiwan am Rand von Japans eigener südwestlicher Inselkette liegt: Ein Konflikt in der Taiwanstraße würde sich in Reichweite japanischen Territoriums und japanischer Schifffahrtswege abspielen. Japanische Regierungsvertreter haben einen solchen Konflikt zeitweise als Frage bezeichnet, die die eigene Sicherheit Japans berührt, auch im Rahmen der Doktrin der kollektiven Selbstverteidigung, und japanische Marineschiffe sind durch die Taiwanstraße gefahren. China betrachtet Taiwan als innere Angelegenheit und wertet ausländische Äußerungen dazu als seine eigene Souveränität berührend; japanische Aussagen zu diesem Thema haben förmliche Proteste, Rücknahmeforderungen und diplomatische Spannungen bis hin zu Zwischenfällen an den jeweiligen Botschaften beider Länder ausgelöst. Der Streit unterscheidet sich von der breiteren Konfrontation um die Taiwanstraße zwischen China, Taiwan und den USA: Sein Schauplatz ist die bilaterale japanisch-chinesische Beziehung, ausgelöst durch und zentriert auf Japans eigene Äußerungen und Haltung.$$,
  updated_at = now()
WHERE id = 'japan_china_taiwan_question';

-- ============ japan_defense_expansion ============
UPDATE friction_nodes SET
  name_de = 'Japans Verteidigungsausbau und die Beschränkungen des Nachkriegsmilitärs',
  description_en = $$Japan's defense budget, equipment policy and constitutional debate, considered in relation to China's military modernization. Covers rising defense spending, development of counter-strike missile capability, changes to Japan's arms export rules, and debate over Article 9 of Japan's postwar constitution and its Self-Defense Forces.$$,
  description_de = $$Japans Verteidigungshaushalt, Rüstungspolitik und Verfassungsdebatte im Verhältnis zur chinesischen Militärmodernisierung. Umfasst steigende Verteidigungsausgaben, die Entwicklung von Gegenschlag-Raketenfähigkeiten, Änderungen an Japans Regeln für Rüstungsexporte sowie die Debatte über Artikel 9 der japanischen Nachkriegsverfassung und die Selbstverteidigungsstreitkräfte.$$,
  editorial_summary_en = $$Japan's postwar constitution renounces the use of force to settle international disputes and for decades constrained its military to a strictly defensive posture. Since the 2010s, Japan has raised its defense budget, developed long-range counter-strike missile capability, eased restrictions on defense equipment exports, and debated formal revision of Article 9 -- changes officials in Tokyo describe as a response to a more severe regional security environment, including Chinese naval and air activity near Japan's southwestern islands. Chinese officials and state media describe the same changes as a departure from Japan's postwar pacifist commitments and connect them to Japan's wartime history. The debate involves Japan's Self-Defense Forces, its defense budget process, and its security relationships with the United States and other partners.$$,
  editorial_summary_de = $$Japans Nachkriegsverfassung verzichtet auf Gewaltanwendung zur Beilegung internationaler Streitigkeiten und beschränkte sein Militär über Jahrzehnte auf eine strikt defensive Ausrichtung. Seit den 2010er Jahren hat Japan seinen Verteidigungshaushalt erhöht, weitreichende Gegenschlag-Raketenfähigkeiten entwickelt, Beschränkungen bei Rüstungsexporten gelockert und eine förmliche Änderung von Artikel 9 debattiert -- Schritte, die Vertreter in Tokio als Reaktion auf ein verschärftes regionales Sicherheitsumfeld beschreiben, darunter chinesische Marine- und Luftaktivitäten nahe Japans südwestlichen Inseln. Chinesische Regierungsvertreter und Staatsmedien beschreiben dieselben Schritte als Abkehr von Japans pazifistischen Nachkriegsverpflichtungen und stellen sie in Bezug zu Japans Kriegsgeschichte. Die Debatte betrifft Japans Selbstverteidigungsstreitkräfte, den Verteidigungshaushaltsprozess sowie die Sicherheitsbeziehungen zu den USA und weiteren Partnern.$$,
  updated_at = now()
WHERE id = 'japan_defense_expansion';

-- ============ china_japan_economic_restrictions ============
UPDATE friction_nodes SET
  name_de = 'Chinesische Wirtschafts- und Reisebeschränkungen gegenüber Japan',
  description_en = $$Chinese trade, travel and regulatory measures affecting Japan, including rare-earth and dual-use export licensing, travel advisories affecting Chinese tourism to Japan, import rules on Japanese seafood, and the detention of Japanese nationals in China.$$,
  description_de = $$Chinesische Handels-, Reise- und Regulierungsmaßnahmen mit Auswirkungen auf Japan, darunter Exportlizenzierung für Seltene Erden und Güter mit doppeltem Verwendungszweck, Reisewarnungen mit Auswirkungen auf den chinesischen Tourismus nach Japan, Importregeln für japanische Meeresfrüchte sowie die Festnahme japanischer Staatsbürger in China.$$,
  editorial_summary_en = $$China supplies the large majority of the world's processed rare-earth minerals, an input Japanese manufacturers depend on, and has historically been Japan's largest source of inbound tourists. Both have become instruments in the bilateral relationship: Chinese export licensing on rare earths and related materials to Japan has tightened at points of diplomatic friction, Chinese authorities have issued travel advisories that preceded declines in tourist arrivals from China, and imports of Japanese seafood have at times been restricted. Japanese nationals, including company employees, have also been detained by Chinese authorities. Japanese and allied governments have responded by pursuing alternative mineral sources, including seabed extraction and recycling, and joint stockpiling arrangements with other countries.$$,
  editorial_summary_de = $$China liefert den überwiegenden Teil der weltweit verarbeiteten Seltenen Erden, ein Vorprodukt, von dem japanische Hersteller abhängig sind, und war historisch die größte Quelle einreisender Touristen für Japan. Beides ist zu einem Instrument der bilateralen Beziehung geworden: Chinesische Exportlizenzierung für Seltene Erden und verwandte Materialien nach Japan wurde an Punkten diplomatischer Spannung verschärft, chinesische Behörden erließen Reisewarnungen, denen Rückgänge bei den Touristenankünften aus China folgten, und Importe japanischer Meeresfrüchte wurden zeitweise beschränkt. Auch japanische Staatsbürger, darunter Unternehmensmitarbeiter, wurden von chinesischen Behörden festgenommen. Japan und verbündete Regierungen reagierten mit der Suche nach alternativen Rohstoffquellen, darunter Tiefseeabbau und Recycling, sowie gemeinsamen Bevorratungsvereinbarungen mit anderen Ländern.$$,
  updated_at = now()
WHERE id = 'china_japan_economic_restrictions';

-- ============ senkaku_diaoyu_islands (merged) ============
UPDATE friction_nodes SET
  name_de = 'Senkaku/Diaoyu-Inseln und maritime Spannungen im Ostchinesischen Meer',
  description_en = $$The territorial dispute over the Senkaku Islands, administered by Japan and known in China as the Diaoyu Islands, and the surrounding waters of the East China Sea. Covers China Coast Guard patrols and vessel movements in and near Japan's territorial waters and exclusive economic zone around the islands, and related maritime activity including survey vessels and undersea drilling structures.$$,
  description_de = $$Der Territorialstreit um die Senkaku-Inseln, die von Japan verwaltet werden und in China als Diaoyu-Inseln bekannt sind, sowie die umliegenden Gewässer des Ostchinesischen Meeres. Umfasst Patrouillen und Schiffsbewegungen der chinesischen Küstenwache in und nahe Japans Hoheitsgewässern und ausschließlicher Wirtschaftszone um die Inseln sowie damit verbundene maritime Aktivitäten wie Forschungsschiffe und Unterwasser-Bohrstrukturen.$$,
  editorial_summary_en = $$The Senkaku Islands, a small uninhabited island group in the East China Sea, have been administered by Japan since 1972 and are also claimed by China, which calls them the Diaoyu Islands, and by Taiwan. China Coast Guard vessels regularly enter the contiguous zone and, at intervals, the territorial waters around the islands; Japan's coast guard tracks these vessels and at times acts to expel them. The dispute also extends to the wider East China Sea, where the two countries' exclusive economic zone claims overlap and where survey vessels, fishing activity and gas-field infrastructure near the median line have periodically drawn protest from Japan. The islands lie near Japan's Yonaguni and Ishigaki islands, within the broader geography of the first island chain.$$,
  editorial_summary_de = $$Die Senkaku-Inseln, eine kleine unbewohnte Inselgruppe im Ostchinesischen Meer, werden seit 1972 von Japan verwaltet und werden zugleich von China, das sie Diaoyu-Inseln nennt, sowie von Taiwan beansprucht. Schiffe der chinesischen Küstenwache fahren regelmäßig in die Anschlusszone und zeitweise in die Hoheitsgewässer um die Inseln ein; Japans Küstenwache verfolgt diese Schiffe und schreitet mitunter ein, um sie zu vertreiben. Der Streit erstreckt sich zudem auf das weitere Ostchinesische Meer, wo sich die Ansprüche beider Länder auf die ausschließliche Wirtschaftszone überschneiden und wo Forschungsschiffe, Fischereiaktivitäten und Gasfeld-Infrastruktur nahe der Mittellinie wiederholt Proteste Japans ausgelöst haben. Die Inseln liegen nahe den japanischen Inseln Yonaguni und Ishigaki, innerhalb der weiteren Geografie der Ersten Inselkette.$$,
  updated_at = now()
WHERE id = 'senkaku_diaoyu_islands';

-- ============ japan_china_memory_wars ============
UPDATE friction_nodes SET
  name_de = 'Kriegsgeschichte und historisches Gedenken',
  description_en = $$Disputes over the commemoration and interpretation of Japan's wartime conduct in China, including visits and offerings to Yasukuni Shrine, the historical record of the Nanjing Massacre and other wartime events, the treatment of forced laborers and so-called "comfort women," and the restitution of cultural property removed from China during the war.$$,
  description_de = $$Streitfragen zum Gedenken an und zur Deutung von Japans Kriegsverhalten in China, darunter Besuche und Opfergaben am Yasukuni-Schrein, die historische Aufarbeitung des Massakers von Nanking und anderer Kriegsereignisse, der Umgang mit Zwangsarbeitern und sogenannten "Trostfrauen" sowie die Rückgabe von Kulturgütern, die während des Krieges aus China entfernt wurden.$$,
  editorial_summary_en = $$Japan's conduct during its wartime occupation of parts of China, including the 1937 Nanjing Massacre, the use of forced labor, and the coercion of women into wartime brothels, remains a subject of dispute between the two countries' historical accounts. Visits or ritual offerings by Japanese officials to Yasukuni Shrine, which honors Japan's war dead including convicted war criminals, routinely draw formal protest from China. Related disputes include denial or minimization of wartime events by some Japanese public figures, the restoration of wartime military rank titles, unexploded or abandoned wartime chemical weapons still being cleared in China, and calls for Japan to return cultural relics removed during the war. These disputes recur independently of the theater's other dimensions and are raised by Chinese officials and state media at points of broader diplomatic friction.$$,
  editorial_summary_de = $$Japans Verhalten während der Besetzung von Teilen Chinas im Krieg, darunter das Massaker von Nanking 1937, der Einsatz von Zwangsarbeitern und die Zwangsrekrutierung von Frauen für Kriegsbordelle, bleibt zwischen den historischen Darstellungen beider Länder umstritten. Besuche oder rituelle Opfergaben japanischer Regierungsvertreter am Yasukuni-Schrein, der Japans Kriegstote einschließlich verurteilter Kriegsverbrecher ehrt, lösen regelmäßig förmliche Proteste Chinas aus. Verwandte Streitfragen umfassen die Leugnung oder Verharmlosung von Kriegsereignissen durch einzelne japanische Persönlichkeiten des öffentlichen Lebens, die Wiedereinführung von Dienstgradbezeichnungen aus der Kriegszeit, in China noch zu beseitigende zurückgelassene Chemiewaffen aus der Kriegszeit sowie Forderungen an Japan, während des Krieges entfernte Kulturgüter zurückzugeben. Diese Streitfragen treten unabhängig von den anderen Dimensionen des Themenfelds wiederholt auf und werden von chinesischen Regierungsvertretern und Staatsmedien an Punkten breiterer diplomatischer Spannung aufgegriffen.$$,
  updated_at = now()
WHERE id = 'japan_china_memory_wars';

COMMIT;
