-- Add tracking columns for incremental processing in Phases 4.1 and 4.5
-- This enables event-driven processing - only re-process CTMs with new content

-- Phase 4.1: Topic Aggregation tracking
ALTER TABLE ctm ADD COLUMN IF NOT EXISTS last_aggregated_at TIMESTAMPTZ;
ALTER TABLE ctm ADD COLUMN IF NOT EXISTS title_count_at_aggregation INTEGER;

-- Phase 4.5: CTM Summary tracking
ALTER TABLE ctm ADD COLUMN IF NOT EXISTS last_summary_at TIMESTAMPTZ;
ALTER TABLE ctm ADD COLUMN IF NOT EXISTS event_count_at_summary INTEGER;

-- Index for efficient lookup of CTMs needing aggregation
CREATE INDEX IF NOT EXISTS idx_ctm_needs_aggregation
ON ctm (last_aggregated_at, title_count)
WHERE is_frozen = false;

-- Index for efficient lookup of CTMs needing summary regeneration
CREATE INDEX IF NOT EXISTS idx_ctm_needs_summary
ON ctm (last_summary_at, event_count_at_summary)
WHERE is_frozen = false;

COMMENT ON COLUMN ctm.last_aggregated_at IS 'When this CTM was last processed by Phase 4.1 topic aggregation';
COMMENT ON COLUMN ctm.title_count_at_aggregation IS 'Title count when last aggregated - used to detect new content';
COMMENT ON COLUMN ctm.last_summary_at IS 'When this CTM summary was last generated by Phase 4.5';
COMMENT ON COLUMN ctm.event_count_at_summary IS 'Event count when last summarized - used to detect new clusters';
