-- US-Russia theater: bilingual completeness fields (§6). 2026-07-19.
-- description_* and editorial_summary_* for the theater and all three atomics.
-- Descriptions are neutral and evergreen (feedback_fn_descriptions_neutral);
-- framing lives only in narratives_v2. Editorial summaries state the current
-- phase, which is what dates them -- written against the Jan-Jul 2026 corpus.

BEGIN;

UPDATE friction_nodes SET
  description_en = 'The bilateral relationship between the United States and Russia, treated as a subject in its own right: the diplomatic channel between Washington and Moscow, the American sanctions instruments applied to Russian energy and finance, and the nuclear arms-control framework the two states share. Distinct from the war in Ukraine, which is covered by its own theater, though the two intersect constantly.',
  description_de = 'Das bilaterale Verhältnis zwischen den Vereinigten Staaten und Russland als eigenständiger Gegenstand: der diplomatische Kanal zwischen Washington und Moskau, die amerikanischen Sanktionsinstrumente gegenüber russischer Energie und Finanzwirtschaft sowie der gemeinsame nukleare Rüstungskontrollrahmen. Abzugrenzen vom Krieg in der Ukraine, der ein eigenes Theater hat, auch wenn sich beide ständig überschneiden.',
  editorial_summary_en = 'The relationship is in an unsettled thaw. Working contacts have been rebuilt -- envoy visits to Moscow, a resumed high-level military channel, repeated leader-level calls -- while Washington has repeatedly issued and withdrawn waivers on Russian oil, drawing objections from European and British partners still tightening enforcement. The last nuclear warhead limits lapsed with New START in February 2026, leaving the two arsenals unconstrained for the first time in decades. Coverage divides less along US-versus-Russia lines than over how much accommodation of Moscow is warranted, with Western outlets on both sides of that question and third-country buyers treating the whole framework as conditions to navigate.',
  editorial_summary_de = 'Das Verhältnis befindet sich in einem ungefestigten Tauwetter. Arbeitskontakte wurden wieder aufgebaut -- Besuche von Sondergesandten in Moskau, ein wieder aufgenommener militärischer Kanal auf hoher Ebene, wiederholte Telefonate auf Führungsebene -- während Washington Ausnahmegenehmigungen für russisches Öl mehrfach erteilte und zurücknahm, was Einwände europäischer und britischer Partner hervorrief, die die Durchsetzung weiter verschärfen. Die letzten nuklearen Obergrenzen liefen im Februar 2026 mit New START aus; erstmals seit Jahrzehnten sind beide Arsenale unbegrenzt. Die Berichterstattung teilt sich weniger entlang der Linie USA gegen Russland als an der Frage, wie viel Entgegenkommen gegenüber Moskau gerechtfertigt ist.',
  updated_at = NOW()
WHERE id = 'us_russia_theater';

UPDATE friction_nodes SET
  description_en = 'American sanctions on Russian energy and finance used as an adjustable instrument: waivers, general licences and exemptions issued, extended, allowed to lapse and reinstated, and the effect of those decisions on Russian export revenue, on third-country buyers, and on coordination with European partners. Distinct from European enforcement action against the shadow fleet, which sits in the Russia-Europe theater.',
  description_de = 'Amerikanische Sanktionen gegen russische Energie und Finanzwirtschaft als verstellbares Instrument: Ausnahmegenehmigungen, Generallizenzen und Befreiungen, die erteilt, verlängert, auslaufen gelassen und wieder in Kraft gesetzt werden, sowie deren Wirkung auf russische Exporteinnahmen, auf Käufer in Drittstaaten und auf die Abstimmung mit europäischen Partnern. Abzugrenzen von der europäischen Durchsetzung gegen die Schattenflotte, die im Theater Russland-Europa liegt.',
  editorial_summary_en = 'Waiver policy has moved repeatedly through 2026. Washington eased restrictions on cargoes already at sea, granted and then extended a 30-day waiver covering Indian purchases, exempted Rosneft''s German operations and approved a Lukoil carve-out for Bulgaria, before letting waivers lapse and signalling further changes. Each move drew objections from Kyiv and from European and British partners, and congressional pressure for a new sanctions bill persists. Indian and other buyers have continued purchasing throughout, treating the waivers as confirmation the restrictions were unenforceable rather than as permission.',
  editorial_summary_de = 'Die Ausnahmepolitik hat sich 2026 mehrfach geändert. Washington lockerte Beschränkungen für bereits auf See befindliche Ladungen, gewährte und verlängerte eine 30-Tage-Ausnahme für indische Käufe, befreite das Deutschlandgeschäft von Rosneft und genehmigte eine Lukoil-Ausnahme für Bulgarien, ließ Ausnahmen dann auslaufen und kündigte weitere Änderungen an. Jeder Schritt rief Einwände aus Kyjiw sowie von europäischen und britischen Partnern hervor; im Kongress hält der Druck für ein neues Sanktionsgesetz an. Indische und andere Käufer kauften durchgehend weiter.',
  updated_at = NOW()
WHERE id = 'us_russia_sanctions_leverage';

UPDATE friction_nodes SET
  description_en = 'The working mechanism of the US-Russia relationship: envoy missions, foreign-minister contacts, leader-level calls, summit formats and the state of diplomatic and military channels between Washington and Moscow. Covers the machinery of contact itself rather than the substance of the Ukraine negotiations, which has its own node.',
  description_de = 'Der Arbeitsmechanismus des Verhältnisses zwischen den USA und Russland: Missionen von Sondergesandten, Kontakte der Außenminister, Telefonate auf Führungsebene, Gipfelformate sowie der Zustand der diplomatischen und militärischen Kanäle zwischen Washington und Moskau. Erfasst wird das Kontaktgeschehen selbst, nicht der Inhalt der Ukraine-Verhandlungen, für den ein eigener Knoten besteht.',
  editorial_summary_en = 'Contact is far denser than at any point since 2022. US envoys have travelled repeatedly to Moscow, the two militaries have re-established high-level communication, foreign ministers speak by phone, and leader-level calls have become routine enough to include congratulatory exchanges. Moscow presents this as overdue recognition of parity while simultaneously accusing Washington of stalling and issuing ultimatums -- the two Kremlin registers run side by side. Western coverage of the same events is comparatively thin as bilateral reporting, because Western outlets largely file these contacts as Ukraine-war news.',
  editorial_summary_de = 'Die Kontaktdichte ist so hoch wie zu keinem Zeitpunkt seit 2022. US-Sondergesandte reisten mehrfach nach Moskau, beide Streitkräfte stellten die Kommunikation auf hoher Ebene wieder her, die Außenminister telefonieren, und Gespräche auf Führungsebene sind so alltäglich geworden, dass sie Glückwünsche einschließen. Moskau stellt dies als überfällige Anerkennung der Ebenbürtigkeit dar und wirft Washington zugleich Hinhalten und Ultimaten vor -- beide Register laufen nebeneinander. Die westliche Berichterstattung über dieselben Ereignisse ist als bilaterale Berichterstattung vergleichsweise dünn, da westliche Medien diese Kontakte überwiegend als Nachrichten zum Ukrainekrieg einordnen.',
  updated_at = NOW()
WHERE id = 'us_russia_bilateral_channel';

UPDATE friction_nodes SET
  description_en = 'The nuclear arms-control relationship between the United States and Russia: treaty limits on deployed warheads and delivery systems, verification and inspection arrangements, strategic-stability talks, missile-defence programmes and novel delivery systems that fall outside existing frameworks.',
  description_de = 'Das nukleare Rüstungskontrollverhältnis zwischen den Vereinigten Staaten und Russland: vertragliche Obergrenzen für stationierte Sprengköpfe und Trägersysteme, Verifikations- und Inspektionsregelungen, Gespräche über strategische Stabilität, Raketenabwehrprogramme sowie neuartige Trägersysteme außerhalb bestehender Rahmen.',
  editorial_summary_en = 'New START expired on 4 February 2026, ending the last treaty limits on the two largest nuclear arsenals and with them the inspection and data-exchange regime. The UN called the lapse a grave moment and coverage widely anticipates an unconstrained arms race. Talks on a successor have not stopped -- proposals have been floated and reported as close to agreement more than once, and China has publicly urged the two to resume strategic-stability dialogue -- but nothing has been concluded. Moscow attributes the collapse to rejected proposals and to the Golden Dome missile-defence programme; Washington points to Russian systems built outside any treaty''s scope.',
  editorial_summary_de = 'New START lief am 4. Februar 2026 aus und beendete die letzten vertraglichen Obergrenzen für die beiden größten Nukleararsenale und damit auch das Inspektions- und Datenaustauschregime. Die UN nannte dies einen ernsten Moment; die Berichterstattung erwartet überwiegend ein ungebremstes Wettrüsten. Gespräche über einen Nachfolger laufen weiter -- Vorschläge wurden mehrfach als kurz vor einer Einigung berichtet, und China forderte beide Seiten öffentlich zur Wiederaufnahme des Dialogs über strategische Stabilität auf -- abgeschlossen wurde nichts. Moskau führt den Zusammenbruch auf zurückgewiesene Vorschläge und das Raketenabwehrprogramm Golden Dome zurück; Washington verweist auf russische Systeme außerhalb jedes Vertragsrahmens.',
  updated_at = NOW()
WHERE id = 'us_russia_arms_control';

COMMIT;
