-- Reader-facing content rewrite for the 5 active friction nodes (Iran cluster).
-- Neutral journalistic prose, no in-house terminology. Centroid scopes restricted
-- to MIDEAST-* per editorial decision (drop US/UK/FR; add MIDEAST-GULF where the
-- smaller Gulf states are involved).
-- 2026-05-12.

BEGIN;

-- =========================================================================
-- iran_theater (umbrella) — long-term confrontation involving Iran
-- =========================================================================
UPDATE friction_nodes
SET name_en = 'Iran in regional and international confrontation',
    name_de = 'Iran in regionalen und internationalen Spannungen',
    description_en = 'Long-running political and military tensions between Iran and a coalition of regional and Western actors. Multiple specific flashpoints — the nuclear programme, allied armed groups across the region, maritime disputes in the Persian Gulf, and strikes on Gulf states — sit beneath this broader confrontation.',
    description_de = 'Langjaehrige politische und militaerische Spannungen zwischen Iran und einer Koalition aus regionalen und westlichen Akteuren. Unter diesem uebergreifenden Konflikt liegen spezifische Brennpunkte: das Atomprogramm, verbuendete bewaffnete Gruppen in der Region, maritime Streitigkeiten im Persischen Golf und Angriffe auf Golfstaaten.',
    editorial_summary_en = 'For more than four decades, Iran has been at the centre of intersecting tensions in the Middle East. The Islamic Republic governs a state of roughly 90 million people, sits on major oil and gas reserves, and maintains ties with armed political movements in Lebanon, Syria, Iraq, Yemen and the Palestinian territories. The United States, Israel and several Gulf monarchies treat Iran''s regional posture, nuclear programme, and missile and drone arsenal as primary security threats; Iran and its allies frame the same activities as defence of sovereignty and resistance to foreign domination of the region. The confrontation has produced sanctions regimes, covert operations, intermittent open conflict, and a long-running diplomatic track. This page groups the more specific files — nuclear, allied armed groups, the Strait of Hormuz, and strikes on Gulf states — that together make up the confrontation.',
    editorial_summary_de = 'Iran steht seit mehr als vier Jahrzehnten im Zentrum sich ueberschneidender Spannungen im Nahen Osten. Die Islamische Republik regiert einen Staat mit rund 90 Millionen Menschen, verfuegt ueber grosse Oel- und Gasreserven und unterhaelt Verbindungen zu bewaffneten politischen Bewegungen im Libanon, in Syrien, im Irak, im Jemen und in den palaestinensischen Gebieten. Die Vereinigten Staaten, Israel und mehrere Golfmonarchien betrachten Irans regionale Politik, sein Atomprogramm sowie sein Raketen- und Drohnenarsenal als zentrale Sicherheitsbedrohungen; Iran und seine Verbuendeten stellen dieselben Aktivitaeten als Verteidigung der Souveraenitaet und Widerstand gegen auslaendische Dominanz dar. Aus dieser Konfrontation sind Sanktionsregime, verdeckte Operationen, periodische offene Konflikte und ein anhaltender diplomatischer Prozess hervorgegangen. Diese Seite buendelt die spezifischeren Akten — Nuklear, verbuendete bewaffnete Gruppen, die Strasse von Hormuz und Angriffe auf Golfstaaten — die gemeinsam diese Konfrontation ausmachen.',
    centroid_ids = ARRAY['MIDEAST-IRAN']
WHERE id = 'iran_theater';

-- =========================================================================
-- iran_nuclear_program
-- =========================================================================
UPDATE friction_nodes
SET name_en = 'Iran''s nuclear programme',
    name_de = 'Irans Atomprogramm',
    description_en = 'Disputed nature, scope and aims of Iran''s uranium-enrichment and related nuclear activities, and the diplomatic and military responses to them.',
    description_de = 'Umstrittene Natur, Umfang und Ziele von Irans Urananreicherung und verwandten nuklearen Aktivitaeten sowie die diplomatischen und militaerischen Reaktionen darauf.',
    editorial_summary_en = 'Iran''s nuclear programme has been a subject of international dispute for more than two decades. Iran maintains that its enrichment activities are for civilian energy and medical purposes and are protected under the Non-Proliferation Treaty. The United States, Israel and several European governments argue that Iran''s enrichment levels, centrifuge capacity, and known and suspected facilities (Natanz, Fordow, Arak, Isfahan, Parchin) bring it close to a weapons-grade capability and require negotiated limits, intrusive inspection, and — in some readings — military action. The 2015 Joint Comprehensive Plan of Action set limits in exchange for sanctions relief; its collapse, repeated rounds of negotiation, IAEA inspection reports, covert sabotage and assassinations (notably the killing of nuclear scientist Mohsen Fakhrizadeh in 2020), and direct strikes on nuclear infrastructure all sit within this file.',
    editorial_summary_de = 'Irans Atomprogramm ist seit mehr als zwei Jahrzehnten Gegenstand internationaler Auseinandersetzungen. Iran erklaert, seine Anreicherungstaetigkeiten dienten zivilen Energie- und medizinischen Zwecken und seien durch den Atomwaffensperrvertrag geschuetzt. Die Vereinigten Staaten, Israel und mehrere europaeische Regierungen argumentieren, dass Anreicherungsgrade, Zentrifugenkapazitaet und bekannte oder vermutete Anlagen (Natanz, Fordow, Arak, Isfahan, Parchin) Iran in die Naehe einer waffenfaehigen Kapazitaet bringen und Verhandlungslimits, eingreifende Inspektionen und in einigen Lesarten militaerische Massnahmen erfordern. Der Gemeinsame Umfassende Aktionsplan von 2015 (JCPOA) setzte Grenzen im Austausch gegen Sanktionserleichterungen; sein Scheitern, wiederholte Verhandlungsrunden, IAEA-Inspektionsberichte, verdeckte Sabotage und Toetungen (insbesondere die Ermordung des Nuklearwissenschaftlers Mohsen Fakhrizadeh im Jahr 2020) sowie direkte Angriffe auf nukleare Infrastruktur fallen alle in diese Akte.',
    centroid_ids = ARRAY['MIDEAST-IRAN','MIDEAST-ISRAEL']
WHERE id = 'iran_nuclear_program';

-- =========================================================================
-- iran_proxy_network
-- =========================================================================
UPDATE friction_nodes
SET name_en = 'Iran-linked armed groups in the region',
    name_de = 'Mit Iran verbuendete bewaffnete Gruppen in der Region',
    description_en = 'The role and scope of armed groups across the Middle East — including Hezbollah, Hamas, the Houthi movement, and Iraqi militias — and their relationships with Iranian state institutions.',
    description_de = 'Rolle und Reichweite bewaffneter Gruppen im Nahen Osten — darunter Hisbollah, Hamas, die Huthi-Bewegung und irakische Milizen — sowie ihre Beziehungen zu iranischen Staatsinstitutionen.',
    editorial_summary_en = 'Across Lebanon, Syria, the Palestinian territories, Iraq and Yemen, a network of armed organisations maintain political, military and financial ties with Iran. Hezbollah in Lebanon, Hamas and Palestinian Islamic Jihad in the Palestinian territories, the Houthi movement (Ansar Allah) in Yemen, and Iraqi groups including the Popular Mobilisation Forces, Kata''ib Hezbollah, Asaib Ahl al-Haq and Harakat al-Nujaba are among the largest. Iran''s Islamic Revolutionary Guard Corps and its Quds Force operate as the principal channels of training, financing and weapons transfers. Israel, the United States, Saudi Arabia and several Western states characterise these groups as components of an Iran-directed terror infrastructure; Iran and its allies describe the network as an axis of resistance to Israeli and Western military presence in the region. Their activities span cross-border missile and rocket fire, drone strikes, political mobilisation, governance functions, and direct confrontation with regional adversaries.',
    editorial_summary_de = 'Im Libanon, in Syrien, in den palaestinensischen Gebieten, im Irak und im Jemen unterhaelt ein Netzwerk bewaffneter Organisationen politische, militaerische und finanzielle Verbindungen zu Iran. Zu den groessten zaehlen die Hisbollah im Libanon, Hamas und der Palaestinensische Islamische Dschihad in den palaestinensischen Gebieten, die Huthi-Bewegung (Ansar Allah) im Jemen sowie irakische Gruppen wie die Volksmobilisierungskraefte, Kataib Hisbollah, Asaib Ahl al-Haq und Harakat al-Nujaba. Die iranischen Revolutionsgarden und ihre Quds-Truppe sind die wichtigsten Kanaele fuer Ausbildung, Finanzierung und Waffenlieferungen. Israel, die Vereinigten Staaten, Saudi-Arabien und mehrere westliche Staaten charakterisieren diese Gruppen als Bestandteile einer von Iran gelenkten Terror-Infrastruktur; Iran und seine Verbuendeten beschreiben das Netzwerk als Achse des Widerstands gegen die israelische und westliche Militaerpraesenz in der Region. Ihre Aktivitaeten umfassen grenzueberschreitenden Raketen- und Drohnenbeschuss, politische Mobilisierung, Regierungsfunktionen und direkte Konfrontation mit regionalen Gegnern.',
    centroid_ids = ARRAY['MIDEAST-IRAN','MIDEAST-LEVANT','MIDEAST-PALESTINE','MIDEAST-YEMEN','MIDEAST-IRAQ','MIDEAST-ISRAEL']
WHERE id = 'iran_proxy_network';

-- =========================================================================
-- strait_of_hormuz_sovereignty
-- =========================================================================
UPDATE friction_nodes
SET name_en = 'Strait of Hormuz and Persian Gulf maritime security',
    name_de = 'Strasse von Hormuz und maritime Sicherheit im Persischen Golf',
    description_en = 'Competing claims over Iranian territorial waters, freedom of navigation through one of the world''s busiest oil chokepoints, and the military presence of foreign navies in the Persian Gulf.',
    description_de = 'Konkurrierende Anspruechen auf iranische Hoheitsgewaesser, Freiheit der Schifffahrt durch einen der wichtigsten Oel-Engpaesse der Welt und die militaerische Praesenz auslaendischer Marinen im Persischen Golf.',
    editorial_summary_en = 'The Strait of Hormuz is a 39-kilometre-wide passage between Iran and Oman through which roughly a fifth of the world''s seaborne oil and a large share of liquefied natural gas transit. Iran considers the strait part of its territorial waters and maintains a substantial naval and asymmetric capability there through the Islamic Revolutionary Guard Corps navy operating from bases at Bandar Abbas and on the islands of Qeshm and Larak. Foreign navies — principally the United States Fifth Fleet headquartered in Bahrain, alongside United Kingdom, French and other coalition vessels — assert the strait as an international waterway under the UN Convention on the Law of the Sea and conduct freedom-of-navigation operations. The Saudi Arabian and Emirati economies depend on the strait for their oil exports. Periodic tanker seizures, military escalation, threats by Iranian officials to close the strait, and tensions over shipping route alternatives shape this file.',
    editorial_summary_de = 'Die Strasse von Hormuz ist eine 39 Kilometer breite Passage zwischen Iran und Oman, durch die etwa ein Fuenftel des weltweit auf dem Seeweg transportierten Oels und ein grosser Teil des Fluessigerdgases verlaufen. Iran betrachtet die Strasse als Teil seiner Hoheitsgewaesser und unterhaelt dort durch die Marine der Revolutionsgarden mit Stuetzpunkten in Bandar Abbas sowie auf den Inseln Qeshm und Larak erhebliche militaerische und asymmetrische Faehigkeiten. Auslaendische Marinen — vor allem die in Bahrain stationierte Fuenfte US-Flotte sowie britische, franzoesische und andere Koalitionsverbaende — sehen die Strasse als internationale Wasserstrasse im Sinne des UN-Seerechtsuebereinkommens und fuehren Freedom-of-Navigation-Operationen durch. Die Wirtschaft Saudi-Arabiens und der VAE haengt fuer ihre Oelexporte von dieser Strasse ab. Periodische Tankerueberfaelle, militaerische Eskalation, Drohungen iranischer Stellen mit einer Schliessung der Strasse und Spannungen ueber alternative Schifffahrtsrouten praegen diese Akte.',
    centroid_ids = ARRAY['MIDEAST-IRAN','MIDEAST-SAUDI','MIDEAST-GULF']
WHERE id = 'strait_of_hormuz_sovereignty';

-- =========================================================================
-- gulf_attacks_on_arab_states
-- =========================================================================
UPDATE friction_nodes
SET name_en = 'Missile and drone strikes against Gulf states and military bases',
    name_de = 'Raketen- und Drohnenangriffe auf Golfstaaten und Militaerbasen',
    description_en = 'Periodic missile and drone attacks targeting Saudi Arabian and Emirati infrastructure and United States military installations across the wider Gulf region.',
    description_de = 'Periodische Raketen- und Drohnenangriffe auf saudische und emiratische Infrastruktur sowie US-amerikanische Militaereinrichtungen in der weiteren Golfregion.',
    editorial_summary_en = 'Saudi Arabia, the United Arab Emirates and US military installations across the Gulf have been the target of repeated missile and drone strikes. Notable incidents include the September 2019 attack on Saudi Aramco''s Abqaiq and Khurais oil-processing facilities, which briefly halved Saudi oil exports; 2022 strikes against UAE air defences and the Al Taweelah terminal; the January 2024 Tower 22 attack on a US base near the Jordanian-Syrian border; and successive waves of strikes against Al Udeid Air Base in Qatar, Al Asad Air Base in Iraq and Camp Arifjan in Kuwait during periods of escalation. The Houthi movement in Yemen and Iranian state forces are typically identified as responsible. Targets describe these strikes as state-sponsored aggression by Iran and its allies; the responsible side frames them as legitimate retaliation against host countries supporting US and Israeli military operations.',
    editorial_summary_de = 'Saudi-Arabien, die Vereinigten Arabischen Emirate und US-amerikanische Militaereinrichtungen am Golf waren Ziel wiederholter Raketen- und Drohnenangriffe. Zu den bedeutendsten Vorfaellen zaehlen der Angriff vom September 2019 auf die Oelverarbeitungsanlagen von Saudi Aramco in Abqaiq und Khurais, der die saudischen Oelexporte kurzzeitig halbierte; Angriffe auf VAE-Luftabwehr und das Terminal Al Taweelah im Jahr 2022; der Angriff auf den US-Stuetzpunkt Tower 22 nahe der jordanisch-syrischen Grenze im Januar 2024; sowie aufeinanderfolgende Angriffswellen gegen den Luftwaffenstuetzpunkt Al Udeid in Katar, Al Asad im Irak und Camp Arifjan in Kuwait in Eskalationsphasen. Die Huthi-Bewegung im Jemen und iranische Streitkraefte werden gewoehnlich als verantwortlich genannt. Zielstaaten beschreiben diese Angriffe als staatlich gesponserte Aggression durch Iran und seine Verbuendeten; die durchfuehrende Seite stellt sie als legitime Vergeltung gegen Gaststaaten dar, die US- und israelische Militaeroperationen unterstuetzen.',
    centroid_ids = ARRAY['MIDEAST-IRAN','MIDEAST-YEMEN','MIDEAST-SAUDI','MIDEAST-GULF','MIDEAST-ISRAEL']
WHERE id = 'gulf_attacks_on_arab_states';

COMMIT;
