-- Ukraine atomic FNs: name_de + description + editorial_summary (EN/DE) (2026-07-13)
--
-- Fills the localized friction_nodes copy (name_de, description_en/de,
-- editorial_summary_en/de) for the Ukraine theater's remaining atomic members
-- -- a complete two-language field set per FN.
-- These render on each FN's own page (editorial_summary as lead, description as
-- "What is contested") and in the theater "Specific conflicts in this zone"
-- member cards. ukraine_infrastructure_war already had them; ukraine_proxy_war
-- is inactive and excluded. DE uses ASCII transliteration (ae/oe/ue/ss) to
-- match existing rows. Idempotent: guarded UPDATEs by id.

BEGIN;

-- 1. Battlefield operations and territorial control
UPDATE friction_nodes SET
  name_de = 'Kampfhandlungen und territoriale Kontrolle',
  description_en = 'The ground war itself: the contest for the front line and the territory behind it. Russian offensives and Ukrainian defense and counter-attacks across Donbas, Zaporizhzhia and the border oblasts -- captured villages, fortified towns, force generation and the daily attrition that moves the map by metres. Each side reads the same advance as either liberation or aggression, and that contest over meaning sits on top of the physical one.',
  description_de = 'Der Bodenkrieg selbst: der Kampf um die Frontlinie und das Land dahinter. Russische Offensiven sowie ukrainische Verteidigung und Gegenangriffe im Donbass, in Saporischschja und den Grenzregionen -- eroberte Doerfer, befestigte Staedte, Truppenaufwuchs und die taegliche Zermuerbung, die die Karte um Meter verschiebt. Jede Seite liest denselben Vorstoss entweder als Befreiung oder als Aggression, und dieser Streit um die Bedeutung liegt ueber dem physischen.',
  editorial_summary_en = 'This is the war at its most literal: kilometres of front, fortified towns that change hands over months, and an attritional grind that consumes men and materiel faster than either side admits. Russia presses a slow, costly advance framed as the liberation of historically Russian land; Ukraine fights a defensive war of national survival, trading space for time and striking back where it can. The battlefield''s vocabulary -- Pokrovsk, Kupiansk, Avdiivka, the Kursk incursion, mobilisation and casualty figures -- is where the war''s cost is counted most directly. Because the same kilometre is "liberated" by one side and "occupied" by the other, the ground war is also a contest over narrative: whose advance is legitimate, whose losses are catastrophic, and whether the line can move at all. Nothing else in the theatre -- aid, diplomacy, strikes -- makes sense except in relation to what is happening here.',
  editorial_summary_de = 'Dies ist der Krieg in seiner buchstaeblichsten Form: Kilometer Front, befestigte Staedte, die ueber Monate den Besitzer wechseln, und ein zermuerbender Abnutzungskampf, der Menschen und Material schneller verbraucht, als beide Seiten zugeben. Russland treibt einen langsamen, verlustreichen Vormarsch voran, gerahmt als Befreiung historisch russischen Landes; die Ukraine fuehrt einen defensiven Ueberlebenskrieg, tauscht Raum gegen Zeit und schlaegt zurueck, wo sie kann. Das Vokabular des Schlachtfelds -- Pokrowsk, Kupjansk, Awdijiwka, der Vorstoss bei Kursk, Mobilmachung und Verlustzahlen -- ist der Ort, an dem die Kosten des Krieges am unmittelbarsten gezaehlt werden. Weil derselbe Kilometer von der einen Seite "befreit" und von der anderen "besetzt" wird, ist der Bodenkrieg auch ein Streit ums Narrativ: wessen Vormarsch legitim ist, wessen Verluste katastrophal sind und ob sich die Linie ueberhaupt bewegen laesst. Nichts anderes im Kriegsschauplatz -- Hilfe, Diplomatie, Angriffe -- ergibt Sinn ausser im Verhaeltnis zu dem, was hier geschieht.'
WHERE id = 'ukraine_battlefield';

-- 2. Western military and economic aid to Ukraine
UPDATE friction_nodes SET
  name_de = 'Westliche Militaer- und Wirtschaftshilfe fuer die Ukraine',
  description_en = 'The flow of Western military, financial and industrial support that keeps Ukraine in the fight -- weapons packages, air defense, artillery and ammunition, budget financing and the fight over frozen Russian assets. The contested question is not only how much to send but what it buys: a sustainable defense, or an open-ended commitment that deepens the West''s exposure.',
  description_de = 'Der Strom westlicher militaerischer, finanzieller und industrieller Unterstuetzung, der die Ukraine im Kampf haelt -- Waffenpakete, Luftverteidigung, Artillerie und Munition, Haushaltsfinanzierung und der Streit um eingefrorene russische Vermoegenswerte. Die umstrittene Frage ist nicht nur, wie viel geschickt wird, sondern was es erkauft: eine tragfaehige Verteidigung oder eine unbefristete Verpflichtung, die die Exponierung des Westens vertieft.',
  editorial_summary_en = 'Ukraine cannot fight without external supply, which makes Western aid a front in its own right -- fought in the parliaments and treasuries of Washington, Brussels, Berlin, London and Paris as much as on the battlefield. Supporters frame aid as the cheapest possible investment in European security: sustaining a democracy under attack and degrading a strategic rival without a single NATO soldier. Critics -- from the American right to Global South commentators -- read the same flows as escalation, proxy waste and a subsidy to prolong an unwinnable war. The specifics matter: which systems (air-defense interceptors, long-range strike, F-16s), how they are financed (direct grants, loans, the disputed use of immobilised Russian central-bank assets), and whether European industry can backfill what American politics may withdraw. Aid is where the war''s staying power is ultimately decided -- and where Western unity is most visibly tested.',
  editorial_summary_de = 'Die Ukraine kann ohne externen Nachschub nicht kaempfen, was die westliche Hilfe zu einer eigenen Front macht -- ausgetragen in den Parlamenten und Finanzministerien von Washington, Bruessel, Berlin, London und Paris ebenso wie auf dem Schlachtfeld. Befuerworter rahmen Hilfe als die billigstmoegliche Investition in europaeische Sicherheit: eine angegriffene Demokratie stuetzen und einen strategischen Rivalen schwaechen, ohne einen einzigen NATO-Soldaten. Kritiker -- von der amerikanischen Rechten bis zu Kommentatoren des Globalen Suedens -- lesen dieselben Stroeme als Eskalation, Stellvertreter-Verschwendung und Subvention zur Verlaengerung eines nicht zu gewinnenden Krieges. Die Einzelheiten zaehlen: welche Systeme (Abfangraketen der Luftverteidigung, Langstreckenschlag, F-16), wie sie finanziert werden (Direktzuschuesse, Kredite, die umstrittene Nutzung immobilisierter russischer Zentralbankvermoegen) und ob die europaeische Industrie auffuellen kann, was die amerikanische Politik moeglicherweise zurueckzieht. An der Hilfe entscheidet sich letztlich das Durchhaltevermoegen des Krieges -- und hier wird die westliche Einheit am sichtbarsten auf die Probe gestellt.'
WHERE id = 'western_aid_to_ukraine';

-- 3. Peace negotiations and diplomatic initiatives
UPDATE friction_nodes SET
  name_de = 'Friedensverhandlungen und diplomatische Initiativen',
  description_en = 'The diplomatic track: ceasefire proposals, security guarantees, territorial formulas and the shuttle diplomacy around them. Three incompatible end-states compete -- a Ukrainian restoration of 1991 borders, a Russian settlement that ratifies its annexations and Ukrainian neutrality, and a great-power push to freeze the line as it stands. The contest is over whose terms define "peace".',
  description_de = 'Die diplomatische Spur: Waffenstillstandsvorschlaege, Sicherheitsgarantien, territoriale Formeln und die Pendeldiplomatie darum herum. Drei unvereinbare Endzustaende konkurrieren -- eine ukrainische Wiederherstellung der Grenzen von 1991, eine russische Regelung, die seine Annexionen und die ukrainische Neutralitaet bestaetigt, und ein Grossmacht-Vorstoss, die Linie im heutigen Verlauf einzufrieren. Der Streit geht darum, wessen Bedingungen "Frieden" definieren.',
  editorial_summary_en = 'Every settlement proposal encodes a theory of who is winning. Kyiv''s maximalist position -- full withdrawal, restored borders, accountability and NATO-backed guarantees -- treats negotiation as the codification of a Russian defeat that has not yet happened on the ground. Moscow''s terms invert this: recognised annexations, a neutral and "denazified" Ukraine, sanctions lifted -- the ratification of its war aims by other means. Between them sits a third track, pushed at various points by Washington and echoed by war-weary European and Global South voices, that would freeze the front roughly where it lies and defer the hardest questions. The vocabulary -- Istanbul, Anchorage, security guarantees, line of contact, territorial swaps -- shifts with each round of shuttle diplomacy, but the underlying deadlock is stable: no party will sign terms that concede what it still believes it can win or hold. Diplomacy here is less a path out of the war than another arena in which it is fought.',
  editorial_summary_de = 'Jeder Regelungsvorschlag verschluesselt eine Theorie darueber, wer gewinnt. Kiews maximalistische Position -- vollstaendiger Abzug, wiederhergestellte Grenzen, Rechenschaft und NATO-gestuetzte Garantien -- behandelt Verhandlungen als Festschreibung einer russischen Niederlage, die am Boden noch nicht eingetreten ist. Moskaus Bedingungen kehren dies um: anerkannte Annexionen, eine neutrale und "entnazifizierte" Ukraine, aufgehobene Sanktionen -- die Bestaetigung seiner Kriegsziele mit anderen Mitteln. Dazwischen liegt eine dritte Spur, zeitweise von Washington vorangetrieben und von kriegsmueden europaeischen und Global-South-Stimmen aufgegriffen, die die Front etwa dort einfrieren wuerde, wo sie verlaeuft, und die haertesten Fragen vertagt. Das Vokabular -- Istanbul, Anchorage, Sicherheitsgarantien, Kontaktlinie, Gebietstausch -- verschiebt sich mit jeder Runde der Pendeldiplomatie, doch die zugrunde liegende Blockade ist stabil: keine Partei unterzeichnet Bedingungen, die preisgeben, was sie noch zu gewinnen oder zu halten glaubt. Diplomatie ist hier weniger ein Weg aus dem Krieg als eine weitere Arena, in der er gefuehrt wird.'
WHERE id = 'ukraine_peace_negotiations';

-- 4. Official corruption and reconstruction challenges
UPDATE friction_nodes SET
  name_de = 'Amtliche Korruption und Herausforderungen des Wiederaufbaus',
  description_en = 'Governance under wartime stress: graft investigations, procurement scandals and the integrity of reconstruction and aid spending. Coverage splits three ways -- reform institutions proving they work, Western allies alarmed that high-level corruption threatens support, and adversary media casting the whole state as a kleptocracy stealing aid at scale.',
  description_de = 'Regieren unter Kriegsbelastung: Korruptionsermittlungen, Beschaffungsskandale und die Integritaet der Ausgaben fuer Wiederaufbau und Hilfe. Die Berichterstattung teilt sich in drei Richtungen -- Reforminstitutionen, die ihre Wirksamkeit beweisen, westliche Verbuendete, die alarmiert sind, dass Korruption auf hoher Ebene die Unterstuetzung gefaehrdet, und gegnerische Medien, die den gesamten Staat als Kleptokratie darstellen, die Hilfe in grossem Stil stiehlt.',
  editorial_summary_en = 'Corruption is the one Ukraine topic where the usual publisher coalitions break down. The country''s own anti-corruption architecture -- NABU, SAPO, the High Anti-Corruption Court -- is both a genuine reform success and a steady source of damaging headlines, because every prosecution is also proof that the graft was there. Supportive outlets can therefore read the same Yermak-circle or procurement scandal two ways at once: as institutions working, or as systemic rot that endangers the Western aid the war depends on. That is why this node runs a three-stance gradient rather than a simple pro/con split -- reform-in-progress, Western systemic alarm, and the adversary "Zelensky kleptocracy" frame that treats every story as evidence aid is being stolen wholesale. The stakes are concrete: corruption narratives feed directly into the aid debate, so a single high-profile scandal can move votes in Washington and Brussels as much as any battlefield setback.',
  editorial_summary_de = 'Korruption ist das eine Ukraine-Thema, bei dem die ueblichen Publisher-Koalitionen zusammenbrechen. Die eigene Antikorruptionsarchitektur des Landes -- NABU, SAPO, der Hohe Antikorruptionsgerichtshof -- ist zugleich ein echter Reformerfolg und eine bestaendige Quelle schaedlicher Schlagzeilen, denn jede Strafverfolgung ist auch ein Beleg, dass die Korruption vorhanden war. Wohlwollende Medien koennen denselben Skandal im Jermak-Kreis oder bei der Beschaffung daher auf zweierlei Weise zugleich lesen: als funktionierende Institutionen oder als systemische Faeulnis, die die westliche Hilfe gefaehrdet, von der der Krieg abhaengt. Deshalb faehrt dieser Knoten einen Drei-Stufen-Gradienten statt einer einfachen Pro/Contra-Teilung -- Reform im Gange, westliche systemische Alarmierung und das gegnerische "Selenskyj-Kleptokratie"-Framing, das jede Geschichte als Beweis wertet, dass Hilfe in grossem Stil gestohlen wird. Die Einsaetze sind konkret: Korruptionsnarrative fliessen direkt in die Hilfsdebatte ein, sodass ein einziger prominenter Skandal in Washington und Bruessel ebenso Stimmen bewegen kann wie ein Rueckschlag auf dem Schlachtfeld.'
WHERE id = 'ukraine_official_corruption';

COMMIT;
