-- FN Europe review, phase 3: ukraine_war_theater editorial rework (2026-07-09)
-- 1. Sharper theater name (was "Ukraine war theater")
-- 2. editorial_summary_en/de written (was missing -- this is the frontend's
--    main hero description, per apps/frontend/app/[locale]/friction-nodes/
--    [slug]/page.tsx:188)
-- 3. description_en/de updated to mention the new infrastructure-war FN
--    (this is the sidebar "What is contested" box, page.tsx:227)
-- 4. russia_special_military_operation claim tightened: removed "the West's
--    role as the actual aggressor through proxy warfare" -- that line
--    duplicated proxy_war_restraint_critique's own territory and was making
--    the two narratives read as redundant. Publisher cohorts remain fully
--    disjoint (TASS/RT/Lenta/RIA/BelTA/Press TV vs Fox
--    News/CGTN/AlJazeera/Anadolu/etc) -- kept as 3 distinct narratives.
-- 5. fn_anchor bundle rebuilt smaller and sharper: dropped NATO/EU/G7/BRICS/
--    NATO summit/EU summit/Ramstein/UDCG (generic multilateral nouns that
--    were flooding "Headlines under this frame" with NATO-summit scheduling
--    wire copy instead of substantive coverage -- confirmed via sample
--    inspection) plus "rebuild" and the bare war/invasion terms some
--    non-English lists carried inconsistently with EN. 31 EN aliases -> 22.
BEGIN;

UPDATE friction_nodes
   SET name_en = 'Russia''s war in Ukraine',
       name_de = 'Russlands Krieg in der Ukraine',
       description_en = 'The Russia-Ukraine war (initiated 24 February 2022) and its surrounding contest of framings: battlefield operations, the campaign against energy and infrastructure on both sides, Western military and economic aid, peace negotiations, anti-corruption investigations of Ukrainian officials, and the sanctions regime on Russia. The scope of the war itself is contested vocabulary — Ukrainian/Western framing as full-scale invasion versus Russian framing as a limited special military operation. Coverage spans Ukrainian, Russian, Western mainstream, Eastern European, and Global South press with sharply divergent vocabularies for the same events.',
       description_de = 'Der russisch-ukrainische Krieg (begonnen am 24. Februar 2022) und sein umgebender Rahmungs-Wettstreit: Gefechtsoperationen, der beiderseitige Feldzug gegen Energie und Infrastruktur, westliche militaerische und wirtschaftliche Hilfe, Friedensverhandlungen, Anti-Korruptionsermittlungen gegen ukrainische Beamte und das Sanktionsregime gegen Russland. Der Umfang des Krieges selbst ist umkaempftes Vokabular — ukrainisch-westliche Rahmung als voll entfaltete Invasion gegenueber russischer Rahmung als begrenzte militaerische Spezialoperation. Berichterstattung umfasst ukrainische, russische, westliche, osteuropaeische und Global-South-Medien mit stark divergierenden Vokabularen fuer dieselben Ereignisse.',
       editorial_summary_en = 'Russia''s invasion of Ukraine, launched 24 February 2022, is the largest land war in Europe since 1945 and the organizing fact of the current European security order. Four axes of contest run through it: control of the front line itself, the scale and durability of Western military and economic backing, the terms on which — or whether — negotiations can end it, and whether Ukraine''s wartime governance holds up under the strain of corruption scandals. A fifth front runs through the energy system on both sides, targeting the fuel and power that sustain the other''s war effort. Coverage of the war is itself contested ground: the same events are described as full-scale invasion and national resistance in Kyiv and the West, and as a special military operation against NATO encroachment in Moscow.',
       editorial_summary_de = 'Russlands am 24. Februar 2022 begonnene Invasion der Ukraine ist der groesste Landkrieg in Europa seit 1945 und die praegende Tatsache der gegenwaertigen europaeischen Sicherheitsordnung. Vier Streitachsen durchziehen ihn: die Kontrolle ueber die Front selbst, Ausmass und Durchhaltefaehigkeit der westlichen militaerischen und wirtschaftlichen Unterstuetzung, die Bedingungen, unter denen — oder ob ueberhaupt — Verhandlungen den Krieg beenden koennen, sowie die Frage, ob die ukrainische Kriegsfuehrung der Belastung durch Korruptionsskandale standhaelt. Eine fuenfte Front verlaeuft durch das Energiesystem beider Seiten und zielt auf Treibstoff und Strom, die die Kriegsanstrengung der jeweils anderen Seite aufrechterhalten. Die Berichterstattung ueber den Krieg ist selbst umkaempftes Terrain: dieselben Ereignisse werden in Kiew und im Westen als umfassende Invasion und nationaler Widerstand beschrieben, in Moskau als militaerische Spezialoperation gegen die NATO-Osterweiterung.',
       updated_at = NOW()
 WHERE id = 'ukraine_war_theater';

UPDATE narratives_v2
   SET claim_en = 'Russian state press and aligned outlets frame the war as a defensive special military operation (SMO) protecting Russian-speaking populations in Donbas and Crimea from a Western-installed regime in Kyiv that pursued ethnic discrimination and NATO encroachment since 2014. Vocabulary centers on denazification, demilitarisation, NATO expansion, Western interference, Russian world (Russky Mir), and historical Russian-Ukrainian unity. Coverage emphasises Russian military precision and humanitarian conduct, Ukrainian military targeting of civilians, and the illegitimacy of the post-Maidan Kyiv government. Prescription: complete the SMO''s territorial and political objectives; reject Western-imposed settlement frameworks; defend multipolar world order.',
       claim_de = 'Russische Staatsmedien und ausgerichtete Outlets rahmen den Krieg als defensive militaerische Spezialoperation (SMO) zum Schutz russischsprachiger Bevoelkerungen im Donbass und auf der Krim vor einem vom Westen eingesetzten Regime in Kiew, das seit 2014 ethnische Diskriminierung und NATO-Vormarsch betrieben habe. Das Vokabular kreist um Entnazifizierung, Entmilitarisierung, NATO-Erweiterung, westliche Einmischung, russische Welt (Russki Mir) und historische russisch-ukrainische Einheit. Berichterstattung betont russische militaerische Praezision und humanitaeres Verhalten, ukrainische militaerische Angriffe auf Zivilisten und Illegitimitaet der nach-Maidan-Regierung in Kiew. Vorschrift: territoriale und politische Ziele der SMO vollenden; westlich auferlegte Beilegungsrahmen ablehnen; multipolare Weltordnung verteidigen.',
       updated_at = NOW()
 WHERE id = 'russia_special_military_operation';

UPDATE taxonomy_v3
   SET aliases = '{"en": ["OSCE", "Wagner", "ICC", "ICJ", "special military operation", "SMO", "war crimes", "prisoner of war", "POW", "POW exchange", "refugees", "displaced", "reconstruction", "aid corridor", "Donbas", "Donbass", "Crimea", "Black Sea", "Sea of Azov", "civilian casualties", "grain corridor", "Black Sea grain"], "de": ["OSZE", "IStGH", "IGH", "militaerische Spezialoperation", "Kriegsverbrechen", "Kriegsgefangene", "Gefangenenaustausch", "Fluechtlinge", "Vertriebene", "Wiederaufbau", "Hilfskorridor", "Donbass", "Krim", "Schwarzes Meer", "Asowsches Meer", "zivile Opfer", "Getreidekorridor", "Getreideabkommen"], "es": ["CPI", "CIJ", "operacion militar especial", "crimenes de guerra", "prisioneros de guerra", "intercambio de prisioneros", "refugiados", "desplazados", "reconstruccion", "corredor de ayuda", "Donbas", "Crimea", "Mar Negro", "Mar de Azov", "victimas civiles", "corredor de granos"], "fr": ["CPI", "CIJ", "operation militaire speciale", "crimes de guerre", "prisonniers de guerre", "echange de prisonniers", "refugies", "deplaces", "reconstruction", "corridor d''aide", "Donbass", "Crimee", "mer Noire", "mer d''Azov", "victimes civiles", "corridor cerealier"], "it": ["CPI", "CIG", "operazione militare speciale", "crimini di guerra", "prigionieri di guerra", "scambio di prigionieri", "rifugiati", "sfollati", "ricostruzione", "corridoio di aiuti", "Donbass", "Crimea", "Mar Nero", "Mar d''Azov", "vittime civili", "corridoio del grano"], "ru": ["ОБСЕ", "Вагнер", "МУС", "Международный суд", "СВО", "спецоперация", "специальная военная операция", "военные преступления", "военнопленные", "обмен пленными", "беженцы", "переселенцы", "восстановление", "коридор помощи", "Донбасс", "Крым", "Черное море", "Азовское море", "гражданские жертвы", "зерновой коридор", "зерновая сделка"], "zh": ["欧安组织", "瓦格纳集团", "国际刑事法院", "国际法院", "特别军事行动", "战争罪", "战犯", "战俘", "战俘交换", "难民", "流离失所者", "重建", "援助走廊", "顿巴斯", "克里米亚", "黑海", "亚速海", "平民伤亡", "粮食走廊"], "ar": ["منظمة الأمن والتعاون في أوروبا", "فاغنر", "المحكمة الجنائية الدولية", "محكمة العدل الدولية", "عملية عسكرية خاصة", "جرائم الحرب", "اسرى الحرب", "تبادل اسرى", "لاجئين", "نازحين", "اعادة الاعمار", "ممر المساعدات", "دونباس", "القرم", "البحر الاسود", "بحر آزوف", "ضحايا مدنيين", "ممر الحبوب"], "ja": ["欧州安全保障協力機構", "ワグネル", "国際刑事裁判所", "国際司法裁判所", "特別軍事作戦", "戦争犯罪", "捕虜", "捕虜交換", "難民", "国内避難民", "復興", "支援回廊", "ドンバス", "クリミア", "黒海", "アゾフ海", "民間人犠牲者", "穀物協定"], "hi": ["OSCE", "वैगनर", "अंतरराष्ट्रीय आपराधिक न्यायालय", "अंतरराष्ट्रीय न्यायालय", "विशेष सैन्य अभियान", "युद्ध अपराध", "युद्ध बंदी", "युद्धबंदी विनिमय", "शरणार्थी", "विस्थापित", "पुनर्निर्माण", "सहायता गलियारा", "डोनबास", "क्रीमिया", "काला सागर", "आज़ोव सागर", "नागरिक हताहत", "अनाज गलियारा"]}'::jsonb
 WHERE taxonomy_function = 'fn_anchor' AND linked_id = 'ukraine_war_theater';

COMMIT;
