-- Caucasus completeness fields (§6): bilingual description + editorial_summary
-- for the theater and all 5 active atomics. name_en/name_de already set in the
-- structure migration. Reversible (UPDATE-only).

BEGIN;

UPDATE friction_nodes SET
 description_en = 'The struggle over the future of the South Caucasus as Armenia, Azerbaijan and Georgia are pulled between a receding Russia and an advancing West, Turkey and Iran. Live fault lines run through it: Armenia''s historic pivot away from Moscow toward the EU, the fragile Armenia-Azerbaijan peace after the 2023 fall of Nagorno-Karabakh, the contested Zangezur ("Trump Route") corridor, the wider jockeying of external powers, and Georgia''s own latent drift. Coverage splits sharply: Western outlets read a strategic realignment toward Europe, while Russian and Chinese state media frame it as reckless Western expansion into Russia''s neighbourhood.',
 description_de = 'Der Kampf um die Zukunft des Südkaukasus, während Armenien, Aserbaidschan und Georgien zwischen einem zurückweichenden Russland und einem vordringenden Westen, der Türkei und dem Iran hin- und hergerissen werden. Mehrere offene Bruchlinien durchziehen ihn: Armeniens historische Abkehr von Moskau hin zur EU, der fragile Frieden zwischen Armenien und Aserbaidschan nach dem Fall Bergkarabachs 2023, der umstrittene Sangesur-Korridor ("Trump-Route"), das breitere Ringen externer Mächte und Georgiens eigene latente Drift. Die Berichterstattung ist tief gespalten: westliche Medien lesen eine strategische Neuordnung nach Europa, russische und chinesische Staatsmedien deuten sie als rücksichtslose westliche Expansion in Russlands Nachbarschaft.',
 editorial_summary_en = 'The South Caucasus, long a quiet Russian sphere, has become a contested space of realignment. Armenia -- abandoned by Moscow during the loss of Nagorno-Karabakh -- has pivoted decisively toward the EU and the West, freezing its CSTO role and returning a pro-Western government despite Russian economic pressure. A US- and Turkey-brokered Armenia-Azerbaijan peace is delimiting borders and reopening trade after three decades of war, though Armenian grievance over the 2023 exodus and unresolved accountability runs beneath it. The Zangezur "Trump Route" corridor promises connectivity but crosses Iranian and Russian red lines, and external powers -- Turkey, Iran, Israel and the US -- jockey through energy deals and the Armenian-genocide-recognition dispute. Georgia''s parallel struggle between a Moscow-leaning government and a pro-EU public remains a latent front. The region is quiet now but structurally combustible, and its coverage divides cleanly between a Western realignment story and a Russian/Chinese narrative of Western encirclement.',
 editorial_summary_de = 'Der Südkaukasus, lange eine ruhige russische Einflusssphäre, ist zu einem umkämpften Raum der Neuordnung geworden. Armenien -- von Moskau beim Verlust Bergkarabachs im Stich gelassen -- hat sich entschieden der EU und dem Westen zugewandt, seine OVKS-Rolle eingefroren und trotz russischen Wirtschaftsdrucks eine prowestliche Regierung im Amt bestätigt. Ein von den USA und der Türkei vermittelter Frieden zwischen Armenien und Aserbaidschan zieht Grenzen und öffnet nach drei Jahrzehnten Krieg wieder den Handel, auch wenn armenisches Unrecht über den Exodus von 2023 und ungeklärte Verantwortung darunter schwelen. Der Sangesur-Korridor ("Trump-Route") verspricht Konnektivität, überschreitet aber iranische und russische rote Linien, und externe Mächte -- Türkei, Iran, Israel und die USA -- ringen über Energieabkommen und den Streit um die Anerkennung des Völkermords an den Armeniern. Georgiens paralleler Kampf zwischen einer Moskau-nahen Regierung und einer proeuropäischen Öffentlichkeit bleibt eine latente Front. Die Region ist derzeit ruhig, aber strukturell brandgefährlich, und ihre Berichterstattung spaltet sich klar in eine westliche Neuordnungserzählung und eine russisch/chinesische Erzählung westlicher Einkreisung.'
WHERE id='caucasus_theater';

UPDATE friction_nodes SET
 description_en = 'Armenia''s realignment away from Russia and toward the European Union and the West. After Moscow''s security guarantee failed during the Karabakh wars, Yerevan has frozen its role in the CSTO, courted EU trade and accession, and returned a pro-Western government at the ballot box -- drawing economic pressure and warnings from Moscow. Western coverage frames it as a sovereign democratic choice; Russian state media as a Western-engineered capture heading for a "Ukraine scenario".',
 description_de = 'Armeniens Neuausrichtung weg von Russland und hin zur Europäischen Union und zum Westen. Nachdem Moskaus Sicherheitsgarantie in den Karabach-Kriegen versagte, hat Jerewan seine Rolle in der OVKS eingefroren, EU-Handel und -Beitritt umworben und eine prowestliche Regierung an der Wahlurne bestätigt -- was wirtschaftlichen Druck und Warnungen aus Moskau nach sich zieht. Westliche Berichterstattung deutet dies als souveräne demokratische Entscheidung, russische Staatsmedien als vom Westen inszenierte Vereinnahmung auf dem Weg in ein "Ukraine-Szenario".',
 editorial_summary_en = 'Armenia is the sharpest expression of the South Caucasus realignment. Feeling abandoned by Russia during the loss of Nagorno-Karabakh, Prime Minister Pashinyan has frozen Armenia''s participation in the Russian-led CSTO, pursued EU trade concessions and an accession path, hosted a European Political Community summit in Yerevan, and won re-election against a pro-Russian opposition -- all while Moscow retaliates with import bans and warnings of economic ruin. Western and Ukrainian outlets celebrate a sovereign, democratic escape from Russian domination; a more cautious Western strand warns the pivot leaves Armenia exposed with no security guarantee to replace Russia; and Russian state media casts it as a Western-engineered capture, tainted by "collective West" interference and bound for a Ukraine-style collapse.',
 editorial_summary_de = 'Armenien ist der schärfste Ausdruck der Neuordnung des Südkaukasus. Da er sich von Russland beim Verlust Bergkarabachs im Stich gelassen fühlt, hat Premierminister Paschinjan Armeniens Teilnahme an der russisch geführten OVKS eingefroren, EU-Handelszugeständnisse und einen Beitrittsweg verfolgt, einen Gipfel der Europäischen Politischen Gemeinschaft in Jerewan ausgerichtet und sich gegen eine prorussische Opposition zur Wiederwahl durchgesetzt -- während Moskau mit Einfuhrverboten und Warnungen vor dem wirtschaftlichen Ruin reagiert. Westliche und ukrainische Medien feiern einen souveränen, demokratischen Ausbruch aus russischer Vorherrschaft; ein vorsichtigerer westlicher Strang warnt, der Schwenk lasse Armenien ohne Sicherheitsgarantie als Russland-Ersatz ungeschützt; und russische Staatsmedien stellen ihn als vom Westen inszenierte Vereinnahmung dar, verfälscht durch Einmischung des "kollektiven Westens" und auf dem Weg zu einem Zusammenbruch nach ukrainischem Muster.'
WHERE id='armenia_western_pivot';

UPDATE friction_nodes SET
 description_en = 'The bilateral conflict and settlement between Armenia and Azerbaijan, in both its war and peace modes. It spans the post-2023 peace treaty, border delimitation and Armenia-Turkey normalization on one side, and recurring border clashes, ceasefire violations, prisoner-of-war disputes and unresolved Karabakh accountability on the other. Western and Turkish outlets frame a historic, US-brokered peace; a pro-Armenian and rights-based strand sees a coerced capitulation that rewards ethnic cleansing; Russian media sees a settlement that sidelines Moscow.',
 description_de = 'Der bilaterale Konflikt und die Regelung zwischen Armenien und Aserbaidschan, in ihrem Kriegs- wie Friedensmodus. Sie umfasst einerseits den Friedensvertrag nach 2023, die Grenzziehung und die Normalisierung zwischen Armenien und der Türkei, andererseits wiederkehrende Grenzgefechte, Verstöße gegen den Waffenstillstand, Streit um Kriegsgefangene und die ungeklärte Verantwortung für Karabach. Westliche und türkische Medien deuten einen historischen, von den USA vermittelten Frieden; ein proarmenischer und menschenrechtlicher Strang sieht eine erzwungene Kapitulation, die ethnische Säuberung belohnt; russische Medien sehen eine Regelung, die Moskau an den Rand drängt.',
 editorial_summary_en = 'After Azerbaijan''s 2023 recapture of Nagorno-Karabakh and the exodus of its Armenian population, the two states have moved toward a formal peace -- delimiting their border, negotiating a treaty, and, in parallel, opening the century-old freeze between Armenia and Turkey through direct trade and railway talks. The container holds both modes: the diplomacy of normalization and the persistent risk of relapse, with border clashes, prisoners still held in Baku, and the trial of former Karabakh leaders keeping the conflict live. Western and Turkish coverage frames a historic, US-brokered peace and regional integration; a pro-Armenian and human-rights framing rejects it as a capitulation dictated to a defeated Armenia that leaves ethnic cleansing and war crimes unaddressed; and Russian state media casts the Western- and Turkish-brokered deal as a power grab that pushes out Moscow''s peacekeepers.',
 editorial_summary_de = 'Nach Aserbaidschans Rückeroberung Bergkarabachs 2023 und dem Exodus seiner armenischen Bevölkerung haben sich die beiden Staaten auf einen förmlichen Frieden zubewegt -- sie ziehen ihre Grenze, verhandeln einen Vertrag und öffnen parallel das jahrhundertealte Zerwürfnis zwischen Armenien und der Türkei durch direkten Handel und Gespräche über die Bahnverbindung. Der Container hält beide Modi: die Diplomatie der Normalisierung und das anhaltende Rückfallrisiko, mit Grenzgefechten, weiter in Baku festgehaltenen Gefangenen und dem Prozess gegen frühere Karabach-Führer, die den Konflikt lebendig halten. Westliche und türkische Berichterstattung deutet einen historischen, von den USA vermittelten Frieden und regionale Integration; eine proarmenische und menschenrechtliche Deutung weist ihn als einem besiegten Armenien diktierte Kapitulation zurück, die ethnische Säuberung und Kriegsverbrechen ungesühnt lasse; und russische Staatsmedien stellen den westlich-türkisch vermittelten Deal als Machtgriff dar, der Moskaus Friedenstruppen verdränge.'
WHERE id='armenia_azerbaijan_settlement';

UPDATE friction_nodes SET
 description_en = 'Georgia''s contested geopolitical trajectory between the West and Russia -- a latent front kept as a placeholder for a fault line that can flare fast. A Georgian Dream government accused of drifting toward Moscow has passed a Russian-style foreign-agent law and stalled EU accession, provoking mass pro-European protests and a crackdown, against the backdrop of the Russian-occupied breakaway regions of Abkhazia and South Ossetia. Western outlets back the pro-EU public against democratic backsliding; Russian state media praise Tbilisi for resisting a Western-engineered colour revolution.',
 description_de = 'Georgiens umkämpfte geopolitische Bahn zwischen dem Westen und Russland -- eine latente Front, die als Platzhalter für eine schnell aufflammende Bruchlinie dient. Eine Regierung des Georgischen Traums, der ein Abdriften Richtung Moskau vorgeworfen wird, hat ein Agentengesetz nach russischem Vorbild verabschiedet und den EU-Beitritt gestoppt, was proeuropäische Massenproteste und eine Niederschlagung auslöste -- vor dem Hintergrund der russisch besetzten abtrünnigen Regionen Abchasien und Südossetien. Westliche Medien stützen die proeuropäische Öffentlichkeit gegen den demokratischen Rückschritt; russische Staatsmedien loben Tiflis für den Widerstand gegen eine vom Westen inszenierte Farbrevolution.',
 editorial_summary_en = 'Georgia is the South Caucasus'' third potential Ukraine: a small state on Russia''s border whose European aspiration collides with a government many see leaning back toward Moscow. The ruling Georgian Dream party has enacted a Russian-style "foreign agent" law, seen its EU-accession bid frozen, and faced sustained pro-European street protests met with a crackdown, while Abkhazia and South Ossetia remain under Russian control as frozen conflicts. This friction node is deliberately maintained as a thin placeholder: coverage is quiet today, but the fault line -- a Moscow-leaning government against a pro-EU public -- can escalate suddenly. Western outlets frame a European future being betrayed by democratic backsliding; Russian state media frame a sovereign government resisting a Western-orchestrated colour revolution.',
 editorial_summary_de = 'Georgien ist das dritte potenzielle Ukraine des Südkaukasus: ein kleiner Staat an Russlands Grenze, dessen europäisches Streben mit einer Regierung kollidiert, die viele wieder Richtung Moskau geneigt sehen. Die regierende Partei Georgischer Traum hat ein Agentengesetz nach russischem Vorbild erlassen, ihren EU-Beitritt eingefroren gesehen und anhaltende proeuropäische Straßenproteste erlebt, die niedergeschlagen wurden, während Abchasien und Südossetien als eingefrorene Konflikte unter russischer Kontrolle bleiben. Dieser Reibungsknoten wird bewusst als schlanker Platzhalter geführt: die Berichterstattung ist heute ruhig, doch die Bruchlinie -- eine Moskau-nahe Regierung gegen eine proeuropäische Öffentlichkeit -- kann plötzlich eskalieren. Westliche Medien deuten eine verratene europäische Zukunft durch demokratischen Rückschritt; russische Staatsmedien deuten eine souveräne Regierung, die einer vom Westen orchestrierten Farbrevolution widersteht.'
WHERE id='georgia_geopolitical_drift';

UPDATE friction_nodes SET
 description_en = 'The Zangezur corridor -- a proposed transit link across Armenia''s Syunik province connecting mainland Azerbaijan to its Nakhchivan exclave, recently rebranded as the US-backed "Trump Route" (TRIPP). It is the geoeconomic keystone of the peace and a strategic flashpoint: connectivity and trade for its backers, an extraterritorial threat to Armenian sovereignty and Iran''s border for its opponents. Western, Turkish and Azerbaijani outlets frame prosperity and integration; Iranian and Russian media frame a red line to be blocked.',
 description_de = 'Der Sangesur-Korridor -- eine geplante Transitverbindung durch Armeniens Provinz Sjunik, die das aserbaidschanische Kernland mit seiner Exklave Nachitschewan verbindet und kürzlich als US-gestützte "Trump-Route" (TRIPP) neu benannt wurde. Er ist der geoökonomische Schlussstein des Friedens und ein strategischer Brennpunkt: Konnektivität und Handel für seine Befürworter, eine extraterritoriale Bedrohung für Armeniens Souveränität und Irans Grenze für seine Gegner. Westliche, türkische und aserbaidschanische Medien deuten Wohlstand und Integration; iranische und russische Medien deuten eine rote Linie, die zu blockieren ist.',
 editorial_summary_en = 'The Zangezur corridor is where the South Caucasus peace turns geopolitical. The route would run across Armenia''s southern Syunik province to link Azerbaijan proper with its Nakhchivan exclave -- and, extended, Turkey to the Caspian and Central Asia. Its 2025 rebranding as the "Trump Route"/TRIPP, with a US operating role, made it the corridor''s defining event. For Azerbaijan, Turkey and the West it is a transformative connectivity and prosperity project and the physical embodiment of the peace; for Iran it severs its land border with Armenia and inserts US and NATO influence on its doorstep -- a red line -- and for Russia it marks the loss of its role as regional gatekeeper. The corridor thus concentrates the whole theater''s external-power contest into a single strip of road and rail.',
 editorial_summary_de = 'Am Sangesur-Korridor wird der Frieden des Südkaukasus geopolitisch. Die Route soll durch Armeniens südliche Provinz Sjunik verlaufen, um Aserbaidschan mit seiner Exklave Nachitschewan zu verbinden -- und, verlängert, die Türkei mit dem Kaspischen Meer und Zentralasien. Ihre Neubenennung 2025 als "Trump-Route"/TRIPP, mit einer US-Betreiberrolle, machte sie zum prägenden Ereignis des Korridors. Für Aserbaidschan, die Türkei und den Westen ist sie ein transformatives Konnektivitäts- und Wohlstandsprojekt und die physische Verkörperung des Friedens; für den Iran durchtrennt sie seine Landgrenze zu Armenien und schleust US- und NATO-Einfluss vor seine Haustür -- eine rote Linie -- und für Russland markiert sie den Verlust seiner Rolle als regionaler Torwächter. Der Korridor bündelt so den gesamten Machtwettstreit des Schauplatzes in einem einzigen Streifen aus Straße und Schiene.'
WHERE id='zangezur_corridor';

UPDATE friction_nodes SET
 description_en = 'The jockeying of external powers -- Russia, Turkey, Iran, Israel and the United States -- over the South Caucasus as Russian dominance recedes. It runs through Azerbaijani energy geopolitics (SOCAR, the Southern Gas Corridor, Caspian hydrocarbons), the Israel-Turkey rivalry that surfaced in the Armenian-genocide-recognition dispute, Russia-Azerbaijan friction, and competing connectivity axes. Western and Turkish framing sees integration and moral reckoning; Russian and Iranian framing sees hostile encirclement to be resisted.',
 description_de = 'Das Ringen externer Mächte -- Russland, Türkei, Iran, Israel und die Vereinigten Staaten -- um den Südkaukasus, während die russische Vormachtstellung zurückweicht. Es verläuft über die aserbaidschanische Energiegeopolitik (SOCAR, der Südliche Gaskorridor, kaspische Kohlenwasserstoffe), die im Streit um die Anerkennung des Völkermords an den Armeniern aufgebrochene Rivalität zwischen Israel und der Türkei, Reibungen zwischen Russland und Aserbaidschan sowie konkurrierende Konnektivitätsachsen. Westliche und türkische Deutung sieht Integration und moralische Abrechnung; russische und iranische Deutung sieht eine feindliche Einkreisung, der zu widerstehen ist.',
 editorial_summary_en = 'As Russia''s grip on the South Caucasus loosens, outside powers are competing to fill the space. Azerbaijan leverages its energy wealth -- SOCAR, the Southern Gas Corridor and Caspian hydrocarbons -- to deepen ties with Europe and Turkey, while Israel''s move to recognize the Armenian Genocide, read by Ankara and Baku as a cynical blow aimed at Turkey and a deflection from Gaza, exposed the Israel-Turkey rivalry playing out across the region. Russia-Azerbaijan relations have frayed over detained nationals and a drone strike on a SOCAR facility, and Iran guards its northern flank against US and Israeli inroads. Western and Turkish coverage frames integration and, on the genocide question, moral reckoning; Russian and Iranian state media frame the whole contest as a hostile Western, Turkish and Israeli encirclement to be resisted through their own partnerships.',
 editorial_summary_de = 'Während sich Russlands Griff auf den Südkaukasus lockert, konkurrieren äußere Mächte darum, den Raum zu füllen. Aserbaidschan nutzt seinen Energiereichtum -- SOCAR, den Südlichen Gaskorridor und kaspische Kohlenwasserstoffe -- um die Beziehungen zu Europa und der Türkei zu vertiefen, während Israels Vorstoß zur Anerkennung des Völkermords an den Armeniern, von Ankara und Baku als zynischer, gegen die Türkei gerichteter Schlag und Ablenkung von Gaza gelesen, die quer durch die Region ausgetragene Rivalität zwischen Israel und der Türkei offenlegte. Die Beziehungen zwischen Russland und Aserbaidschan sind über festgehaltene Staatsbürger und einen Drohnenangriff auf eine SOCAR-Anlage zerrüttet, und der Iran bewacht seine Nordflanke gegen US-amerikanische und israelische Vorstöße. Westliche und türkische Berichterstattung deutet Integration und, in der Völkermordfrage, eine moralische Abrechnung; russische und iranische Staatsmedien deuten den gesamten Wettstreit als feindliche westliche, türkische und israelische Einkreisung, der durch eigene Partnerschaften zu widerstehen ist.'
WHERE id='caucasus_power_competition';

COMMIT;
