
-- sahel_jihadist_insurgency (92 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'sahel_jihadist_insurgency', 'sahel_jihadist_insurgency fn_anchor', '{"ar": ["داعش", "القاعدة", "جماعة نصرة الإسلام والمسلمين", "بوكو حرام", "جهاديين", "مسلحين", "غارة جوية", "مدنيين", "حصار", "قاعدة عسكرية"], "de": ["Islamischer Staat", "Dschihadist", "Islamisten", "Luftangriff", "Zivilisten", "Belagerung", "Militärstützpunkt"], "en": ["JNIM", "Boko Haram", "ISWAP", "Islamic State", "al Qaeda", "al-Qaida", "jihadist", "jihadi", "militant", "insurgent", "airstrike", "air strike", "civilian", "blockade", "army base", "military base"], "es": ["Estado Islámico", "yihadista", "ataque aéreo", "civiles", "asedio", "base militar"], "fr": ["État islamique", "Etat islamique", "Groupe de soutien à l''islam et aux musulmans", "djihadiste", "jihadiste", "frappes aériennes", "civils", "blocus", "base militaire", "camp militaire", "poste militaire"], "hi": ["इस्लामिक स्टेट", "अल कायदा", "बोको हराम", "जिहादी", "चरमपंथी", "हवाई हमला", "नागरिक", "घेराबंदी", "सैन्य अड्डा"], "it": ["Stato Islamico", "jihadisti", "raid aereo", "civili", "assedio", "base militare"], "ja": ["イスラム国", "アルカイダ", "ボコ・ハラム", "ジハード主義", "イスラム過激派", "空爆", "民間人", "封鎖", "軍事基地"], "ru": ["Исламское государство", "Аль-Каида", "ДЖНИМ", "джихадист", "боевик", "авиаудар", "мирных жителей", "блокада", "военная база"], "zh": ["伊斯兰国", "基地组织", "博科圣地", "圣战分子", "武装分子", "空袭", "平民", "封锁", "军事基地"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- sahel_tuareg_separatism (48 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'sahel_tuareg_separatism', 'sahel_tuareg_separatism fn_anchor', '{"ar": ["الطوارق", "كيدال", "شمال مالي", "انفصاليين", "متمردين"], "de": ["Tuareg-Rebellen", "Nordmali", "Separatisten", "Rebellen"], "en": ["Tuareg", "Touareg", "FLA", "Front de Libération de l''Azawad", "Kidal", "separatist", "rebel"], "es": ["tuareg", "norte de Malí", "separatista", "rebeldes"], "fr": ["touareg", "touaregs", "nord du Mali", "séparatiste", "rebelles"], "hi": ["तुआरेग", "किदाल", "अलगाववादी", "विद्रोही"], "it": ["tuareg", "nord del Mali", "separatisti", "ribelli"], "ja": ["トゥアレグ", "キダル", "マリ北部", "分離主義", "反政府勢力"], "ru": ["туарег", "Кидаль", "север Мали", "сепаратист", "повстанцы"], "zh": ["图阿雷格", "基达尔", "马里北部", "分离主义", "叛军"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- sahel_junta_consolidation (62 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'sahel_junta_consolidation', 'sahel_junta_consolidation fn_anchor', '{"ar": ["المجلس العسكري", "انقلاب", "غويتا", "تراوري", "الأحزاب السياسية", "حقوق الإنسان"], "de": ["Militärjunta", "Putsch", "Militärregierung", "Parteien verboten", "Menschenrechte"], "en": ["junta", "junte", "military government", "military rule", "Goita", "Goïta", "Traore", "Traoré", "Doumbouya", "political parties", "human rights", "ICC"], "es": ["junta militar", "golpe de Estado", "partidos políticos", "derechos humanos"], "fr": ["junte", "coup d''État", "régime militaire", "militaires au pouvoir", "partis politiques", "droits de l''homme", "Cour pénale internationale"], "hi": ["सैन्य शासन", "तख्तापलट", "गोइता", "त्राओरे", "राजनीतिक दल", "मानवाधिकार"], "it": ["giunta militare", "colpo di Stato", "partiti politici", "diritti umani"], "ja": ["軍事政権", "クーデター", "ゴイタ", "トラオレ", "政党", "人権"], "ru": ["хунта", "переворот", "Гойта", "Траоре", "политические партии", "права человека"], "zh": ["军政府", "政变", "戈伊塔", "特拉奥雷", "政党", "人权"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- sahel_security_patron_contest (36 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'sahel_security_patron_contest', 'sahel_security_patron_contest fn_anchor', '{"ar": ["الفيلق الأفريقي", "فاغنر", "أنقرة", "الرباط"], "de": ["russische Militärs", "Afrikakorps"], "en": ["Africa Corps", "Wagner", "Bayraktar", "Ankara", "Rabat", "Atlantic Initiative"], "es": ["militares rusos"], "fr": ["militaires russes", "soutien russe", "Corps africain", "Ankara", "Rabat", "initiative atlantique"], "hi": ["अफ्रीका कोर", "वैगनर", "अंकारा", "रबात"], "it": ["militari russi"], "ja": ["アフリカ軍団", "ワグネル", "アンカラ", "ラバト"], "ru": ["Африканский корпус", "Вагнер", "Анкара", "Рабат"], "zh": ["非洲军团", "瓦格纳", "安卡拉", "拉巴特"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();

-- sahel_france_rupture (39 aliases)
INSERT INTO taxonomy_v3 (id, linked_id, item_raw, aliases, is_active, is_stop_word, taxonomy_function)
VALUES (gen_random_uuid(), 'sahel_france_rupture', 'sahel_france_rupture fn_anchor', '{"ar": ["العلاقات الدبلوماسية", "التجسس", "الاستعمار"], "de": ["diplomatische Beziehungen", "Spionage", "Kolonialmacht"], "en": ["diplomatic relations", "diplomatic ties", "colonial ruler", "DGSE", "espionage", "colonial", "neocolonial"], "es": ["relaciones diplomáticas", "espionaje", "colonial"], "fr": ["relations diplomatiques", "diplomate", "ambassadeur de France", "ressortissants", "agent français", "espion", "colonial", "néocolonial"], "hi": ["राजनयिक संबंध", "जासूसी", "औपनिवेशिक"], "it": ["relazioni diplomatiche", "spionaggio", "coloniale"], "ja": ["外交関係", "スパイ", "植民地"], "ru": ["дипломатические отношения", "шпионаж", "колониальн"], "zh": ["外交关系", "间谍", "殖民"]}'::jsonb, true, false, 'fn_anchor')
ON CONFLICT (linked_id) WHERE taxonomy_function = 'fn_anchor' AND is_active = true
DO UPDATE SET aliases = EXCLUDED.aliases, item_raw = EXCLUDED.item_raw, updated_at = now();
