-- Russia-Europe theater completeness fields (Phase 2, step F).
-- Bilingual name_de / description_en+de / editorial_summary_en+de for the
-- theater and all 4 atomics. Neutral, factual, evergreen prose per
-- feedback_fn_descriptions_neutral: no framing, no motive attribution, no
-- temporality. Editorial summaries neutrally describe what the opposing
-- narratives argue without endorsing either (matches russia_sanctions_regime
-- precedent already in the DB). Also fixes name_de umlaut ASCII fallback
-- (Kriegsfuehrung -> Kriegsführung) introduced by the structure migration.

UPDATE friction_nodes SET
 name_de = 'Russland-Europa-Konfrontation',
 description_en = 'The confrontation between Russia and European states and institutions outside the direct Ukraine battlefield: NATO military posture on the eastern flank, below-threshold gray-zone activity, contested airspace over NATO territory, and the sanctions regime imposed on Russia since 2022. Participants include Russia, NATO and EU member states along the eastern flank (Baltic, Nordic, Visegrad), Germany, France, the UK, and the United States.',
 description_de = 'Die Konfrontation zwischen Russland und europäischen Staaten und Institutionen außerhalb des unmittelbaren Kriegsschauplatzes in der Ukraine: militärische Präsenz der NATO an der Ostflanke, Aktivität unterhalb der Kriegsschwelle in der Grauzone, umstrittener Luftraum über NATO-Gebiet und das seit 2022 gegen Russland verhängte Sanktionsregime. Beteiligte sind Russland, NATO- und EU-Mitgliedstaaten entlang der Ostflanke (Baltikum, Norden, Visegrad-Staaten), Deutschland, Frankreich, das Vereinigte Königreich und die Vereinigten Staaten.',
 editorial_summary_en = 'The theater spans four atomic frictions: NATO-Russia military deterrence, hybrid and gray-zone operations, airspace incursions, and the sanctions regime. Western-mainstream coverage treats these as complementary parts of one response to sustained Russian pressure. Russian and allied state media treat the same events as manufactured or self-inflicted, produced by NATO encirclement and Western economic self-harm rather than genuine Russian aggression. A third, smaller current within Western-European press is critical of aspects of the Western response itself -- threat inflation, over-attribution, escalation risk -- without endorsing the Russian counter-frame.',
 editorial_summary_de = 'Das Theater umfasst vier atomare Reibungspunkte: militärische Abschreckung zwischen NATO und Russland, hybride Operationen in der Grauzone, Luftraumverletzungen und das Sanktionsregime. Die westliche Mainstream-Berichterstattung behandelt diese als sich ergänzende Teile einer Antwort auf anhaltenden russischen Druck. Russische und verbündete Staatsmedien behandeln dieselben Ereignisse als konstruiert oder selbstverschuldet, verursacht durch NATO-Einkreisung und westliche wirtschaftliche Selbstschädigung statt durch echte russische Aggression. Eine dritte, kleinere Strömung innerhalb der westeuropäischen Presse steht Teilen der westlichen Reaktion selbst kritisch gegenüber -- Bedrohungsinflation, Über-Attribution, Eskalationsrisiko --, ohne den russischen Gegenframe zu teilen.',
 updated_at = now()
WHERE id = 'russia_europe_theater';

UPDATE friction_nodes SET
 name_de = 'NATO-Russland-Abschreckung an der Ostflanke',
 description_en = 'NATO military posture on its eastern flank facing Russia: enhanced Forward Presence brigades in the Baltic states, forward air policing near Kaliningrad and the Suwalki corridor, rearmament and rising defence budgets, reintroduced conscription in several states, and named exercises such as Steadfast Defender and Baltic Sentry.',
 description_de = 'Die militärische Präsenz der NATO an ihrer Ostflanke gegenüber Russland: verstärkte Vornepräsenz-Brigaden in den baltischen Staaten, vorwärtige Luftpolizei nahe Kaliningrad und dem Suwalki-Korridor, Aufrüstung und steigende Verteidigungsbudgets, wiedereingeführte Wehrpflicht in mehreren Staaten sowie benannte Übungen wie Steadfast Defender und Baltic Sentry.',
 editorial_summary_en = 'Western-mainstream coverage treats the build-up as proportionate deterrence against a persistent Russian military threat. Russian and allied state media treat the same build-up as aggressive NATO encirclement driving escalation. A smaller Western-European current questions whether rearmament and war-economy drift have become disproportionate to the near-term threat.',
 editorial_summary_de = 'Die westliche Mainstream-Berichterstattung behandelt den Ausbau als angemessene Abschreckung gegen eine anhaltende russische Bedrohung. Russische und verbündete Staatsmedien behandeln denselben Ausbau als aggressive NATO-Einkreisung, die Eskalation treibt. Eine kleinere westeuropäische Strömung stellt infrage, ob Aufrüstung und Kriegswirtschafts-Drift gegenüber der kurzfristigen Bedrohung unverhältnismäßig geworden sind.',
 updated_at = now()
WHERE id = 'russia_nato_deterrence';

UPDATE friction_nodes SET
 name_de = 'Russische hybride Kriegsführung gegen Europa',
 description_en = 'Below-threshold gray-zone activity attributed to Russia in the Baltic and North Sea region and beyond: undersea cable and pipeline sabotage, GPS jamming and spoofing, shadow-fleet tanker operations evading sanctions, and espionage. Named incidents include the Nord Stream pipeline sabotage, the Eagle S cable-damage case, and the Druzhba pipeline.',
 description_de = 'Aktivität unterhalb der Kriegsschwelle in der Grauzone, die Russland im Ostsee- und Nordseeraum sowie darüber hinaus zugeschrieben wird: Sabotage an Unterseekabeln und Pipelines, GPS-Störung und Spoofing, Schattenflotten-Tankerbetrieb zur Sanktionsumgehung sowie Spionage. Zu den benannten Vorfällen zählen die Nord-Stream-Pipeline-Sabotage, der Eagle-S-Kabelschadensfall und die Druzhba-Pipeline.',
 editorial_summary_en = 'Western-mainstream and Baltic/Nordic coverage treats the pattern of sabotage, jamming and shadow-fleet activity as a coordinated Russian gray-zone campaign requiring attribution and hardened defences. Russian and allied state media dismiss the same incidents as evidence-free Russophobia, casting shadow-fleet enforcement as maritime piracy. A smaller Western-European current cautions against over-attribution, noting some incidents may be accidents or unrelated criminality.',
 editorial_summary_de = 'Die westliche Mainstream- und baltisch-nordische Berichterstattung behandelt das Muster aus Sabotage, Störung und Schattenflotten-Aktivität als koordinierte russische Grauzonen-Kampagne, die Attribution und gehärtete Abwehr erfordert. Russische und verbündete Staatsmedien weisen dieselben Vorfälle als beweisfreie Russophobie zurück und stellen die Durchsetzung gegen die Schattenflotte als Piraterie dar. Eine kleinere westeuropäische Strömung warnt vor Über-Attribution und weist darauf hin, dass manche Vorfälle Unfälle oder unabhängige Kriminalität sein könnten.',
 updated_at = now()
WHERE id = 'russia_hybrid_warfare';

UPDATE friction_nodes SET
 name_de = 'Luftraumverletzungen und NATO-Luftverteidigung an der Ostflanke',
 description_en = 'Incidents of drones and aircraft entering NATO airspace along the eastern flank, and the alliance''s air-defence response: scrambles, intercepts, national airspace closures, and debate over Article 4 consultations and shoot-down authority. The same airspace is also the subject of Russian claims that NATO and Baltic states allow Ukrainian drone operations to transit or launch from their territory.',
 description_de = 'Vorfälle, bei denen Drohnen und Flugzeuge entlang der Ostflanke in den NATO-Luftraum eindringen, sowie die Luftverteidigungsreaktion des Bündnisses: Abfangeinsätze, Luftraumsperrungen einzelner Staaten sowie die Debatte über Artikel-4-Konsultationen und Abschussbefugnis. Derselbe Luftraum ist zugleich Gegenstand russischer Behauptungen, NATO- und baltische Staaten ließen ukrainische Drohnenoperationen von ihrem Gebiet aus starten oder durchqueren.',
 editorial_summary_en = 'Western-mainstream and Baltic/Nordic coverage treats repeated incursions as deliberate Russian probing requiring a firm response, including shoot-down authority. Russian and allied state media invert the story, accusing NATO and Baltic states of enabling Ukrainian drone strikes and casting Russian countermeasures as legitimate self-defence. A smaller Western-European current warns that shoot-down authority over ambiguous contacts risks uncontrolled escalation, and that some incidents may be accidental.',
 editorial_summary_de = 'Die westliche Mainstream- und baltisch-nordische Berichterstattung behandelt wiederholte Einbrüche als gezielte russische Tests, die eine entschlossene Antwort einschließlich Abschussbefugnis erfordern. Russische und verbündete Staatsmedien kehren die Erzählung um, werfen NATO- und baltischen Staaten vor, ukrainische Drohnenangriffe zu ermöglichen, und stellen russische Gegenmaßnahmen als legitime Selbstverteidigung dar. Eine kleinere westeuropäische Strömung warnt, dass Abschussbefugnis gegenüber mehrdeutigen Kontakten unkontrollierte Eskalation riskiert und manche Vorfälle unfallbedingt sein könnten.',
 updated_at = now()
WHERE id = 'russia_airspace_incursions';
