-- Myanmar civil conflict: bilingual completeness fields (SPEC 6).
-- Register modelled on south_china_sea_claims: neutral factual description +
-- an editorial that names the coverage split without endorsing either side
-- (feedback_fn_descriptions_neutral: no framing, no motive attribution in the
-- FN's own prose -- framing lives in narratives_v2).

BEGIN;

UPDATE friction_nodes SET
  name_de = 'Bürgerkonflikt in Myanmar',
  description_en = 'Myanmar has been in political and armed conflict since the military removed the elected government in February 2021. The armed forces, organised politically around the Union Solidarity and Development Party, hold central power; a parallel National Unity Government, allied People''s Defence Forces and long-established ethnic armed organisations contest military control across much of the country. In elections held under military administration the military-aligned bloc won most seats, and former State Counsellor Aung San Suu Kyi remains in detention. Fighting includes airstrikes, ground offensives and clashes near the borders with Thailand, China and India. The border regions host large scam-compound and human-trafficking operations whose victims and proceeds cross the wider region, prompting Chinese prosecutions and cross-border enforcement. China, Russia, India and ASEAN states maintain varying degrees of engagement with the authorities in Naypyidaw.',
  description_de = 'Myanmar befindet sich seit der Absetzung der gewählten Regierung durch das Militär im Februar 2021 in einem politischen und bewaffneten Konflikt. Die Streitkräfte, politisch um die Union Solidarity and Development Party organisiert, halten die zentrale Macht; eine parallele Regierung der Nationalen Einheit, verbündete People''s Defence Forces und seit langem bestehende ethnische bewaffnete Organisationen stellen die militärische Kontrolle in weiten Teilen des Landes infrage. Bei unter Militärverwaltung abgehaltenen Wahlen gewann das militärnahe Lager die meisten Sitze; die frühere Staatsrätin Aung San Suu Kyi bleibt in Haft. Zu den Kampfhandlungen gehören Luftangriffe, Bodenoffensiven und Gefechte nahe den Grenzen zu Thailand, China und Indien. Die Grenzregionen beherbergen große Betrugszentren und Menschenhandelsoperationen, deren Opfer und Erlöse die weitere Region durchziehen und chinesische Strafverfolgung sowie grenzüberschreitende Einsätze nach sich ziehen. China, Russland, Indien und ASEAN-Staaten unterhalten unterschiedlich enge Beziehungen zu den Behörden in Naypyidaw.',
  editorial_summary_en = 'Myanmar''s conflict is regionally contained and draws limited direct involvement from major powers. The military-aligned bloc took most seats in elections held under military administration, Aung San Suu Kyi remains detained, and fighting continues between the armed forces and both opposition and ethnic armed organisations, while the border regions host industrial-scale scam compounds and trafficking. Coverage splits along two lines: Chinese and Russian state media present the post-election government as a legitimate transition backed by cooperation and engagement; Western and Southeast Asian democratic press treat the vote as a staged legitimation of military rule and document airstrikes, detentions and civilian casualties. The scam economy is reported across both as a transnational security problem.',
  editorial_summary_de = 'Der Konflikt in Myanmar ist regional begrenzt und zieht nur begrenzte direkte Beteiligung der Großmächte nach sich. Das militärnahe Lager gewann bei unter Militärverwaltung abgehaltenen Wahlen die meisten Sitze, Aung San Suu Kyi bleibt in Haft, und die Kämpfe zwischen den Streitkräften und sowohl der Opposition als auch ethnischen bewaffneten Organisationen dauern an, während die Grenzregionen Betrugszentren und Menschenhandel im industriellen Maßstab beherbergen. Die Berichterstattung teilt sich entlang zweier Linien: Chinesische und russische Staatsmedien stellen die Regierung nach der Wahl als legitimen Übergang dar, der durch Zusammenarbeit und Engagement gestützt wird; westliche und südostasiatische demokratische Medien werten die Wahl als inszenierte Legitimierung der Militärherrschaft und dokumentieren Luftangriffe, Inhaftierungen und zivile Opfer. Die Betrugswirtschaft wird von beiden Seiten als transnationales Sicherheitsproblem behandelt.',
  updated_at = now()
WHERE id = 'myanmar_civil_conflict';

COMMIT;
