# Docker Compose override for development environment
# This file is automatically loaded in development

version: '3.8'

services:
  api:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app  # Mount source code for hot reload
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models
    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app  # Mount source code for hot reload
      - ./logs:/app/logs
      - ./data:/app/data
      - ./models:/app/models

  scheduler:
    build:
      target: development
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app  # Mount source code for hot reload
      - ./logs:/app/logs

  flower:
    build:
      target: development
    environment:
      - ENVIRONMENT=development