---
# Strategic Narrative Intelligence (SNI) Pipeline Configuration
# Centralized window and parameter management for all pipeline stages

# Environment configuration
environment: development

# =============================================================================
# PIPELINE STAGE WINDOWS
# =============================================================================

# Ingestion stages
ingestion:
  # Incremental RSS processing - always use latest
  rss_incremental: true
  # Full-text enhancement window (0 = all pending articles)
  fulltext_window_hours: 0

# Keyword extraction
keywords:
  # Time window for processing articles 
  window_hours: 72
  # Processing mode: auto, short, full
  mode: auto

# CLUST-0: Event signals and materialized views
clust0:
  # Refreshes materialized views (no window needed)
  refresh_views: true

# CLUST-1: Taxonomy-aware clustering  
clust1:
  # Time window for article processing
  window_hours: 72
  # Clustering profile: strict, balanced, recall
  profile: strict
  # Hub-assisted clustering
  use_hub_assist: true
  # Hub pair cosine threshold 
  hub_pair_cos: 0.90
  # Macro classification enable
  macro_enable: true

# CLUST-2: Interpretive narrative clustering
clust2:
  # Maximum narratives to generate
  limit: 10

# CLUST-3: Narrative consolidation
clust3:
  # Candidate window for consolidation (converted to days: hours/24)
  candidate_window_hours: 72
  # Library window for existing narratives
  library_days: 90
  # Cosine similarity minimum threshold
  similarity_threshold: 0.82
  # Token Jaccard minimum threshold  
  jaccard_threshold: 0.40

# =============================================================================
# GENERATION PIPELINE 
# =============================================================================

# GEN-1: Card generation
gen1:
  enabled: true
  limit: 10

# GEN-2: Enrichment  
gen2:
  enabled: true
  limit: 10

# GEN-3: RAI overlay
gen3:
  enabled: true
  limit: 10

# =============================================================================
# PUBLISHER CONFIGURATION
# =============================================================================

publisher:
  # Evidence window (days)
  evidence_days: 7
  # Parent narrative window (days)  
  parent_days: 14
  # Minimum articles required
  min_articles: 4
  # Minimum sources required
  min_sources: 3
  # Maximum entropy threshold
  entropy_max: 2.40

# =============================================================================
# ENVIRONMENT OVERRIDES
# =============================================================================

environments:
  
  production:
    keywords:
      window_hours: 48
    clust1:
      window_hours: 48
      profile: strict
    clust2:
      limit: 5
    gen1:
      limit: 5
    gen2:
      limit: 5  
    gen3:
      limit: 5
    publisher:
      evidence_days: 14
      parent_days: 21
      min_articles: 6
      min_sources: 4
      entropy_max: 2.20
      
  staging:
    keywords:
      window_hours: 96
    clust1:
      window_hours: 96
      profile: balanced
    clust2:
      limit: 15
    publisher:
      evidence_days: 5
      parent_days: 10
      
  development:
    keywords:
      window_hours: 168  # 7 days
    clust1:
      window_hours: 168
      profile: recall
    clust2:
      limit: 20
    clust3:
      candidate_window_hours: 168
    publisher:
      evidence_days: 3
      parent_days: 7
      min_articles: 2
      min_sources: 2