---
# Strategic Narrative Intelligence (SNI) Pipeline Configuration
# Stage-specific windows matching operational requirements

global:
  timezone: "UTC"

ingestion:
  incremental_buffer_minutes: 5     # safety buffer for RSS processing

fetch_fulltext:
  pending_only: true                # process all pending; no window

keywords:
  window_hours: 72                  # re-extract for items updated in last N hours
  mode: auto                        # extraction mode: auto, short, full

library:                            # drives CLUST-0 library & hubs
  lib_window_days: 30               # stable vocabulary window (was 30d)
  hubs_top_n: 12
  df_min: 2

strategic_filter:
  strategic_window_hours: 300       # candidate window (was 300h)

clust1:
  window_hours: 72                  # the "current run" span
  use_hub_assist: true
  hub_pair_cos: 0.90
  densify_cosine: 0.86
  orphan_cosine: 0.89
  seed_min_size: 3
  seed_min_sources: 2

clust2:
  input_min_cluster_size: 4         # conservative gates
  input_min_sources: 3
  window_hours: 72                  # typically same as CLUST-1
  limit: 10                         # maximum narratives to generate

clust3:
  candidate_window_hours: 72        # only *process* raw narratives from last N hours
  similarity_threshold: 0.82
  conflict_threshold: 0.90
  # IMPORTANT: comparison library = ALL historical consolidated narratives (no window)

gen1:
  enabled: true
  limit: 10                         # maximum narratives to process

gen2:
  enabled: true
  limit: 10                         # maximum narratives to process

gen3:
  enabled: true
  limit: 10                         # maximum narratives to process
  rai:
    enabled: true
    timeout_sec: 30

publisher:
  evidence_days: 7                  # its own "window"
  parent_days: 14                   # its own "window"
  min_articles: 4
  min_sources: 3
  entropy_max: 2.40

# =============================================================================
# ENVIRONMENT OVERRIDES
# =============================================================================

environments:
  
  production:
    # Shorter windows for production efficiency
    keywords:
      window_hours: 48
    strategic_filter:
      strategic_window_hours: 240   # 10 days
    clust1:
      window_hours: 48
    clust2:
      window_hours: 48
    clust3:
      candidate_window_hours: 48
    gen1:
      enabled: true
    gen2:
      enabled: true
    gen3:
      enabled: true
    publisher:
      evidence_days: 14
      parent_days: 21
      min_articles: 6
      min_sources: 4
      entropy_max: 2.20
      
  staging:
    # Balanced settings for testing
    keywords:
      window_hours: 96
    strategic_filter:
      strategic_window_hours: 360   # 15 days
    clust1:
      window_hours: 96
    clust2:
      window_hours: 96
    clust3:
      candidate_window_hours: 96
    publisher:
      evidence_days: 5
      parent_days: 10
      
  development:
    # Longer windows for development/testing
    keywords:
      window_hours: 168             # 7 days
    strategic_filter:
      strategic_window_hours: 480   # 20 days
    clust1:
      window_hours: 168
    clust2:
      window_hours: 168
    clust3:
      candidate_window_hours: 168
    publisher:
      evidence_days: 3
      parent_days: 7
      min_articles: 2
      min_sources: 2