import DashboardLayout from '@/components/DashboardLayout';
import CentroidCard from '@/components/CentroidCard';
import MapSection from '@/components/MapSection';
import { getCentroidsByClass } from '@/lib/queries';
import { REGIONS } from '@/lib/types';
import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default async function HomePage() {
  const systemicCentroids = await getCentroidsByClass('systemic');
  const geoCentroids = await getCentroidsByClass('geo');

  const globalGeoCentroids = geoCentroids.filter(c => !c.primary_theater);
  const geoCentroidsWithMap = geoCentroids.filter(c => c.iso_codes && c.iso_codes.length > 0);

  return (
    <DashboardLayout>
      <div className="space-y-12">
        {/* Introduction */}
        <section className="max-w-3xl">
          <h1 className="text-5xl font-bold mb-6">Strategic Narrative Intelligence</h1>
          <p className="text-xl text-dashboard-text-muted mb-4">
            SNI presents AI-generated global news narratives organized by strategic actors and thematic lenses.
            Navigate intelligence across military, diplomatic, economic, and other critical domains.
          </p>
          <div className="flex gap-4">
            <Link href="#how-it-works" className="text-blue-400 hover:text-blue-300 underline">
              How it works
            </Link>
          </div>
        </section>

        {/* AI Disclaimer */}
        <section className="bg-dashboard-surface border border-dashboard-border rounded-lg p-6 max-w-3xl">
          <h2 className="text-xl font-semibold mb-2">AI-Generated Content</h2>
          <p className="text-dashboard-text-muted">
            All summaries, narratives, and event digests on this platform are generated by artificial intelligence.
            Content is derived from global news sources but should be verified independently for critical decisions.
          </p>
        </section>

        {/* Map */}
        <MapSection centroids={geoCentroidsWithMap} />

        {/* System Centroids */}
        <section>
          <h2 className="text-3xl font-bold mb-6">Global Thematic Lenses</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {systemicCentroids.map(centroid => (
              <CentroidCard key={centroid.id} centroid={centroid} />
            ))}
          </div>
        </section>

        {/* Global Geo Centroids */}
        {globalGeoCentroids.length > 0 && (
          <section>
            <h2 className="text-3xl font-bold mb-6">Global Non-State Actors</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {globalGeoCentroids.map(centroid => (
                <CentroidCard key={centroid.id} centroid={centroid} />
              ))}
            </div>
          </section>
        )}

        {/* Regions */}
        <section>
          <h2 className="text-3xl font-bold mb-6">Regional Intelligence</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {Object.entries(REGIONS).map(([key, label]) => (
              <Link
                key={key}
                href={`/region/${key}`}
                className="p-8 border border-dashboard-border bg-dashboard-surface rounded-lg hover:border-blue-500 transition text-center"
              >
                <h3 className="text-xl font-semibold">{label}</h3>
              </Link>
            ))}
          </div>
        </section>

        {/* How it works */}
        <section id="how-it-works" className="max-w-3xl">
          <h2 className="text-3xl font-bold mb-6">How SNI Works</h2>
          <div className="space-y-4 text-dashboard-text-muted">
            <p>
              <strong className="text-dashboard-text">1. Ingestion:</strong> SNI continuously monitors global news sources via RSS feeds,
              capturing thousands of articles daily across multiple languages.
            </p>
            <p>
              <strong className="text-dashboard-text">2. Strategic Filtering:</strong> Articles are filtered for strategic relevance
              using taxonomy matching and AI-powered gating, focusing on geopolitical, security, and economic developments.
            </p>
            <p>
              <strong className="text-dashboard-text">3. Centroid Assignment:</strong> Strategic articles are assigned to centroids
              (countries, regions, or thematic lenses) and classified into tracks (military, diplomacy, economic, etc.).
            </p>
            <p>
              <strong className="text-dashboard-text">4. Narrative Generation:</strong> AI synthesizes monthly summaries and event
              timelines for each centroid-track combination, creating structured intelligence narratives.
            </p>
            <p>
              <strong className="text-dashboard-text">5. Presentation:</strong> You navigate these narratives through an intuitive
              interface organized by actor, theme, and time.
            </p>
          </div>
        </section>
      </div>
    </DashboardLayout>
  );
}
